#pragma once

namespace MH4U {
constexpr const char* CB_s[] = {
    "(None)",
    "Elite Blade",
    "Elite Blade+",
    "Defender's Blade",
    "Kaiser Blade",
    "Blackguard",
    "Full Blackguard",
    "Sentinel Blade",
    "Sentinel Blade+",
    "Noblest of Lieges",
    "Dear Lutemis",
    "Dear Lutemia",
    "Dear Hecatel",
    "Dear Hecatelia",
    "Axelion Blade",
    "Halberion Blade",
    "Bardichion Blade",
    "Hellsire Blade",
    "Hellspawn Blade",
    "Guardsqual",
    "Guardsqual+",
    "Squaliarma",
    "Squaliarmada",
    "Elendskraft",
    "Leidenskraft",
    "Unheilskraft",
    "L'Oppresseur",
    "Deceadeus",
    "Heroic Deceadeus",
    "Permanence",
    "Izanami",
    "Fatalis Charger",
    "Ruiner Reaver",
    "Starlight Axe",
    "Grandstar Axe",
    "dummy35",
    "dummy36",
    "Full Blackguard+",
    "Schwarzschild",
    "K. Captain's Blade",
    "Die Walküre",
    "Arachnoscale",
    "Arachnoscale+",
    "Arachnoscythe",
    "Belobog's Scythe",
    "Schwarzschlum",
    "Schwarzschlum+",
    "Chernobog's Scythe",
    "Schildsect",
    "Schildsect+",
    "Galvanisect",
    "Dominisect",
    "Maximinsect",
    "Dear Rose",
    "Dear Rosetta",
    "Luna Eostre",
    "Azure Swallow",
    "Azure Skylark",
    "Rathflame Ubernova",
    "Blossomauler",
    "Propensity",
    "Serrated Glace",
    "Trios Tristesse",
    "The Haboob",
    "Desert Rose",
    "L'Essor",
    "Le Salut",
    "Elends/Essor",
    "Diablos Strongarm",
    "Cera Cediment",
    "Ceadeus Regalia",
    "Kyusen",
    "Watatsumi",
    "Daora's Casca",
    "Daora's Thwartoise",
    "Eldaora Casca",
    "Teostra's Striker",
    "Teostra's Nova",
    "Dios Strongarm",
    "Demolition C. Blade",
    "Fulgent Demolisher",
    "Lightbreak C. Blade",
    "Demonlord C. Blade",
    "Demonlord Supersurge",
    "Akantor C. Blade",
    "Akantor Severance",
    "Bebladed Implement",
    "Machina Razer",
    "Adélie the Savior",
    "Dalamadur C. Blade",
    "Patient Dalamadur",
    "True Fatalis Charger",
    "True Ruiner Reaver",
    "Fatalis Mien",
    "Aslat Charger",
    "Aslat Charger+",
    "Seditious C. Blade",
    "Garuda Sedition",
    "Forbidden Coffin",
    "Promised Nadir",
    "dummy100",
    "DUMMY",
    "DUMMY",
    "Awaritia",
    "Fallen Morgenröte",
    "Elite Blade",
    "Elite Blade",
    "Elite Blade",
    "Elite Blade",
    "Elite Blade",
    "Dear Lutemis",
    "Dear Lutemis",
    "Dear Lutemis",
    "Dear Lutemis",
    "Dear Lutemis",
    "Elendskraft",
    "Elendskraft",
    "Elendskraft",
    "Elendskraft",
    "Elendskraft",
    "Deceadeus",
    "Deceadeus",
    "Deceadeus",
    "Deceadeus",
    "Deceadeus"
};
}
