#pragma once

namespace MH4U {
constexpr const char* DB_s[] = {
    "(None)",
    "Matched Slicers",
    "Matched Slicers+",
    "Dual Slicers",
    "Dual Hatchets",
    "Dual Hatchets+",
    "Dual Cleavers+",
    "Hurricane",
    "Cyclone",
    "Rex Slicers",
    "Tigrex Claws",
    "Accursed Slicers",
    "Pouncing Graveclaws",
    "Freezing Daggers",
    "Freezing Daggers+",
    "Icicle Daggers",
    "Frozen Death",
    "Insecticutters",
    "Insecticutters+",
    "Insectiscythes",
    "Alated Insect",
    "Sworn Rapiers",
    "Holy Sabers",
    "Guild Knight Sabers",
    "Master Sabers",
    "Jaggid Shotels",
    "Leader's Shotels",
    "Fledderklauen",
    "Hungerklauen",
    "Aasklauen",
    "Les Apôtres",
    "Cleaving Jaws",
    "Cleaving Jaws+",
    "Cool Cleavers",
    "Frozen Cleavers",
    "Bone Scythes",
    "Bone Scythes+",
    "Chief's Scythes",
    "Dual Battleaxe",
    "Dual Battleaxe+",
    "Double Tabarzin",
    "Terminal Toxin",
    "Mortal Miasma",
    "Dual Chameleos",
    "Twin Flames",
    "High Twin Flames",
    "Wyvern Lovers",
    "Wyvern Strife",
    "Pink Maracas",
    "Funky Maracas",
    "Jungle Maracas",
    "Evergreen",
    "Whirlitwists",
    "Whirlitricks",
    "Whirlitorture",
    "Spiral Edges",
    "Gyro Wedges",
    "Snow Slicers",
    "Snow Sisters",
    "Maulagombs",
    "Brawlagombs",
    "Twin Chainsaws",
    "Usurper's Fulgur",
    "Despot's Blitz",
    "Levin Acrus",
    "Brimstren Drakeclaws",
    "Vprey Claws",
    "High Vprey Claws",
    "Raven Tessen",
    "Wolf Tessen",
    "Crow Tessen",
    "Kut-Ku Pair",
    "Kut-Ku Pair+",
    "Melting Wail",
    "Melting Blazer",
    "Dios Slicers",
    "Dios Slicers+",
    "Demolition Blades",
    "Dual Dragon",
    "Dual Dragon Ultimus",
    "Dual Dragon Ultimus+",
    "Felyne and Melynx",
    "Felyne and Melynx+",
    "Plesioth Cutlasses",
    "Plesioth Machetes",
    "Verdant Slashers",
    "Alluvion Slashers",
    "Glutton's Tools",
    "Gorger's Tools",
    "Worn Blades",
    "Weathered Blades",
    "Enduring Schism",
    "Twin Nails",
    "Fire and Ice",
    "Monarch",
    "Kirin Bolts",
    "Ritual Hailscreamers",
    "Wrath & Rancor",
    "Wrathful Predation",
    "Consummate Pair",
    "Akantor Blades",
    "Blackspine Bundles",
    "The Wrackful Gemini",
    "Ebonblood Twindrakes",
    "dummy104",
    "dummy105",
    "dummy106",
    "Dual Kut-Ku",
    "dummy108",
    "dummy109",
    "Twins Regnant",
    "Twins Regnant",
    "Twins Regnant",
    "Twins Regnant",
    "Twins Regnant",
    "Vprey Claws",
    "Vprey Claws",
    "Vprey Claws",
    "Vprey Claws",
    "Vprey Claws",
    "Tessen",
    "Tessen",
    "Tessen",
    "Tessen",
    "Tessen",
    "Ritual Ephemera",
    "Ritual Ephemera",
    "Ritual Ephemera",
    "Ritual Ephemera",
    "Ritual Ephemera",
    "Guild Knight Sabers",
    "Guild Knight Sabers",
    "Guild Knight Sabers",
    "Guild Knight Sabers",
    "Guild Knight Sabers",
    "DUMMY",
    "Tornado Hatchets",
    "Typhoon",
    "Pouncing Graveclaws+",
    "Razor Grisclaws",
    "Gelid Mind",
    "Gelid Soul",
    "Alated Insect+",
    "Entomotheos",
    "Master Sabers+",
    "Holy Guild Knight",
    "Le Paradis",
    "Le Shangri-La",
    "Inferno/Paradis",
    "Névé Bite",
    "Blizztrios Fangs",
    "Sandgnashers",
    "Psammophages",
    "Flamestorm",
    "Salamanders",
    "Ignis Noire",
    "Agnaktor Inferno",
    "Chameleos Blades",
    "Wyvern Strife+",
    "Wyvern Conciliation",
    "Evergreen+",
    "Paradise Green",
    "Crossdrills",
    "Crossveldts",
    "Crossenders",
    "Brawlagombs+",
    "Appallagombs",
    "Neo Twin Acrus",
    "Neo Acrus Whitebolt",
    "Brimstren Drakeclaws+",
    "Stygian Superbia",
    "Pox Tessen",
    "Garuga Gunsen",
    "Garuga Lovebirds",
    "Megiddo Rippers",
    "Megiddo Breakers",
    "Spectral Demolisher",
    "Lightbreak Twins",
    "Dual Dragons \"Angst\"",
    "Diablos Bashers",
    "Diablos Sinidex",
    "Sinistrus Dextraos",
    "Felyne and Melynx++",
    "Jade Plesioth Fans",
    "Jade Battlefanzers",
    "Savortooths",
    "Enduring Sacrifice",
    "Enduring Surrender",
    "Blizzard and Blaze",
    "Twin Elders",
    "Wunderkirins",
    "Ritual Eidolons",
    "Suzuka Takamaru",
    "Suzuka Otakemaru",
    "Doomfang \"Envoys\"",
    "Akantor Shadow Claws",
    "Ukanlos Ruinblades",
    "Ukanlos Skyrippers",
    "Mbale the Acute",
    "Dalamadur Spikes",
    "Amber Dalamadur",
    "Twinbane Blades",
    "Twinbane Twilight",
    "Ultimus Apocalypse",
    "Zakun Twins",
    "Zakun Twins+",
    "Seditious Talons",
    "Serre Sedition",
    "Recriminators",
    "Eternal Leavetakers",
    "Shaka Scarecrows",
    "Chum Scarecrows",
    "Chum-Chum Scarecrows",
    "dummy213",
    "Fan Club Fans",
    "DUMMY",
    "DUMMY",
    "Sea-king's Twins",
    "Sea-king's Twins",
    "Sea-king's Twins",
    "Sea-king's Twins",
    "Sea-king's Twins",
    "Blizzarioths",
    "Blizzarioths",
    "Blizzarioths",
    "Blizzarioths",
    "Blizzarioths",
    "Crooked Blades",
    "Cross Inferno"
};
}
