#pragma once

namespace MH4U {
constexpr const char* GL_s[] = {
    "(None)",
    "Iron Gunlance",
    "Iron Gunlance+",
    "Steel Gunlance",
    "Striker's Gunlance",
    "Defender's Gunlance",
    "Imperial Guardlance",
    "General's Arbalance",
    "Admiral's Arbalance",
    "Ancient Gyrelance",
    "Ancient Gyresmite",
    "Red Rook",
    "Red Rook+",
    "Crimson Rook",
    "Silver Rook",
    "Chariot Gun",
    "Dios Gunlance",
    "Dios Gunlance+",
    "Demolition Gunlance",
    "Full Voltage",
    "Full Generator",
    "Red Generator",
    "Bloodied Dynamo",
    "Red Devil Gunlance",
    "Red Devil Smasher",
    "Blue Devil Uberlance",
    "Blue Devil Opus",
    "White Gunlance",
    "White Cannon",
    "Black Gunlance",
    "Seadiver",
    "Seadiver+",
    "Deepbuster",
    "Deep Gunbuster",
    "Bone Gunlance",
    "Great Bone Gunlance",
    "Jaggid Gunlance",
    "Jaggid Gunlance+",
    "Hurricane Gunlance",
    "Tiger Blast",
    "Tigrex Gunlance",
    "Accursed Blast",
    "Menacing Gravegun",
    "Demon Gunlance",
    "Great Demon Gunlance",
    "Tyrannenarm",
    "Verräterarm",
    "Hochmutsarm",
    "L'Onde",
    "Princess Panoply",
    "Princess Panoply+",
    "Ortlinde",
    "Queen's Panoply",
    "Usurper's Roar",
    "Usurper's Roar+",
    "Despot's Phlogiston",
    "Brimstren Drakeblood",
    "Average Hitter",
    "Grand Slam",
    "Hard Hitter",
    "Big Slugger",
    "Lagomberator",
    "Lagomberatrix",
    "Lagomberastrophe",
    "Lagombergeddon",
    "Shell Gunbird",
    "Shell Gunbird+",
    "Noble Gunbird",
    "Royal Gunbird",
    "Peco Teepee",
    "Peco Teepee+",
    "Feather Gunlance",
    "Hypno Cannon",
    "Felyoshka",
    "Felyoshka+",
    "Felicitous Felyoshka",
    "Marine Fisher",
    "Abyssal Fisher",
    "Deep Blue Sea",
    "Leviathan Gunlance",
    "Worn Gunlance",
    "Weathered Gunlance",
    "Obelisk",
    "Luna's Howl",
    "Luna's Flare",
    "Icesteel Gunlance",
    "Daora's Brigia",
    "Brilliance",
    "Amaterasu",
    "Ravenous Gunlance",
    "Insatiable Gunlance",
    "Consummate Gunlance",
    "Akantor Gunlance",
    "Illstarred Gunlance",
    "The Celestial Fall",
    "Fatalis Gunlance",
    "dummy96",
    "dummy97",
    "dummy98",
    "dummy99",
    "Princess Panoply",
    "Princess Panoply",
    "Princess Panoply",
    "Princess Panoply",
    "Princess Panoply",
    "Full Voltage",
    "Full Voltage",
    "Full Voltage",
    "Full Voltage",
    "Full Voltage",
    "Luna's Howl",
    "Luna's Howl",
    "Luna's Howl",
    "Luna's Howl",
    "Luna's Howl",
    "General's Arbalance",
    "General's Arbalance",
    "General's Arbalance",
    "General's Arbalance",
    "General's Arbalance",
    "Silver Rook",
    "Silver Rook",
    "Silver Rook",
    "Silver Rook",
    "Silver Rook",
    "Admiral's Arbalance+",
    "Imperial Swornlance",
    "Progenesis",
    "Empire",
    "Lagia Burst",
    "Eutaxy Whitebolt",
    "Nether Jugulus",
    "World's Demise",
    "Eine Wahrheit",
    "Zvolta Demolisher",
    "Lightbreak Gunlance",
    "Blood Bolt",
    "Blood Thunder",
    "Rampage Cannonlance",
    "Rampage Firebelcher",
    "Black Gore Cannon",
    "Black Gore Buster",
    "Megalo Mincer",
    "Jones's Locker",
    "Tetrozonata",
    "Velenofragola",
    "Scissor Gunlance",
    "Scissor Cannon",
    "Violet Cannon",
    "Violet Buster",
    "Monsieur Gore",
    "Monsieur Gore+",
    "Madame Butcher",
    "Seltas Fortitude",
    "Menacing Gravegun+",
    "Hounding Grisgun",
    "Grt Demon Gunlance+",
    "Demonlord Gunlance",
    "Le Mur",
    "La Forteresse",
    "Mauer/Guerre",
    "Shining Ishtar",
    "Shining Astarte",
    "Shimmering Tiamat",
    "Oppressor's Skyfall",
    "Brimstren Drakeblood+",
    "Stygian Avaritia",
    "Big Slugger+",
    "Triple Crown",
    "Lagombalanche",
    "Lagombavalanga",
    "Royal Gunbird+",
    "Nightfall Cannon",
    "Nux Cannon",
    "Hypnos",
    "Cornpopper",
    "Mighty Cornpopper",
    "Diviathan Gunlance",
    "Sea Abyss",
    "Deus Obelisk",
    "Luna's Flare+",
    "Luna's Sun",
    "Daora's Tempest",
    "Eldaora's Brigia",
    "Venomous Perfume",
    "Iwato",
    "Amatsuhiko",
    "Doomlance \"Greed\"",
    "Akantor Cannonlance",
    "Ukanlos Gunlance",
    "Ukanlos Cannonlance",
    "Ethelbald the Dire",
    "Dalamadur Gunlance",
    "Unchained Dalamadur",
    "True Fatalis Gunlance",
    "Hellruin Gunlance",
    "W. Fatalis Gunlance",
    "Jaya Gunlance",
    "Jaya Gunlance+",
    "Seditious Gunlance",
    "Tamarod Sedition",
    "Towering Demise",
    "Auguring Prophet",
    "Bamboo Birdsbane",
    "Bamboo Lionsbane",
    "Bamboo Dragonsbane",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "Fangbreaker",
    "Fangbreaker",
    "Fangbreaker",
    "Fangbreaker",
    "Fangbreaker",
    "Tyrannenarm",
    "Tyrannenarm",
    "Tyrannenarm",
    "Tyrannenarm",
    "Tyrannenarm",
    "Era Blazer",
    "Gaping Abyss"
};
}
