#pragma once

namespace MH4U {
constexpr const char* Hammer_s[] = {
    "(None)",
    "War Hammer",
    "War Hammer+",
    "War Mace",
    "Iron Striker",
    "Iron Striker+",
    "Iron Impact",
    "Kurogane",
    "Iron Devil",
    "Fist of Fury",
    "Frozen Core",
    "Cocytus",
    "Gun Hammer",
    "Deadeye Revolver",
    "Sanctioned Gunhammer",
    "Burning Crusher",
    "Purse Bop",
    "Purse Bop+",
    "Bleeding Bopper",
    "Bleeding Basher",
    "Cluster Hammer",
    "Cluster Hammer+",
    "Cluster Musterer",
    "Master Musterer",
    "Usurper's Thunder",
    "Despot's Crackle",
    "Brimstren Drakemaw",
    "Mane Malice",
    "Mane Malice Rajang",
    "Accelerated Hammer",
    "Boosted Hammer",
    "Nitro Boost Hammer",
    "Full Throttle Mace",
    "Overclocker",
    "Wuchtblick",
    "Grimmblick",
    "Ächtungsblick",
    "Le Jugement",
    "Bone Hammer",
    "Bone Hammer+",
    "Bone Bludgeon",
    "Bone Bludgeon+",
    "Heavy Bone Bludgeon",
    "Striped Striker",
    "Tigrex Hammer",
    "Accursed Striker",
    "Tussive Gravemace",
    "Gigaton Hammer",
    "Titan Hammer",
    "Graviton Hammer",
    "Venom Crater",
    "Meaty Smash",
    "Meaty Smash+",
    "Meaty Press",
    "Pressure Cooker",
    "Venom Monster",
    "Venom Monster+",
    "Death Venom Hammer",
    "Purple Mace",
    "Pitohui Bird Mace",
    "Red Bludgeon",
    "Huracan Hammer",
    "Leonid Starcrusher",
    "Huracan Blueblaze",
    "Dios Tailhammer",
    "Dios Tailhammer+",
    "Demolition Hammer",
    "Kut-Ku Pick",
    "Kut-Ku Pick+",
    "Kut-Ku Thwap",
    "Dynamic Hammer",
    "Violence Hammer",
    "Raven Torrent",
    "Wolf Torrent",
    "Crow Torrent",
    "Basarios Blow",
    "Basarios Bash",
    "Oregalore",
    "Gemgalore",
    "Harmingbird",
    "Toxikeet",
    "Potio Bocciolo",
    "Carapace Hammer",
    "Carapace Hammer+",
    "Barroth Hammer",
    "Binding Bludgeon",
    "Armored Gogue",
    "Gaiasp",
    "Great Gaiarch",
    "White Kitty Stamp",
    "White Kitty Hammer",
    "Black Kitty Stamp",
    "Black Kitty Hammer",
    "Rusted Hammer",
    "Tarnished Hammer",
    "Breath Core Hammer",
    "Lava Core Hammer",
    "Teo Cratermaker",
    "Teo Cratergouger",
    "Worn Hammer",
    "Weathered Hammer",
    "Pulsating Core",
    "Icesteel Hammer",
    "Daora's Colossus",
    "Eminence",
    "Kushinada",
    "Devil's Due",
    "Devil's Crush",
    "Consummate Hammer",
    "Helixbone Slab",
    "The Extricating Blow",
    "Fatalis Buster",
    "dummy112",
    "dummy113",
    "dummy114",
    "dummy115",
    "Hidden Breaker",
    "Hidden Breaker",
    "Hidden Breaker",
    "Hidden Breaker",
    "Hidden Breaker",
    "Leonid Starcrusher",
    "Leonid Starcrusher",
    "Leonid Starcrusher",
    "Leonid Starcrusher",
    "Leonid Starcrusher",
    "Lunastra's Crown",
    "Lunastra's Crown",
    "Lunastra's Crown",
    "Lunastra's Crown",
    "Lunastra's Crown",
    "Devil Masher",
    "Devil Masher",
    "Devil Masher",
    "Devil Masher",
    "Devil Masher",
    "War Basher",
    "War Basher",
    "War Basher",
    "War Basher",
    "War Basher",
    "Kitty Hammer",
    "Kitty Hammer",
    "Kitty Hammer",
    "Kitty Hammer",
    "Kitty Hammer",
    "Ancient Blow",
    "Foolhardy Stone Fist",
    "Cocytus+",
    "Pykrete Punisher",
    "Improved Gunhammer",
    "Imperial Gunhammer",
    "Bleeding Basher+",
    "Bleeding Bludgeon",
    "Master Musterer+",
    "Scylla Maelstrom",
    "Scylla Maeltasrophe",
    "Oppressor's Sway",
    "Orcus Adflictus",
    "Brimstren Drakemaw+",
    "Stygian Industria",
    "Mane Master Rajang",
    "Demonlord Hammer",
    "Logicbreaker",
    "Boulverizer",
    "La Naissance",
    "La Terre",
    "Vergehen/Naissance",
    "Ceanataur Head Axe",
    "Carmine Axe",
    "The Great Divider",
    "Tussive Gravemace+",
    "Wracking Grismace",
    "Venom Crater+",
    "Glasya-Labolas",
    "Pressure Cooker+",
    "Morphing Brinicle",
    "Puffer Smash",
    "Pufferpounder",
    "Gypcer Rammer",
    "Gypceros Ramplifi",
    "Leonid Starcrusher+",
    "Svarog Starsmasher",
    "Rathalos Blueblazon",
    "Novagio Demolisher",
    "Lightbreak Hammer",
    "Mysterious Jaw",
    "Pox Torrent",
    "Garuga Effusion",
    "Gemgalore+",
    "Meteorgalore",
    "Bel Fiore",
    "Fiore Fantastico",
    "Barroth Basher",
    "Barroth Grandbasher",
    "Armored Gigagogue",
    "Mother Gaiarch",
    "Gaia Horizon",
    "Gold Cat Hammer",
    "Gold Cat Crusher",
    "Crust Core Hammer",
    "Teostra del Torre",
    "Meteoric Core",
    "Daora's Hyperborea",
    "Eldaora's Colossus",
    "Genie's Expanse",
    "Fugaku",
    "Nadeshiko",
    "Doomhammer \"Blood\"",
    "Ukanlos Trampler",
    "Ukanlos Skysmasher",
    "Edward the Tremor",
    "Dalamadur Hammer",
    "Agonized Dalamadur",
    "Fatalis Demolisher",
    "Fatalis Iregard",
    "Fatalis Ruiner",
    "Matraca Hammer",
    "Matraca Hammer+",
    "Seditious Hammer",
    "Qadar Sedition",
    "Empty Cage",
    "Desmos Admonition",
    "Arluq Whammer",
    "Swinging Scarluq",
    "Pride of Harth",
    "Black Belt Hammer",
    "Portsmark",
    "Teddybear",
    "Enormous Ham",
    "Ham of Hams",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "Apocalypse's Herald",
    "H.O.S.",
    "Crystal Nova",
    "Crystal Nova",
    "Crystal Nova",
    "Crystal Nova",
    "Crystal Nova",
    "Dragonbreaker",
    "Dragonbreaker",
    "Dragonbreaker",
    "Dragonbreaker",
    "Dragonbreaker"
};
}
