#pragma once

namespace MH4U {
constexpr const char* HBG_s[] = {
    "(None)",
    "Bone Shooter",
    "Bone Shooter+",
    "Straw Drumcannon",
    "Shirabeo",
    "Ratatat Drumcannon",
    "Queen's Longfire",
    "Queen's Farflier",
    "Queen's Scionfire",
    "Bone Buster",
    "Bone Blaster",
    "Agnablaster",
    "Agnablazer",
    "Bear Barrel",
    "Arbearalest",
    "Arzuros Gun",
    "Arzuros Gun+",
    "Power Stinger",
    "Power Stinger+",
    "Wild Stinger",
    "Ner Bustergun",
    "Ner Bustergun+",
    "Buster Blaster",
    "Gravios Howl",
    "Gravios Gigahowl",
    "Gravios Roar",
    "Gravios Gigaroar",
    "Mightning",
    "Loyal Thunder",
    "Tigrex Howl",
    "Tigrex Skull",
    "Accursed Roar",
    "Accursed Bellow",
    "Gravecannon",
    "Furious Gravecannon",
    "Pressurized Plaser",
    "Pressurized Plaser+",
    "Pluripotent Plaser",
    "Tropeco Gun",
    "Pecopious Gun",
    "Bite Blaster",
    "Biting Blast",
    "Dual Threat",
    "Diablazooka",
    "Peerless",
    "Masterless",
    "Arahabaki",
    "Daora's Delphinidae",
    "Daora Grande",
    "Teostra's Artillery",
    "Teostra's Flames",
    "Lunastra's Cannon",
    "Lunastra's Flames",
    "Akantor Cannon",
    "Caudalbone Crook",
    "The Omnipotent Blast",
    "Chaos Wing",
    "Albadash",
    "Vor Cannon",
    "Vor Buster",
    "Dual Threat",
    "Dual Threat",
    "Dual Threat",
    "Dual Threat",
    "Dual Threat",
    "Chaos Wing",
    "Chaos Wing",
    "Chaos Wing",
    "Chaos Wing",
    "Chaos Wing",
    "Tetsu Pyrotechnus",
    "Tetsu Pyropinnacle",
    "Empress's Blossom",
    "Empress's Flower",
    "Empress's Doublefleur",
    "Bone Blaster+",
    "Cartilage Blaster",
    "Crab Buster",
    "Heavy Crab Buster",
    "Violet Punisher",
    "Agna Magnum",
    "Agna Scorpion",
    "Arzuros Ozeki",
    "Arzuros Yokozuna",
    "Tödlicher Abzug",
    "Le Désastre",
    "La Foi",
    "Le Déluge",
    "Verrat/Foi",
    "Burst Stinker",
    "Fatal Stinker",
    "Buster Blaster+",
    "Nightfall Blaster",
    "Vampyr Blaster",
    "Gravios Gigacannon",
    "Oppressor's Wedge",
    "Orcus Quarcus",
    "Brimstren Drakemouth",
    "Stygian Humilitas",
    "Accursed Bellow+",
    "Furious Gravecannon+",
    "Livid Griscannon",
    "Dios Cannon",
    "Dios Cannon+",
    "Demolition Cannon",
    "Haize Demolisher",
    "Lightbreak Cannon",
    "Verdant Washbuckler",
    "Captain Verde",
    "Pecopious Thunder",
    "Precision Pico Peco",
    "Ravager Blast",
    "Yellow Buster",
    "Azure Blast",
    "Azure Buster",
    "Nero's Blazooka",
    "Griffon Blazooka",
    "Monodevilcaster",
    "Monodevilcaster+",
    "Monodevilblaster",
    "Utsurowazaru",
    "Eigoh",
    "Daora's Ceti",
    "Eldaora's Delphinidae",
    "Teostra's Firestorm",
    "Lunastra's Firestorm",
    "Kamaeleon",
    "Akantor Skysounder",
    "Ukanlos Cannon",
    "Ukanlos Skyblaster",
    "Robert the Vortex",
    "Dalamadur Cannon",
    "Militant Dalamadur",
    "Altheos Aetheria",
    "Vor Blaster",
    "Destiny's Arm",
    "Fatalis Enslaver",
    "Sayyad Cannon",
    "Sayyad Cannon+",
    "Seditious Cannon",
    "Furia Sedition",
    "Trembling Lordship",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "Gigant Launcher",
    "Gigant Launcher",
    "Gigant Launcher",
    "Gigant Launcher",
    "Gigant Launcher",
    "Cahoe",
    "Cahoe",
    "Cahoe",
    "Cahoe",
    "Cahoe",
    "Giant Pan",
    "Romea Crossbow"
};
}
