#pragma once

namespace MH4U {
constexpr const char* HH_s[] = {
    "(None)",
    "Metal Bagpipe",
    "Metal Bagpipe+",
    "Great Bagpipe",
    "Heavy Bagpipe",
    "Heavy Bagpipe+",
    "Fortissimo",
    "Master Bagpipe",
    "Sforzando",
    "Kummerklang",
    "Gramklang",
    "Trauerklang",
    "La Sépulture",
    "Valkyrie Chordmaker",
    "Valkyrie Chordmaker+",
    "Queen's Chordmaker",
    "Gold Chordmaker",
    "Kecha Whappa",
    "Kecha Whappa+",
    "Kechachacha Whappa",
    "Kecha Thumpa",
    "Kecha Clanga",
    "Usurper's Growl",
    "Usurper's Growl+",
    "Despot's Thunderclap",
    "Brimstren Drakesong",
    "Ice Kazoo",
    "Glacial Kazoo",
    "Frost Groaner",
    "Frost General",
    "Bone Horn",
    "Bone Horn+",
    "Hunter's Horn",
    "Hunter's Horn+",
    "Native's Horn",
    "Striped Gong",
    "Tigrex Horn",
    "Accursed Wail",
    "Howling Gravedrum",
    "Dios Bell",
    "Dios Bell+",
    "Demolition Chime",
    "Khezu Horn",
    "Khezu Flute",
    "Blood Horn",
    "Blood Flute",
    "War Drum",
    "War Bongo",
    "War Conga",
    "Jungle Bongo",
    "Jungle Conga",
    "Danger Call",
    "Danger Call+",
    "Hazardous Call",
    "Parahazard Call",
    "Velociprey Balloon",
    "Velociprey Balloon+",
    "Raven Shamisen",
    "Wolf Shamisen",
    "Crow Shamisen",
    "Basarios Rock",
    "Basarios Rock Mk.II",
    "Volcanic Rock",
    "Volcanic Gig",
    "Beating Gunrock",
    "Fleeting Gunrock",
    "Vicello Nulo (W)",
    "Vicello Unu (W)",
    "Vicello Du (W)",
    "Magia Charm",
    "Dragonwood Flute",
    "Worn Horn",
    "Weathered Horn",
    "Avenir's Music Box",
    "Akantor Horn",
    "Veilglare Hymn",
    "The Ascending Strain",
    "Fatalis Menace",
    "dummy78",
    "dummy79",
    "Megaphone",
    "Basarios Rock",
    "Basarios Rock",
    "Basarios Rock",
    "Basarios Rock",
    "Basarios Rock",
    "Hellstrings",
    "Hellstrings",
    "Hellstrings",
    "Hellstrings",
    "Hellstrings",
    "Swell Shell",
    "Swell Shell",
    "Swell Shell",
    "Swell Shell",
    "Swell Shell",
    "Gold Chordmaker",
    "Gold Chordmaker",
    "Gold Chordmaker",
    "Gold Chordmaker",
    "Gold Chordmaker",
    "Sforzando+",
    "Rinforzato",
    "La Joie",
    "Le Grégorien",
    "Grimm/Joie",
    "Gold Chordmaker+",
    "Lunar Chordmaker",
    "Kecha Clanga+",
    "Kecha Clanvira",
    "Oppressor's Boon",
    "Brimstren Drakesong+",
    "Stygian Tristitia",
    "Denden Daiko",
    "Denden Doomsounder",
    "Poli'ahu Pipe",
    "Phenomenal Phlute",
    "Howling Gravedrum+",
    "Dancing Grisdrum",
    "Timbral Demolisher",
    "Lightbreak Timbre",
    "Shell Castanet",
    "Shell Castanet+",
    "Colored Castanet",
    "Crabby Castanet",
    "Klick-Klack",
    "Blood Flute+",
    "Brute Flute",
    "Jungle Conga+",
    "Primal Conga",
    "Parahazard Call+",
    "Para Calamity",
    "Naja Warning",
    "Naja Alluvion",
    "Pox Shamisen",
    "Garuga Shamisen",
    "Volcanic Gig+",
    "Conflagrig",
    "Heavy Facemelter",
    "Lullaby Facemelter",
    "Magia Charmbell",
    "Aria Rhota",
    "Dragonwood Godflute",
    "Avenir's Music Box+",
    "Eternal Music Box",
    "Teostra's Tiple",
    "Teostra's Orphée",
    "Daora's Taus",
    "Daora's Baphophone",
    "Eldaora's Taus",
    "Genie's Ocarina",
    "Akantor Dark Melody",
    "Ukanlos Horned Flute",
    "Ukanlos Skysinger",
    "Orgueil the Insane",
    "Dalamadur Song",
    "Bloodied Dalamadur",
    "Fatalis Menace Lute",
    "Fatalis Menace Soul",
    "Fatalis Ancient Lute",
    "Vadya Muse",
    "Vadya Muse+",
    "Seditious Warhorn",
    "Maqam Sedition",
    "Clemency's Peal",
    "Onyx Terpsichore",
    "Glass Royale",
    "Queen's Flute",
    "Handmade Frog",
    "Hunter Master",
    "Emperor's Speech",
    "DUMMY",
    "DUMMY",
    "Scorpion Lute",
    "Endless Loop",
    "Sonic Glass",
    "Sonic Glass",
    "Sonic Glass",
    "Sonic Glass",
    "Sonic Glass",
    "Hidden Harmonic",
    "Hidden Harmonic",
    "Hidden Harmonic",
    "Hidden Harmonic",
    "Hidden Harmonic"
};
}
