#pragma once

namespace MH4U {
constexpr const char* IG_s[] = {
    "(None)",
    "Bone Staff",
    "Bone Staff+",
    "Bone Glaive",
    "Bone Glaive+",
    "Aerial Glaive",
    "Sturdy Glaive",
    "Sturdy Glaive+",
    "Sturdy Glaive Redux",
    "Stealth Glaive",
    "Stealth Glaive+",
    "Stealth Glaive Redux",
    "Shadow Walker",
    "Assault Glaive",
    "Assault Glaive+",
    "Forewalker",
    "Leumundslist",
    "Leumundsgift",
    "Leumundsbruch",
    "Le Traqueur",
    "Indigo Flash",
    "Azure Bolt",
    "Verdant Levin",
    "Violindigo Hail",
    "Violazure Sleet",
    "Violverdant Glaze",
    "Heaven's Rath Glaive",
    "Rathful Blaze Glaive",
    "Unprecedented Rath",
    "Metal Mauler",
    "Metal Mauler+",
    "Metalmangler",
    "Direspike Display",
    "Direspike Display+",
    "The Harmonious Stave",
    "Fatalis Glaive",
    "Fatalis Glaive+",
    "Fatalis Fate",
    "dummy38",
    "Sky-high Glaive",
    "Highest of Glaives",
    "Deep Blue Glaive",
    "Midnight Glaive",
    "Mind Stick",
    "Mind Stick \"Stone\"",
    "Mind Stick \"Rock\"",
    "Mind Stick \"Mount\"",
    "Mind Stick \"Wizard\"",
    "Mind Stick \"Wonder\"",
    "Mind Stick \"Demon\"",
    "Mind Stick \"Fiend\"",
    "Shell Intoner",
    "Shell Intoner+",
    "Crab Intoner",
    "Purple Intoner",
    "Hermit Scissors",
    "Spirit Eater",
    "Reaper's Stroke",
    "Silent Eye",
    "Silent Eye+",
    "Nightmare",
    "Needle Ivy",
    "Needle Ivy+",
    "Needle Vine",
    "Paralyzing Vine",
    "Medusa",
    "Medusa+",
    "Medusa Mirror",
    "Névé Rod",
    "Névé Rod+",
    "Névé Frost",
    "Fimbulvetr",
    "Sand Fauchard",
    "Sand Fauchard+",
    "Iörovellir",
    "Sect Happa",
    "Sect Happa+",
    "Trim Happa",
    "Cannibal Happa",
    "Diablos Rod",
    "Diablos Rod+",
    "Tyrant Rod",
    "Thanatos Rod",
    "Thanatos Rod+",
    "Anubis",
    "La Merveille",
    "Le Miracle",
    "List/Confiance",
    "Bruch/Logique",
    "Wehmut/Merveille",
    "Boltbrute",
    "King Boltbrute",
    "Emperor Boltbrute",
    "Icephantom",
    "Propagation",
    "Blossomajesty",
    "Universus",
    "Metalmangler+",
    "Demonlord Cudgel",
    "Demonlord Grudgel",
    "Self-possession",
    "Dalamadur Scepter",
    "Bounding Dalamadur",
    "Dios Rod",
    "Demolition Press",
    "Quantum Demolisher",
    "Lightbreak Press",
    "Ukanlos Staff",
    "Ukanlos Staff+",
    "Ukanlos Skytraveler",
    "Daora's Entom",
    "Daora's Tethidine",
    "Daora's Samudra",
    "Eldaora's Entom",
    "Eldaora's Tethidine",
    "Eldaora's Samudra",
    "Caster's Rod",
    "Caster's Rod+",
    "Hazy Caster",
    "True Fatalis Dyaus",
    "Hellruin Glaive",
    "Hellruin Glaive \"Gift\"",
    "Hellruin Glaive \"Omen\"",
    "Fatalis Soldier",
    "Fatalis Enforcer",
    "Fatalis Overlord",
    "Altair",
    "Altair+",
    "Seditious Breaker",
    "Lana Sedition",
    "Messenger's Mark",
    "Luminary's Mark",
    "Limbo Lacrimosa",
    "Clockwork",
    "dummy134",
    "dummy135",
    "dummy136",
    "dummy137",
    "Bone Staff",
    "Bone Staff",
    "Bone Staff",
    "Bone Staff",
    "Bone Staff",
    "Metal Mauler",
    "Metal Mauler",
    "Metal Mauler",
    "Metal Mauler",
    "Metal Mauler",
    "Leumundslist",
    "Leumundslist",
    "Leumundslist",
    "Leumundslist",
    "Leumundslist",
    "Sect Happa",
    "Sect Happa",
    "Sect Happa",
    "Sect Happa",
    "Sect Happa",
    "Dancing Mad",
    "Hades Shinerod"
};
}
