#pragma once

namespace MH4U {
constexpr const char* LBG_s[] = {
    "(None)",
    "Cross Bowgun",
    "Cross Bowgun+",
    "Grenade Launcher",
    "Grenade Launcher+",
    "Grenade Revolver",
    "Rathling Gun",
    "Rathling Doombringer",
    "Rathling Phoenix",
    "Azurathling Skysear",
    "Azurathling Sunsear",
    "Blossomayhem",
    "Jaggid Fire",
    "Bandit Fire",
    "Bandit's Rage",
    "Usurper's Crime",
    "Usurper's Crime+",
    "Despot's Wildfire",
    "Brimstren Drakekiss",
    "Brimstren Drakevow",
    "Cross Blitz",
    "Cross Blitzkrieg",
    "Shotgun (Azure)",
    "Blue Shooter",
    "Simple Shooter",
    "Simple Shooter+",
    "Shotgun (Blood)",
    "Crimson Blade Shower",
    "Rouge Shooter",
    "Shotgun (Green)",
    "Green Blade Shower",
    "Vert Shooter",
    "Shell Shooter",
    "Shell Gatling",
    "Insect Vulcan",
    "Hornet's Nest",
    "Sawgun",
    "Sawgun+",
    "Buzzawgun",
    "Buzzawcannon",
    "Fäulnisschleuder",
    "Wahnschleuder",
    "Teufelsschleuder",
    "La Lumière",
    "Le Condamnateur",
    "Dios Blaster",
    "Dios Blaster+",
    "Demolition Gun",
    "Khezu Syringe",
    "Khezu Hypo",
    "Hyodermic Miracle",
    "Kut-Ku Anger",
    "Kut-Ku Anger+",
    "Kut-Ku Counterattack",
    "Kut-Ku Rage",
    "Kut-Ku Barrage",
    "Raven Do",
    "Wolf Do",
    "Crow Do",
    "Royal Launcher",
    "Royal Torrent",
    "Royal Inundation",
    "Barro Barrel",
    "Barro Barrel+",
    "Barrozooka",
    "Thundacrus",
    "Thundacrus Rex",
    "Blizzard Cannon",
    "Tabula Blizzara",
    "Felyne Helldoll",
    "Black Parasol",
    "Demon's Isle",
    "Demon's Island",
    "God's Isle",
    "God's Island",
    "Blitz Bowgun",
    "Blitz Kirin",
    "Frigid Bowgun",
    "Frigid Kirin",
    "Devil's Grin",
    "Devil's Madness",
    "Diregun \"Dementia\"",
    "Rajang Barrage",
    "Ten Thousand Volts",
    "Barro Barrel",
    "Barro Barrel",
    "Barro Barrel",
    "Barro Barrel",
    "Barro Barrel",
    "Thundercrack",
    "Thundercrack",
    "Thundercrack",
    "Thundercrack",
    "Thundercrack",
    "Burst Revolver",
    "Volarevolver",
    "Searulean Firedance",
    "Searulean Firebath",
    "Mille Blossomayhem",
    "Prosperity",
    "Merciless Rage",
    "Oppressor's Rift",
    "Orcus Barqus",
    "Brimstren Drakevow+",
    "Stygian Invidia",
    "Blue Shooter+",
    "Blue Burst",
    "Rouge Shooter+",
    "Rouge Burst",
    "Vert Shooter+",
    "Machine Strafer",
    "Battalion Strafer",
    "Precision Pusca",
    "Precision Punisher",
    "La Vertu",
    "L'Éden",
    "Fäulnis/Vertu",
    "Ballista Demolisher",
    "Ballista Demolisher+",
    "Lightbreak Gun",
    "Blood Syringe",
    "Blood Injection",
    "Kut-Ku Barrage+",
    "Garuga Espringal",
    "Maelstrom",
    "Maelstrom+",
    "Plesioth Drencher",
    "Aurora Flare",
    "Glacialahti",
    "Arctica Cannon",
    "Neo Thundacrus",
    "Eclair Whitebolt",
    "Nether Phloxion",
    "Diamond Frost",
    "Diamond Crest",
    "Felyne Heavendoll",
    "God's Archipelago",
    "Blitz Kirin King",
    "Frigid Kirin King",
    "Doomgun \"Dementia\"",
    "Ten Million Volts",
    "Demonlord Cannon",
    "Tigrex Tank",
    "Tigrex Wargun",
    "Heavy Grisfire",
    "Zhen Angler",
    "Gobul Ganador",
    "Icesteel Wasp",
    "Daora's Hornet",
    "Eldaora's Hornet",
    "Genie's Lamp",
    "Ukanlos Flame Bow",
    "Ukanlos Skylighter",
    "Penetrating Gaze",
    "Hayha Voidmaker",
    "Krasnojarsk the Mad",
    "Dalamadur Fire",
    "Buoyant Dalamadur",
    "Dark Parasol",
    "Dith Valor",
    "Absolute Bowgun",
    "Rasasa Bowgun",
    "Rasasa Bowgun+",
    "Seditious Shot",
    "Vayu Sedition",
    "Bethorned Dystopia",
    "Shakalaka Prized Bow",
    "Hexed Shaka Bow",
    "Kettleblower",
    "Kettleblower Deluxe",
    "Arm Cannon",
    "Frilly Pink Parasol",
    "DUMMY",
    "Frilly Parasol",
    "Frilly Parasol",
    "Frilly Parasol",
    "Frilly Parasol",
    "Frilly Parasol",
    "Durambarrel",
    "Durambarrel",
    "Durambarrel",
    "Durambarrel",
    "Durambarrel",
    "Scatterfly Rack",
    "Rebel Paradigm";
}
}
