#pragma once

namespace MH4U {
constexpr const char* Palico_chest_s[] = {
    "(None)",
    "F Acorn Mail",
    "F Derring Lorica",
    "F Bone Mail",
    "F Alloy Mail",
    "F Ladybug Wings",
    "F Gargwa Vest",
    "F Arzuros Mail",
    "F Kecha Coat",
    "F Kut-Ku Wear",
    "F Bnaha Suit",
    "F Bulldrome Vest",
    "F Rheno Mail",
    "F Jaggi Mail",
    "F Mafumofu Vest",
    "F Yukumo Dogi",
    "F Mosgharl Mail",
    "F Ludroth Mail",
    "F Scylla Armor",
    "F Qurupeco Mail",
    "F Zamtrios Suit",
    "F Lagombi Mail",
    "F Cabra Wrap",
    "F Barroth Mail",
    "F Slagtoth Cape",
    "F Volvi Mail",
    "F Plesioth Suit",
    "F Tigrex Mail",
    "F Baggi Mail",
    "F Nibel Mail",
    "F Seltas Body",
    "F Uragaan Mail",
    "F Wroggi Mail",
    "F Guild Suit",
    "F Guide's Suit",
    "F Diablos Mail",
    "F Rathian Mail",
    "F Khezu Apron",
    "F Duram Mail",
    "F Zinogre Mail",
    "F Narga Mail",
    "F Rathalos Mail",
    "F Agnaktor Mail",
    "F Najarala Sirwal",
    "F Gore Ghost",
    "F Angel Feathers",
    "F Kaiser Robe",
    "F Vangis Mail",
    "F Akantor Facade",
    "F Escador Soul",
    "F Kushala Cista",
    "F Ukanlos Facade",
    "F Kirin Vest",
    "F Gigginox Mail",
    "F Puppeteer Garb",
    "F Brachy Gloves",
    "F Barioth Mail",
    "F Spartan Mail",
    "F Majestic Robe",
    "F Lagia Mail",
    "F Fencer Plate",
    "F Bannerman Plate",
    "F Marauder Armor",
    "dummy63",
    "dummy68",
    "dummy67",
    "F Chun Attire",
    "F Dante Jacket",
    "F Star Suit",
    "F Monqlo Tee",
    "F Fan Top",
    "dummy071",
    "F Mario Overalls",
    "F Luigi Overalls",
    "F Acorn Mail S",
    "F Derring Lorica S",
    "F Bone Mail S",
    "F Alloy Mail S",
    "F Ladybug Wings S",
    "F Gargwa Vest S",
    "F Arzuros Mail S",
    "F Kecha Coat S",
    "F Kut-Ku Wear S",
    "F Bnaha Suit S",
    "F Bulldrome Vest S",
    "F Rheno Mail S",
    "F Jaggi Mail S",
    "F Mafumofu Vest S",
    "F Yukumo Dogi S",
    "F Mosgharl Mail S",
    "F Ludroth Mail S",
    "F Scylla Armor S",
    "F Qurupeco Mail S",
    "F Zamtrios Suit S",
    "F Lagombi Mail S",
    "F Cabra Wrap S",
    "F Barroth Mail S",
    "F Slagtoth Cape S",
    "F Volvi Mail S",
    "F Plesioth Suit S",
    "F Tigrex Mail S",
    "F Baggi Mail S",
    "F Nibel Mail S",
    "F Seltas Body S",
    "F Uragaan Mail S",
    "F Wroggi Mail S",
    "F Guild Suit S",
    "F Guide's Suit S",
    "F Diablos Mail S",
    "F Rathian Mail S",
    "F Khezu Smock S",
    "F Duram Mail S",
    "F Zinogre Mail S",
    "F Narga Mail S",
    "F Rathalos Mail S",
    "F Agnaktor Mail S",
    "F Naja Sirwal S",
    "F Gore Ghost S",
    "F Angel Down S",
    "F Kaiser Panoply",
    "F Vangis Mail S",
    "F Akantor Facade S",
    "F Escador Soul S",
    "F Kushala Cormi S",
    "F Ukanlos Facade S",
    "F Kirin Vest S",
    "F Gigginox Mail S",
    "F Puppeteer Garb+",
    "F Brachy Fist S",
    "F Barioth Mail S",
    "F Olympian Mail",
    "F Majestic Robe+",
    "F Lagia Pirate S",
    "F Fencer Plate+",
    "F Bannerman Plate+",
    "F Marauder Armor S",
    "F Genie Carpet S",
    "F Garuga Robe S",
    "F Grav Armor S",
    "F Gypceros Cloth S",
    "F Daimyo Suit S",
    "F Cephalos Dress S",
    "F Basarios Mail S",
    "F Conga Fete S",
    "F Monoblos Mail S",
    "F Seregios Mail S",
    "F Gog Prison S",
    "Arcadia Robe",
    "Dirty F Hakama",
    "Felcote's Coat",
    "Straw Raincoat",
    "Shakalaka Duds",
    "F Sunsnug Vest S",
    "Beautiful Robe",
    "F Monqlo Tee S",
    "F Star Suit S",
    "dummy154",
    "dummy158",
    "dummy155",
    "F Blanka Pants",
    "Armor of Purrity",
    "dummy161",
    "F Melodic Suit",
    "F Fan Top G",
    "dummy165",
    "F Luigi Overalls S",
    "F Magical Robe",
    "Mega Man Suit",
    "F Mario Overalls S",
    "F Sonic Body",
    "F Pep Squad Suit",
    "Resetti Guise",
    "Isabelle Guise",
    "Transpurrter Cape"
};
}
