#pragma once

namespace MH4U {
constexpr const char* Palico_helmet_s[] = {
    "(None)",
    "F Acorn Helm",
    "F Derring Galea",
    "F Bone Helm",
    "F Alloy Helm",
    "F Ladybug Cap",
    "F Gargwa Mask",
    "F Arzuros Helm",
    "F Kecha Cap",
    "F Kut-Ku Mask",
    "F Bnaha Cap",
    "F Bulldrome Mask",
    "F Rheno Helm",
    "F Jaggi Helm",
    "F Mafumofu Hood",
    "F Yukumo Kasa",
    "F Mosgharl Hat",
    "F Ludroth Helm",
    "F Scylla Mask",
    "F Qurupeco Helm",
    "F Zamtrios Helmet",
    "F Lagombi Helm",
    "F Cabra Horn",
    "F Barroth Helm",
    "F Slagtoth Hood",
    "F Volvi Helm",
    "F Plesioth Cap",
    "F Tigrex Helm",
    "F Baggi Helm",
    "F Nibel Helm",
    "F Seltas Head",
    "F Uragaan Helm",
    "F Wroggi Helm",
    "F Guild Headgear",
    "F Guide's Hood",
    "F Diablos Helm",
    "F Rathian Helm",
    "F Khezu Cap",
    "F Duram Helm",
    "F Zinogre Helm",
    "F Narga Helm",
    "F Rathalos Helm",
    "F Agnaktor Helm",
    "F Naja Turban",
    "F Gore Horror",
    "F Angel Halo",
    "F Kaiser Periwig",
    "F Vangis Helm",
    "F Akantor Visage",
    "F Escador Wisdom",
    "F Kushala Glare",
    "F Ukanlos Visage",
    "F Kirin Horn",
    "F Gigginox Helm",
    "F Puppeteer Mask",
    "F Brachy Headgear",
    "F Barioth Helm",
    "F Spartan Helm",
    "F Majestic Crown",
    "F Lagia Tricorn",
    "F Fencer Helm",
    "F Bannerman Kasa",
    "F Marauder Helm",
    "dummy63",
    "dummy68",
    "F Chun Chignon",
    "F Star Hat",
    "F Monqlo Shades",
    "Meowniac's Mask",
    "F Mario Cap",
    "F Luigi Cap",
    "F Acorn Helm S",
    "F Derring Galea S",
    "F Bone Helm S",
    "F Alloy Helm S",
    "F Ladybug Cap S",
    "F Gargwa Mask S",
    "F Arzuros Helm S",
    "F Kecha Cap S",
    "F Kut-Ku Mask S",
    "F Bnaha Cap S",
    "F Bulldrome Mask S",
    "F Rheno Helm S",
    "F Jaggi Helm S",
    "F Mafumofu Hood S",
    "F Yukumo Kasa S",
    "F Mosgharl Hat S",
    "F Ludroth Helm S",
    "F Scylla Mask S",
    "F Qurupeco Helm S",
    "F Zamtrios Helmet S",
    "F Lagombi Helm S",
    "F Cabra Horn S",
    "F Barroth Helm S",
    "F Slagtoth Hood S",
    "F Volvi Helm S",
    "F Plesioth Cap S",
    "F Tigrex Helm S",
    "F Baggi Helm S",
    "F Nibel Helm S",
    "F Seltas Head S",
    "F Uragaan Helm S",
    "F Wroggi Helm S",
    "F Guild Headgear S",
    "F Guide's Hood S",
    "F Diablos Helm S",
    "F Rathian Helm S",
    "F Khezu Catnurse S",
    "F Duram Helm S",
    "F Zinogre Helm S",
    "F Narga Helm S",
    "F Rathalos Helm S",
    "F Agnaktor Helm S",
    "F Naja Turban S",
    "F Gore Horror S",
    "F Angel Aura S",
    "F Kaiser Crown",
    "F Vangis Helm S",
    "F Akantor Visage S",
    "F Escador Wisdom S",
    "F Kushala Glower S",
    "F Ukanlos Visage S",
    "F Kirin Horn S",
    "F Gigginox Helm S",
    "F Puppeteer Mask+",
    "F Brachy Noggin S",
    "F Barioth Helm S",
    "F Olympian Helm",
    "F Majestic Crown+",
    "F Lagia Triad S",
    "F Fencer Helm+",
    "F Bannerman Kasa+",
    "F Marauder Helm S",
    "F Genie Helm S",
    "F Garuga Hood S",
    "F Grav Mask S",
    "F Gypceros Crest S",
    "F Daimyo Mask S",
    "F Cephalos Hat S",
    "F Basarios Helm S",
    "F Conga Steeple S",
    "F Monoblos Helm S",
    "F Seregios Helm S",
    "F Gog Burden S",
    "Soul Hairpiece",
    "Dirty F Locks",
    "Pincer Mask",
    "Ultimate Mask",
    "Acorn Mask",
    "Beautiful Toque",
    "F Sunsnug Mask S",
    "dummy153",
    "F Monqlo Shades S",
    "Meowniac Mask G",
    "F Star Hat S",
    "F Luigi Cap S",
    "F Mario Cap S",
    "dummy156",
    "F Dante Wig",
    "F Melodic Curls",
    "Helm of Purrity",
    "dummy162",
    "F Magical Hat",
    "dummy",
    "Mega Man Helmet",
    "F Sonic Head",
    "Transpurrter Kasa",
    "F Pep Squad Cap"
};
}
