#pragma once

namespace MH4U {
constexpr const char* Palico_weapons_s[] = {
    "(None)",
    "F Bone Wedge",
    "F Derring Lance",
    "F Bone Hammer",
    "F Iron Sword",
    "F Bell Rod",
    "F Grilled Hammer",
    "F Arzuros Mace",
    "F Kecha Harrow",
    "F Kut-Ku Cutter",
    "F Bnaha Dagger",
    "F Bulldrome Tusk",
    "F Rheno Hammer",
    "F Jaggi Knife",
    "F Machalite Wedge",
    "F Giant Acorn",
    "F Wood Chopper",
    "F Barrel Basher",
    "F Vprey Wedge",
    "F Paw Punch",
    "F Yukumo Bokken",
    "F Mosgharl Broom",
    "F Ludroth Paw",
    "F Scylla Wedge",
    "F Qurupeco Axe",
    "F Zamtrios Paw",
    "F Lagombi Staff",
    "F Cabra Pounder",
    "F Barroth Mace",
    "F Slagtoth Leaf",
    "F Volvi Lantern",
    "F Plesioth Board",
    "F Tigrex Whammer",
    "F Baggi Billy",
    "F Nibel Blammer",
    "F Seltas Drill",
    "F Uragaan Iron",
    "F Wroggi Guitar",
    "F Guild Rapier",
    "F Diablos Hammer",
    "F Rathian Rapier",
    "F Khezu Whaccine",
    "F Duram Axe",
    "F Mewsurper's Peal",
    "F Narga Shuriken",
    "F Rathalos Blade",
    "F Agnaktor Lance",
    "F Naja Pungi",
    "F Katzenlampe",
    "F Le Cœur de Chat",
    "F Kaiser Mace",
    "F Vangis Mace",
    "F Akantor Sword",
    "F Escador Scythe",
    "F Kushala Wand",
    "F Ukanlos Sword",
    "F Kirin Rumblezap",
    "F Gigginox Fork",
    "F Golden Gadget",
    "F Brachy Punch",
    "F Barioth Knife",
    "F Cursed Cloud",
    "F Lagia Anchor",
    "F Fencer Sword",
    "F Bannerman Flag",
    "F Kitty Cornerer",
    "F Marauder Blade",
    "F Marauder Gavel",
    "dummy68",
    "dummy73",
    "F Blanka Fish",
    "dummy72",
    "Alastor",
    "F Star World",
    "F Monqlo Mallet",
    "F Fan Megaphone",
    "dummy76",
    "Invincible Hammer",
    "F Bone Wedge S",
    "F Derring Lance S",
    "F Bone Hammer S",
    "F Carbalite Sword",
    "F Bell Rod S",
    "F Fingerlicker",
    "F Arzuros Mace S",
    "F Kecha Harrow S",
    "F Kut-Ku Cutter S",
    "F Bnaha Dagger S",
    "F Bulldrome Tusk S",
    "F Rheno Hammer S",
    "F Jaggi Knife S",
    "F Carbalite Wedge",
    "F Giant Acorn S",
    "F Wood Chopper S",
    "F Barrel Basher S",
    "F Vprey Wedge S",
    "F Paw Punch S",
    "F Yukumo Bonito",
    "F Mosgharl Broom S",
    "F Ludroth Paw S",
    "F Scylla Wedge S",
    "F Qurupeco Axe S",
    "F Zamtrios Paw S",
    "F Lagombi Staff S",
    "F Cabra Pounder S",
    "F Barroth Mace S",
    "F Slagtoth Leaf S",
    "F Volvi Lantern S",
    "F Plesioth Board S",
    "F Tigrex Whammer S",
    "F Baggi Billy S",
    "F Nibel Blammer S",
    "F Seltas Drill S",
    "F Uragaan Iron S",
    "F Wroggi Guitar S",
    "F Guildcalibur",
    "F Diablos Hammer S",
    "F Queen Rapier",
    "F Khezu Whaccine S",
    "F Duram Axe S",
    "F Mewsurper's Roar",
    "F Narga Shuriken S",
    "F Blazing Blade",
    "F Agnaktor Lance S",
    "F Naja Pungi S",
    "F Katzenfunzel",
    "F Le Chatphrodite",
    "F Kaiser Mace S",
    "F Vangis Mace S",
    "F Akantor Sword S",
    "F Escador Scythe S",
    "F Kushala Wand S",
    "F Ukanlos Sword S",
    "F Kirin Bolt",
    "F Giggi Fork S",
    "F Golden Gadget S",
    "F Brachy Wallop",
    "F Barioth Knife S",
    "F Cursed Sky",
    "F Lagia Anchor S",
    "F Fencer Sword S",
    "F Bannerman Pride",
    "F King Catpetter",
    "Meowtetsuken",
    "F Pounderpurr",
    "F Genie Breath S",
    "F Garuga Fan S",
    "F Grav Bazooka S",
    "F Gypceros Glare S",
    "F Daimyo Shears S",
    "F Cephalos Brush S",
    "F Basarios Axe S",
    "F Conga Cymbals S",
    "F Monoblos Lance S",
    "F Seregios Edge S",
    "Fiendlyne Fetter",
    "Dragon Evertones",
    "Dirty F Blade",
    "Bulldrome Rrrush",
    "Kut-Ku Cackle",
    "dummy160",
    "dummy161",
    "F Monqlo Mallet S",
    "F Star World S",
    "dummy165",
    "Sword of Purrity",
    "F Chun Bracelets",
    "dummy167",
    "F Fan Megaphone G",
    "Invincible Hammer S",
    "F Melodic Baton",
    "dummy171",
    "F Magical Baton",
    "Rushing Hammer",
    "Caliburn",
    "Tenderpaw Clog",
    "Sentry's Pickaxe",
    "Minder's Binder",
    "Barrel Mallet"
};
}