#pragma once

namespace MH4U {
constexpr const char* Chest_s[] = {
    "(None)",
    "Derring Jacket",
    "Derring Mail S",
    "Derring Vest S",
    "Leather Vest",
    "Leather Mail S",
    "Leather Vest S",
    "Chainmail Vest",
    "Chainmail Armor S",
    "Chainmail Vest S",
    "Hunter's Mail",
    "Hunter's Vest",
    "Hunter's Mail S",
    "Hunter's Vest S",
    "Hunter's Mail",
    "Hunter's Vest",
    "Bone Mail",
    "Bone Vest",
    "Bone Mail S",
    "Bone Vest S",
    "Alloy Mail",
    "Alloy Vest",
    "Alloy Mail S",
    "Alloy Vest S",
    "Alloy Mail",
    "Alloy Vest",
    "Jaggi Mail",
    "Jaggi Vest",
    "Jaggi Mail S",
    "Jaggi Vest S",
    "Loc Lac Shawl",
    "Ludroth Mail",
    "Ludroth Vest",
    "Ludroth Mail",
    "Ludroth Vest",
    "Rhenoplos Mail",
    "Rhenoplos Vest",
    "Rhenoplos Mail S",
    "Rhenoplos Vest S",
    "Bnahabra Suit",
    "Bnahabra Vest",
    "Bnahabra Suit S",
    "Bnahabra Vest S",
    "Barroth Mail",
    "Barroth Vest",
    "Rathian Mail",
    "Rathian Vest",
    "Rathian Mail S",
    "Rathian Vest S",
    "Rath Heart Mail",
    "Rath Heart Vest",
    "Golden Lunemail",
    "Golden Lunevest",
    "Rathian Mail",
    "Rathian Vest",
    "Rath Heart Mail",
    "Rath Heart Vest",
    "EX Rathian Mail",
    "EX Rathian Vest",
    "Rathalos Mail",
    "Rathalos Vest",
    "Rathalos Mail S",
    "Rathalos Vest S",
    "Rath Soul Mail",
    "Rath Soul Vest",
    "Silver Solmail",
    "Silver Solvest",
    "Rathalos Mail",
    "Rathalos Vest",
    "Rath Soul Mail",
    "Rath Soul Vest",
    "Silver Solmail",
    "Silver Solvest",
    "EX Rathalos Mail",
    "EX Rathalos Vest",
    "Diablos Mail",
    "Diablos Vest",
    "Uragaan Mail",
    "Uragaan Vest",
    "Vangis Mail",
    "Vangis Vest",
    "Esurient Mail",
    "Esurient Vest",
    "Esurient Mail",
    "Esurient Vest",
    "Gloaming Plate",
    "Adamance Plate",
    "Dayspring Plate",
    "Epoch Plate",
    "Gloaming Archplate",
    "Adamance Archplate",
    "Dayspring Archplate",
    "Epoch Archplate",
    "Gloaming Plate",
    "Adamance Plate",
    "Dayspring Plate",
    "Epoch Plate",
    "Plesioth Mail",
    "Plesioth Vest",
    "Nibelsnarf Mail",
    "Nibelsnarf Vest",
    "Duramboros Mail",
    "Duramboros Vest",
    "Arzuros Mail",
    "Arzuros Vest",
    "Lagombi Mail",
    "Lagombi Vest",
    "Lagombi Mail S",
    "Lagombi Vest S",
    "Slagtoth Cloak",
    "Slagtoth Wrap",
    "Slagtoth Cloak S",
    "Slagtoth Wrap S",
    "Nargacuga Mail",
    "Nargacuga Vest",
    "Tigrex Mail",
    "Tigrex Vest",
    "Tigrex Mail S",
    "Tigrex Vest S",
    "Tigrex Mail U",
    "Tigrex Vest U",
    "Excello Mail",
    "Excello Vest",
    "EX Tigrex Mail",
    "EX Tigrex Vest",
    "Tigrex Mail",
    "Tigrex Vest",
    "Tigrex Mail U",
    "Tigrex Vest U",
    "Brachydios Mail",
    "Brachydios Vest",
    "Brachydios Mail S",
    "Brachydios Vest S",
    "Akantor Aegis",
    "Akantor Plate",
    "Akantor Aegis",
    "Akantor Plate",
    "Zinogre Mail",
    "Zinogre Vest",
    "Zinogre Mail S",
    "Zinogre Vest S",
    "Zinogre Mail U",
    "Zinogre Vest U",
    "Zinogre Mail U",
    "Zinogre Vest U",
    "EX Kaiser Mail",
    "EX Kaiser Vest",
    "Kecha Mail",
    "Kecha Vest",
    "Kecha Mail S",
    "Kecha Vest S",
    "Gore Mail",
    "Gore Vest",
    "Gore Mail S",
    "Gore Vest S",
    "Gore Mail",
    "Gore Vest",
    "Tetsucabra Mail",
    "Tetsucabra Vest",
    "Tetsucabra Mail S",
    "Tetsucabra Vest S",
    "Nerscylla Mail",
    "Nerscylla Vest",
    "Nerscylla Mail S",
    "Nerscylla Vest S",
    "Najarala Mail",
    "Najarala Vest",
    "Najarala Mail S",
    "Najarala Vest S",
    "Garuga Mail",
    "Garuga Vest",
    "Garuga Mail S",
    "Garuga Vest S",
    "Basarios Mail",
    "Basarios Vest",
    "Basarios Mail S",
    "Basarios Vest S",
    "Basarios Mail U",
    "Basarios Vest U",
    "Battle Mail",
    "Battle Vest",
    "Velociprey Mail",
    "Velociprey Vest",
    "Velociprey Mail S",
    "Velociprey Vest S",
    "Genprey Mail",
    "Genprey Vest",
    "Genprey Mail S",
    "Genprey Vest S",
    "Ioprey Mail",
    "Ioprey Vest",
    "Ioprey Mail S",
    "Ioprey Vest S",
    "Kut-Ku Mail",
    "Kut-Ku Vest",
    "Kut-Ku Mail S",
    "Kut-Ku Vest S",
    "Kut-Ku Mail U",
    "Kut-Ku Vest U",
    "Gypceros Mail",
    "Gypceros Vest",
    "Gypceros Mail S",
    "Gypceros Vest S",
    "Gypceros Mail U",
    "Gypceros Vest U",
    "Gypceros Mail",
    "Gypceros Vest",
    "Gypceros Mail U",
    "Gypceros Vest U",
    "Conga Mail",
    "Conga Vest",
    "Conga Mail S",
    "Conga Vest S",
    "Conga Mail U",
    "Conga Vest U",
    "Gravios Mail",
    "Gravios Vest",
    "Gravios Mail S",
    "Gravios Vest S",
    "Gravios Mail U",
    "Gravios Vest U",
    "Khezu Mail",
    "Khezu Vest",
    "Khezu Mail S",
    "Khezu Vest S",
    "Khezu Mail U",
    "Khezu Vest U",
    "Khezu Mail",
    "Khezu Vest",
    "Khezu Mail U",
    "Khezu Vest U",
    "Kirin Jacket",
    "Kirin Cape",
    "Kirin Jacket S",
    "Kirin Cape S",
    "Kirin Jacket U",
    "Kirin Cape U",
    "Kirin Jacket",
    "Kirin Cape",
    "Kirin Jacket U",
    "Kirin Cape U",
    "Kushala Cista",
    "Kushala Vise",
    "EX Kushala Cista",
    "EX Kushala Vise",
    "Kushala Cista",
    "Kushala Vise",
    "Empress Mail",
    "Empress Vest",
    "Ceanataur Mail",
    "Ceanataur Vest",
    "Ceanataur Mail",
    "Ceanataur Vest",
    "Auroros Torso",
    "Borealis Chest",
    "Genesis Torso",
    "Glyph Chest",
    "Auroros Torso",
    "Borealis Chest",
    "Genesis Torso",
    "Glyph Chest",
    "Lava Mail",
    "Lava Vest",
    "Remobra Suit",
    "Remobra Wear",
    "Remobra Suit S",
    "Remobra Wear S",
    "Zamtrios Mail",
    "Zamtrios Vest",
    "Zamtrios Mail S",
    "Zamtrios Vest S",
    "Seltas Mail",
    "Seltas Vest",
    "Seltas Mail S",
    "Seltas Vest S",
    "Arc Mail",
    "Arc Vest",
    "Arc Mail S",
    "Arc Vest S",
    "Arc Mail",
    "Arc Vest",
    "Kaiser Mail",
    "Kaiser Vest",
    "Golden Haori",
    "Puppeteer Suit",
    "Divine Ire Haori",
    "Crusher Garb",
    "Rebellion Mail",
    "Riot Vest",
    "Rebellion Mail",
    "Riot Vest",
    "Dragonhide X",
    "Dragonskin X",
    "Dragonhide",
    "Dragonskin",
    "Fatalis Crimsonhide",
    "Fatalis Crimsonskin",
    "Ioprey Body",
    "Ioprey Wear",
    "Cephalos Mail",
    "Cephalos Vest",
    "Mizuha Guards",
    "Cham Camise",
    "Hermitaur Mail",
    "Hermitaur Vest",
    "Hermitaur Mail",
    "Hermitaur Vest",
    "Vespoid Mail",
    "Vespoid Vest",
    "Qurupeco Mail",
    "Qurupeco Vest",
    "Agnaktor Mail",
    "Agnaktor Vest",
    "Barioth Mail",
    "Barioth Vest",
    "Volvidon Mail",
    "Volvidon Vest",
    "Lagiacrus Mail",
    "Lagiacrus Vest",
    "Lagiacrus Mail",
    "Lagiacrus Vest",
    "Helios Mail",
    "Helios Vest",
    "Selene Mail",
    "Selene Vest",
    "Gobul Mail",
    "Gobul Vest",
    "Yamato Doate",
    "Hyuga Muneate",
    "Mutsu Doate",
    "Amagi Muneate",
    "Escadora Soul",
    "Escadora Seele",
    "Escadora Soul",
    "Escadora Seele",
    "Blango Mail",
    "Blango Vest",
    "Lobster Mail",
    "Lobster Vest",
    "Ukanlos Aegis",
    "Ukanlos Plate",
    "Indra Vest",
    "Steadfast Vest",
    "Yaksha Raiment",
    "Carnage Raiment",
    "Artian Mail",
    "Artian Vest",
    "Artian Mail S",
    "Artian Vest S",
    "Artian Mail S",
    "Artian Vest S",
    "Dober Mail",
    "Dober Vest",
    "Ingot Mail",
    "Ingot Vest",
    "Ingot Mail",
    "Ingot Vest",
    "Aelucanth Thorax",
    "Rhopessa Thorax",
    "Aelucanth Pleuron",
    "Rhopessa Pleuron",
    "Obituary Thorax",
    "Butterfly Thorax",
    "Obituary Pleuron",
    "Butterfly Pleuron",
    "Mosgharl Ribplate",
    "Mosgharl Ribguard",
    "Guild Bard Bolero",
    "Scholar's Blouse",
    "Guild Bard Vest",
    "Scholar's Vest",
    "Black Belt Mail",
    "Black Belt Vest",
    "Guardian Suit",
    "Helper Suit",
    "Guardian Vest",
    "Helper Vest",
    "Shinobi Sky Suit",
    "Shinobi Land Suit",
    "Guild Knight Suit",
    "Maiden's Suit",
    "Guild Knight Vest",
    "Maiden's Vest",
    "Yukumo Sky Dogi",
    "Yukumo Land Dogi",
    "High Metal Mail",
    "High Metal Vest",
    "Ranger's Girdle",
    "Archer's Girdle",
    "Chakra Necklace",
    "Sailor Suit",
    "Sailor Vest",
    "Hawksuit",
    "Lecturer's Suit",
    "Hawkjacket",
    "Lecturer's Jacket",
    "Blue Star Suit",
    "Blue Star Jacket",
    "Mail of Anat",
    "Vest of Anat",
    "Fan Club Jacket",
    "Fan Club Tracksuit",
    "Uniqlo Bomber",
    "Uniqlo Hoodie",
    "Star Rook Mail",
    "Star Rook Vest",
    "dummy706",
    "dummy718",
    "dummy707",
    "dummy719",
    "Hunter's Camo Suit",
    "Hunter's Camo Jacket",
    "dummy709",
    "dummy721",
    "DUMMY",
    "DUMMY",
    "Rider Jacket",
    "Rider Leather",
    "dummy712",
    "dummy724",
    "DUMMY",
    "DUMMY",
    "Hero's Clothes",
    "Hero's Tunic",
    "dummy729",
    "dummy730",
    "dummy731",
    "dummy732",
    "EX Rebellion Mail",
    "EX Riot Vest",
    "EX Artian Mail",
    "EX Artian Vest",
    "EX Gore Mail",
    "EX Gore Vest",
    "EX Ingot Mail",
    "EX Ingot Vest",
    "EX Kirin Jacket U",
    "EX Kirin Cape U",
    "Storge Mail",
    "Storge Vest",
    "Storge Mail S",
    "Storge Vest S",
    "Storge Mail",
    "Storge Vest",
    "Hunter's Mail",
    "Hunter's Vest",
    "Alloy Mail",
    "Alloy Vest",
    "Ludroth Mail",
    "Ludroth Vest",
    "Rathian Mail",
    "Rathian Vest",
    "Rath Heart Mail",
    "Rath Heart Vest",
    "Rathalos Mail",
    "Rathalos Vest",
    "Rath Soul Mail",
    "Rath Soul Vest",
    "Silver Solmail",
    "Silver Solvest",
    "Esurient Mail",
    "Esurient Vest",
    "Gloaming Plate",
    "Adamance Plate",
    "Dayspring Plate",
    "Epoch Plate",
    "Tigrex Mail",
    "Tigrex Vest",
    "Tigrex Mail U",
    "Tigrex Vest U",
    "Akantor Aegis",
    "Akantor Plate",
    "Zinogre Mail U",
    "Zinogre Vest U",
    "Gore Mail",
    "Gore Vest",
    "Gypceros Mail",
    "Gypceros Vest",
    "Gypceros Mail U",
    "Gypceros Vest U",
    "Khezu Mail",
    "Khezu Vest",
    "Khezu Mail U",
    "Khezu Vest U",
    "Kirin Jacket",
    "Kirin Cape",
    "Kirin Jacket U",
    "Kirin Cape U",
    "Kushala Cista",
    "Kushala Vise",
    "Ceanataur Mail",
    "Ceanataur Vest",
    "Auroros Torso",
    "Borealis Chest",
    "Genesis Torso",
    "Glyph Chest",
    "Arc Mail",
    "Arc Vest",
    "Rebellion Mail",
    "Riot Vest",
    "Dragonhide X",
    "Dragonskin X",
    "Hermitaur Mail",
    "Hermitaur Vest",
    "Lagiacrus Mail",
    "Lagiacrus Vest",
    "Escadora Soul",
    "Escadora Seele",
    "Artian Mail S",
    "Artian Vest S",
    "Ingot Mail",
    "Ingot Vest",
    "Storge Mail",
    "Storge Vest",
    "Velociprey Mail X",
    "Velociprey Vest X",
    "Ioprey Mail X",
    "Ioprey Vest X",
    "Kecha Mail X",
    "Kecha Vest X",
    "Kecha Mail Z",
    "Kecha Vest Z",
    "Tetsucabra Mail X",
    "Tetsucabra Vest X",
    "Tetsucabra Mail Z",
    "Tetsucabra Vest Z",
    "Nerscylla Mail X",
    "Nerscylla Vest X",
    "Nerscylla Mail Z",
    "Nerscylla Vest Z",
    "Zamtrios Mail X",
    "Zamtrios Vest X",
    "Zamtrios Mail Z",
    "Zamtrios Vest Z",
    "Najarala Mail X",
    "Najarala Vest X",
    "Najarala Mail Z",
    "Najarala Vest Z",
    "Seltas Mail X",
    "Seltas Vest X",
    "Seltas Mail Z",
    "Seltas Vest Z",
    "Gore Mail X",
    "Gore Vest X",
    "Gore Armor",
    "Gore Pizane",
    "Arc Mail X",
    "Storge Mail X",
    "Arc Vest X",
    "Storge Vest X",
    "Arc Armor",
    "Storge Armor",
    "Arc Pizane",
    "Storge Pizane",
    "Gogma Mail",
    "Gogma Vest",
    "Gypceros Mail X",
    "Gypceros Vest X",
    "Gypceros Armor",
    "Gypceros Pizane",
    "Gypceros Mail Z",
    "Gypceros Vest Z",
    "Gypceros Armor U",
    "Gypceros Pizane U",
    "Lagombi Mail X",
    "Lagombi Vest X",
    "Conga Mail X",
    "Conga Vest X",
    "Conga Mail Z",
    "Conga Vest Z",
    "Khezu Mail X",
    "Khezu Vest X",
    "Khezu Armor",
    "Khezu Pizane",
    "Khezu Mail Z",
    "Khezu Vest Z",
    "Khezu Armor U",
    "Khezu Pizane U",
    "Rathian Mail X",
    "Rathian Vest X",
    "Rathian Armor",
    "Rathian Pizane",
    "Rath Heart Mail Z",
    "Rath Heart Vest Z",
    "Rath Heart Armor",
    "Rath Heart Pizane",
    "Golden Lunemail Z",
    "Golden Lunevest Z",
    "Rathalos Mail X",
    "Rathalos Vest X",
    "Rathalos Armor",
    "Rathalos Pizane",
    "Rath Soul Mail Z",
    "Rath Soul Vest Z",
    "Rath Soul Armor",
    "Rath Soul Pizane",
    "Silver Solmail Z",
    "Silver Solvest Z",
    "Silver Solarmor",
    "Silver Solpizane",
    "Zinogre Mail X",
    "Zinogre Vest X",
    "Zinogre Mail Z",
    "Zinogre Vest Z",
    "Zinogre Armor U",
    "Zinogre Pizane U",
    "Tigrex Mail X",
    "Tigrex Vest X",
    "Tigrex Armor",
    "Tigrex Pizane",
    "Tigrex Mail Z",
    "Tigrex Vest Z",
    "Tigrex Armor U",
    "Tigrex Pizane U",
    "Excello Mail Z",
    "Excello Vest Z",
    "Gravios Mail X",
    "Gravios Vest X",
    "Gravios Mail Z",
    "Gravios Vest Z",
    "Brachydios Mail X",
    "Brachydios Vest X",
    "Brachydium Mail",
    "Brachydium Vest",
    "Grand Gloaming Plate",
    "Grand Adamance Plate",
    "Grand Dayspring Plate",
    "Grand Epoch Plate",
    "Gloaming Redplate",
    "Adamance Redplate",
    "Dayspring Redplate",
    "Epoch Redplate",
    "Vangis Mail X",
    "Vangis Vest X",
    "Esurient Mail Z",
    "Esurient Vest Z",
    "Esurient Armor",
    "Esurient Pizane",
    "Kaiser Mail X",
    "Kaiser Vest X",
    "Akantor Aegis X",
    "Akantor Plate X",
    "Akantor Armor",
    "Akantor Pizane",
    "EX Escadora Soul",
    "EX Escadora Seele",
    "Ukanlos Aegis X",
    "Ukanlos Plate X",
    "Kushala Cista X",
    "Kushala Vise X",
    "Kushala Armor",
    "Kushala Pizane",
    "Kujula Cista",
    "Kujula Vise",
    "Grand God's Peer Robe",
    "Grand Hermit Robe",
    "Grand Divine Ire Robe",
    "Grand Crusher Robe",
    "Rebellion Mail X",
    "Riot Vest X",
    "Rebellion Armor",
    "Riot Pizane",
    "Rebellion Mail Z",
    "Riot Vest Z",
    "Cephalos Mail X",
    "Cephalos Vest X",
    "Hermitaur Mail X",
    "Hermitaur Vest X",
    "Hermitaur Armor",
    "Hermitaur Pizane",
    "Hermitaur Mail Z",
    "Hermitaur Vest Z",
    "Mono Mail S",
    "Mono Vest S",
    "Mono Mail X",
    "Mono Vest X",
    "Mono Mail",
    "Mono Vest",
    "Mono Armor",
    "Mono Pizane",
    "Monodevil Mail",
    "Monodevil Vest",
    "Monodevil Mail",
    "Monodevil Vest",
    "Monodevil Armor",
    "Monodevil Pizane",
    "Diablos Mail X",
    "Diablos Vest X",
    "Diablos Mail",
    "Diablos Vest",
    "Diablos Armor",
    "Diablos Pizane",
    "Diablos Mail Z",
    "Diablos Vest Z",
    "Dragonhide X",
    "Dragonskin X",
    "Dragonarmor X",
    "Dragonpizane X",
    "Fatalis Crimsonhide Z",
    "Fatalis Crimsonskin Z",
    "Fatalis Crimsonarmor Z",
    "Fatalis Crimsonpizane Z",
    "Wrothhide",
    "Wrothskin",
    "White Fatalis Hide",
    "White Fatalis Skin",
    "Grand Mizuha Guards",
    "Grand Cham Camise",
    "Regios Mail S",
    "Regios Vest S",
    "Regios Mail X",
    "Regios Vest X",
    "Chaos Mail",
    "Nephilim Mail",
    "Chaos Vest",
    "Nephilim Vest",
    "Basarios Mail X",
    "Basarios Vest X",
    "Basarios Mail Z",
    "Basarios Vest Z",
    "Kut-Ku Mail X",
    "Kut-Ku Vest X",
    "Kut-Ku Mail Z",
    "Kut-Ku Vest Z",
    "Garuga Mail X",
    "Garuga Vest X",
    "Kirin Jacket X",
    "Kirin Cape X",
    "Kirin Armor",
    "Kirin Pizane",
    "Kirin Jacket Z",
    "Kirin Cape Z",
    "Kirin Armor U",
    "Kirin Pizane U",
    "Bnahabra Suit X",
    "Bnahabra Vest X",
    "Slagtoth Cloak X",
    "Slagtoth Wrap X",
    "Rhenoplos Mail X",
    "Rhenoplos Vest X",
    "Hunter's Armor",
    "Hunter's Pizane",
    "Alloy Armor",
    "Alloy Pizane",
    "Artian Mail X",
    "Artian Vest X",
    "Arc Armor S",
    "Arc Pizane S",
    "Ingot Armor",
    "Ingot Pizane",
    "Guardian Suit X",
    "Helper Vest X",
    "Guardian Vest X",
    "Healer Vest X",
    "Guardian Suit Z",
    "Helper Vest Z",
    "Guardian Vest Z",
    "Healer Vest Z",
    "G. Knight Suit X",
    "Maiden's Suit X",
    "G. Knight Vest X",
    "Exclusive Vest X",
    "Ace Mail",
    "Sororal Mail",
    "Ace Vest",
    "Sororal Vest",
    "Ceanataur Armor",
    "Ceanataur Pizane",
    "Lagiacrus Armor",
    "Lagiacrus Pizane",
    "Escadora Armor",
    "Escadora Pizane",
    "Auroros Kermes Plate",
    "Borealis Woad Plate",
    "Genesis Kermes Plate",
    "Glyph Woad Plate",
    "Ludroth Armor",
    "Ludroth Pizane",
    "Hornet Mail",
    "Hornet Vest",
    "Hornet Armor",
    "Hornet Pizane",
    "Wroggi Mail",
    "Wroggi Vest",
    "Wroggi Armor",
    "Wroggi Pizane",
    "Gigginox Mail",
    "Gigginox Vest",
    "Gigginox Armor",
    "Gigginox Pizane",
    "Tempest Robe",
    "Welkin Robe",
    "Tempest Vesture",
    "Welkin Vesture",
    "Death Stench Muscle",
    "Death Stench Heart",
    "Death Stench Armor",
    "Death Stench Pizane",
    "Damascus Mail",
    "Damascus Vest",
    "Damascus Armor",
    "Damascus Pizane",
    "Lagiacrus Mail X",
    "Lagiacrus Vest X",
    "Nargacuga Mail X",
    "Nargacuga Vest X",
    "Empress Mail X",
    "Empress Vest X",
    "Helios Mail X",
    "Selene Mail X",
    "Helios Vest X",
    "Selene Vest X",
    "Agnaktor Mail X",
    "Agnaktor Vest X",
    "Qurupeco Mail X",
    "Qurupeco Vest X",
    "Gobul Mail X",
    "Gobul Vest X",
    "Barioth Mail X",
    "Barioth Vest X",
    "Barroth Mail X",
    "Barroth Vest X",
    "Nibelsnarf Mail X",
    "Nibelsnarf Vest X",
    "Duramboros Mail X",
    "Duramboros Vest X",
    "Lava Mail X",
    "Lava Vest X",
    "Grand Yamato Doate",
    "Grand Hyuga Muneate",
    "Grand Mutsu Doate",
    "Grand Amagi Muneate",
    "Grand Yaksha Raiment",
    "Grand Carnage Raiment",
    "Miralis Breastplate",
    "Miralis Chestguard",
    "Plesioth Mail Z",
    "Plesioth Vest Z",
    "Kita Star Jacket",
    "Umi Ocean Jacket",
    "Patissier's Suit",
    "Patissier's Vest",
    "High Metal Mail S",
    "High Metal Vest S",
    "Aelucanth Thorax X",
    "Rhopessa Thorax X",
    "Aelucanth Pleuron X",
    "Rhopessa Pleuron X",
    "Obituary Thorax X",
    "Butterfly Thorax X",
    "Obituary Pleuron X",
    "Butterfly Pleuron X",
    "EX Auroros Torso",
    "EX Borealis Chest",
    "EX Genesis Torso",
    "EX Glyph Chest",
    "Tempest Robe",
    "Welkin Robe",
    "GX Escadora Armor",
    "GX Escadora Pizane",
    "GX Dragonarmor X",
    "GX Dragonpizane X",
    "Star Knight Mail",
    "Star Knight Vest",
    "Mail of Rage",
    "Vest of Rage",
    "Varia Suit Armor",
    "Zero Suit Body",
    "Varia Suit Barrier",
    "Zero Suit Wear",
    "Varia Suit Armor",
    "Zero Suit Body",
    "Varia Suit Barrier",
    "Zero Suit Wear",
    "Fan Club Goldsuit",
    "Fan Club Silversuit",
    "Hawksuit X",
    "Lecturer's Suit X",
    "Hawkjacket X",
    "Lecturer's Jacket X",
    "GX Hunter's Armor",
    "GX Hunter's Pizane",
    "GX Esurient Armor",
    "GX Esurient Pizane",
    "GX Tempest Vesture",
    "GX Welkin Vesture",
    "GX Fatalis Crimsonarmor",
    "GX Fatalis Crimsonpizane",
    "Hunter's Mail",
    "Hunter's Vest",
    "Hunter's Mail",
    "Hunter's Vest",
    "Ludroth Mail",
    "Ludroth Vest",
    "Ludroth Mail",
    "Ludroth Vest",
    "Alloy Mail",
    "Alloy Vest",
    "Alloy Mail",
    "Alloy Vest",
    "Gypceros Mail",
    "Gypceros Vest",
    "Gypceros Mail",
    "Gypceros Vest",
    "Khezu Mail",
    "Khezu Vest",
    "Khezu Mail",
    "Khezu Vest",
    "Ingot Mail",
    "Ingot Vest",
    "Ingot Mail",
    "Ingot Vest",
    "Rathian Mail",
    "Rathian Vest",
    "Lagiacrus Mail",
    "Lagiacrus Vest",
    "Rathalos Mail",
    "Rathalos Vest",
    "Gypceros Mail U",
    "Gypceros Vest U",
    "Khezu Mail U",
    "Khezu Vest U",
    "Tigrex Mail",
    "Tigrex Vest",
    "Kirin Jacket",
    "Kirin Cape",
    "Kirin Jacket",
    "Kirin Cape",
    "Artian Mail S",
    "Artian Vest S",
    "Ceanataur Mail",
    "Ceanataur Vest",
    "Ceanataur Mail",
    "Ceanataur Vest",
    "Gloaming Plate",
    "Dayspring Plate",
    "Adamance Plate",
    "Epoch Plate",
    "Zinogre Mail U",
    "Zinogre Vest U",
    "Tigrex Mail U",
    "Tigrex Vest U",
    "Gore Mail",
    "Gore Vest",
    "Auroros Torso",
    "Genesis Torso",
    "Borealis Chest",
    "Glyph Chest",
    "Kirin Jacket U",
    "Kirin Cape U",
    "Kirin Jacket U",
    "Kirin Cape U",
    "Esurient Mail",
    "Esurient Vest",
    "Monoblos Mail",
    "Monoblos Vest",
    "Hornet Mail",
    "Hornet Vest",
    "Wroggi Mail",
    "Wroggi Vest",
    "Monodevil Mail",
    "Monodevil Vest",
    "Diablos Mail",
    "Diablos Vest",
    "Gigginox Mail",
    "Gigginox Vest",
    "Death Stench Muscle",
    "Death Stench Heart",
    "Damascus Mail",
    "Damascus Vest",
    "DUMMY",
    "DUMMY"
};

enum Chest_e {
    NoChest,
    Derring_Jacket,
    Derring_Mail_S,
    Derring_Vest_S,
    Leather_Vest,
    Leather_Mail_S,
    Leather_Vest_S,
    Chainmail_Vest,
    Chainmail_Armor_S,
    Chainmail_Vest_S,
    Hunter_s_Mail_0,
    Hunter_s_Vest_0,
    Hunter_s_Mail_S,
    Hunter_s_Vest_S,
    Hunter_s_Mail_1,
    Hunter_s_Vest_1,
    Bone_Mail,
    Bone_Vest,
    Bone_Mail_S,
    Bone_Vest_S,
    Alloy_Mail_0,
    Alloy_Vest_0,
    Alloy_Mail_S,
    Alloy_Vest_S,
    Alloy_Mail_1,
    Alloy_Vest_1,
    Jaggi_Mail,
    Jaggi_Vest,
    Jaggi_Mail_S,
    Jaggi_Vest_S,
    Loc_Lac_Shawl,
    Ludroth_Mail_0,
    Ludroth_Vest_0,
    Ludroth_Mail_1,
    Ludroth_Vest_1,
    Rhenoplos_Mail,
    Rhenoplos_Vest,
    Rhenoplos_Mail_S,
    Rhenoplos_Vest_S,
    Bnahabra_Suit,
    Bnahabra_Vest,
    Bnahabra_Suit_S,
    Bnahabra_Vest_S,
    Barroth_Mail,
    Barroth_Vest,
    Rathian_Mail_0,
    Rathian_Vest_0,
    Rathian_Mail_S,
    Rathian_Vest_S,
    Rath_Heart_Mail_0,
    Rath_Heart_Vest_0,
    Golden_Lunemail,
    Golden_Lunevest,
    Rathian_Mail_1,
    Rathian_Vest_1,
    Rath_Heart_Mail_1,
    Rath_Heart_Vest_1,
    EX_Rathian_Mail,
    EX_Rathian_Vest,
    Rathalos_Mail_0,
    Rathalos_Vest_0,
    Rathalos_Mail_S,
    Rathalos_Vest_S,
    Rath_Soul_Mail_0,
    Rath_Soul_Vest_0,
    Silver_Solmail_0,
    Silver_Solvest_0,
    Rathalos_Mail_1,
    Rathalos_Vest_1,
    Rath_Soul_Mail_1,
    Rath_Soul_Vest_1,
    Silver_Solmail_1,
    Silver_Solvest_1,
    EX_Rathalos_Mail,
    EX_Rathalos_Vest,
    Diablos_Mail_0,
    Diablos_Vest_0,
    Uragaan_Mail,
    Uragaan_Vest,
    Vangis_Mail,
    Vangis_Vest,
    Esurient_Mail_0,
    Esurient_Vest_0,
    Esurient_Mail_1,
    Esurient_Vest_1,
    Gloaming_Plate_0,
    Adamance_Plate_0,
    Dayspring_Plate_0,
    Epoch_Plate_0,
    Gloaming_Archplate,
    Adamance_Archplate,
    Dayspring_Archplate,
    Epoch_Archplate,
    Gloaming_Plate_1,
    Adamance_Plate_1,
    Dayspring_Plate_1,
    Epoch_Plate_1,
    Plesioth_Mail,
    Plesioth_Vest,
    Nibelsnarf_Mail,
    Nibelsnarf_Vest,
    Duramboros_Mail,
    Duramboros_Vest,
    Arzuros_Mail,
    Arzuros_Vest,
    Lagombi_Mail,
    Lagombi_Vest,
    Lagombi_Mail_S,
    Lagombi_Vest_S,
    Slagtoth_Cloak,
    Slagtoth_Wrap,
    Slagtoth_Cloak_S,
    Slagtoth_Wrap_S,
    Nargacuga_Mail,
    Nargacuga_Vest,
    Tigrex_Mail_0,
    Tigrex_Vest_0,
    Tigrex_Mail_S,
    Tigrex_Vest_S,
    Tigrex_Mail_U_0,
    Tigrex_Vest_U_0,
    Excello_Mail,
    Excello_Vest,
    EX_Tigrex_Mail,
    EX_Tigrex_Vest,
    Tigrex_Mail_1,
    Tigrex_Vest_1,
    Tigrex_Mail_U_1,
    Tigrex_Vest_U_1,
    Brachydios_Mail,
    Brachydios_Vest,
    Brachydios_Mail_S,
    Brachydios_Vest_S,
    Akantor_Aegis_0,
    Akantor_Plate_0,
    Akantor_Aegis_1,
    Akantor_Plate_1,
    Zinogre_Mail,
    Zinogre_Vest,
    Zinogre_Mail_S,
    Zinogre_Vest_S,
    Zinogre_Mail_U_0,
    Zinogre_Vest_U_0,
    Zinogre_Mail_U_1,
    Zinogre_Vest_U_1,
    EX_Kaiser_Mail,
    EX_Kaiser_Vest,
    Kecha_Mail,
    Kecha_Vest,
    Kecha_Mail_S,
    Kecha_Vest_S,
    Gore_Mail_0,
    Gore_Vest_0,
    Gore_Mail_S,
    Gore_Vest_S,
    Gore_Mail_1,
    Gore_Vest_1,
    Tetsucabra_Mail,
    Tetsucabra_Vest,
    Tetsucabra_Mail_S,
    Tetsucabra_Vest_S,
    Nerscylla_Mail,
    Nerscylla_Vest,
    Nerscylla_Mail_S,
    Nerscylla_Vest_S,
    Najarala_Mail,
    Najarala_Vest,
    Najarala_Mail_S,
    Najarala_Vest_S,
    Garuga_Mail,
    Garuga_Vest,
    Garuga_Mail_S,
    Garuga_Vest_S,
    Basarios_Mail,
    Basarios_Vest,
    Basarios_Mail_S,
    Basarios_Vest_S,
    Basarios_Mail_U,
    Basarios_Vest_U,
    Battle_Mail,
    Battle_Vest,
    Velociprey_Mail,
    Velociprey_Vest,
    Velociprey_Mail_S,
    Velociprey_Vest_S,
    Genprey_Mail,
    Genprey_Vest,
    Genprey_Mail_S,
    Genprey_Vest_S,
    Ioprey_Mail,
    Ioprey_Vest,
    Ioprey_Mail_S,
    Ioprey_Vest_S,
    Kut_Ku_Mail,
    Kut_Ku_Vest,
    Kut_Ku_Mail_S,
    Kut_Ku_Vest_S,
    Kut_Ku_Mail_U,
    Kut_Ku_Vest_U,
    Gypceros_Mail_0,
    Gypceros_Vest_0,
    Gypceros_Mail_S,
    Gypceros_Vest_S,
    Gypceros_Mail_U_0,
    Gypceros_Vest_U_0,
    Gypceros_Mail_1,
    Gypceros_Vest_1,
    Gypceros_Mail_U_1,
    Gypceros_Vest_U_1,
    Conga_Mail,
    Conga_Vest,
    Conga_Mail_S,
    Conga_Vest_S,
    Conga_Mail_U,
    Conga_Vest_U,
    Gravios_Mail,
    Gravios_Vest,
    Gravios_Mail_S,
    Gravios_Vest_S,
    Gravios_Mail_U,
    Gravios_Vest_U,
    Khezu_Mail_0,
    Khezu_Vest_0,
    Khezu_Mail_S,
    Khezu_Vest_S,
    Khezu_Mail_U_0,
    Khezu_Vest_U_0,
    Khezu_Mail_1,
    Khezu_Vest_1,
    Khezu_Mail_U_1,
    Khezu_Vest_U_1,
    Kirin_Jacket_0,
    Kirin_Cape_0,
    Kirin_Jacket_S,
    Kirin_Cape_S,
    Kirin_Jacket_U_0,
    Kirin_Cape_U_0,
    Kirin_Jacket_1,
    Kirin_Cape_1,
    Kirin_Jacket_U_1,
    Kirin_Cape_U_1,
    Kushala_Cista_0,
    Kushala_Vise_0,
    EX_Kushala_Cista,
    EX_Kushala_Vise,
    Kushala_Cista_1,
    Kushala_Vise_1,
    Empress_Mail,
    Empress_Vest,
    Ceanataur_Mail_0,
    Ceanataur_Vest_0,
    Ceanataur_Mail_1,
    Ceanataur_Vest_1,
    Auroros_Torso_0,
    Borealis_Chest_0,
    Genesis_Torso_0,
    Glyph_Chest_0,
    Auroros_Torso_1,
    Borealis_Chest_1,
    Genesis_Torso_1,
    Glyph_Chest_1,
    Lava_Mail,
    Lava_Vest,
    Remobra_Suit,
    Remobra_Wear,
    Remobra_Suit_S,
    Remobra_Wear_S,
    Zamtrios_Mail,
    Zamtrios_Vest,
    Zamtrios_Mail_S,
    Zamtrios_Vest_S,
    Seltas_Mail,
    Seltas_Vest,
    Seltas_Mail_S,
    Seltas_Vest_S,
    Arc_Mail_0,
    Arc_Vest_0,
    Arc_Mail_S,
    Arc_Vest_S,
    Arc_Mail_1,
    Arc_Vest_1,
    Kaiser_Mail,
    Kaiser_Vest,
    Golden_Haori,
    Puppeteer_Suit,
    Divine_Ire_Haori,
    Crusher_Garb,
    Rebellion_Mail_0,
    Riot_Vest_0,
    Rebellion_Mail_1,
    Riot_Vest_1,
    Dragonhide_X_0,
    Dragonskin_X_0,
    Dragonhide,
    Dragonskin,
    Fatalis_Crimsonhide,
    Fatalis_Crimsonskin,
    Ioprey_Body,
    Ioprey_Wear,
    Cephalos_Mail,
    Cephalos_Vest,
    Mizuha_Guards,
    Cham_Camise,
    Hermitaur_Mail_0,
    Hermitaur_Vest_0,
    Hermitaur_Mail_1,
    Hermitaur_Vest_1,
    Vespoid_Mail,
    Vespoid_Vest,
    Qurupeco_Mail,
    Qurupeco_Vest,
    Agnaktor_Mail,
    Agnaktor_Vest,
    Barioth_Mail,
    Barioth_Vest,
    Volvidon_Mail,
    Volvidon_Vest,
    Lagiacrus_Mail_0,
    Lagiacrus_Vest_0,
    Lagiacrus_Mail_1,
    Lagiacrus_Vest_1,
    Helios_Mail,
    Helios_Vest,
    Selene_Mail,
    Selene_Vest,
    Gobul_Mail,
    Gobul_Vest,
    Yamato_Doate,
    Hyuga_Muneate,
    Mutsu_Doate,
    Amagi_Muneate,
    Escadora_Soul_0,
    Escadora_Seele_0,
    Escadora_Soul_1,
    Escadora_Seele_1,
    Blango_Mail,
    Blango_Vest,
    Lobster_Mail,
    Lobster_Vest,
    Ukanlos_Aegis,
    Ukanlos_Plate,
    Indra_Vest,
    Steadfast_Vest,
    Yaksha_Raiment,
    Carnage_Raiment,
    Artian_Mail,
    Artian_Vest,
    Artian_Mail_S_0,
    Artian_Vest_S_0,
    Artian_Mail_S_1,
    Artian_Vest_S_1,
    Dober_Mail,
    Dober_Vest,
    Ingot_Mail_0,
    Ingot_Vest_0,
    Ingot_Mail_1,
    Ingot_Vest_1,
    Aelucanth_Thorax,
    Rhopessa_Thorax,
    Aelucanth_Pleuron,
    Rhopessa_Pleuron,
    Obituary_Thorax,
    Butterfly_Thorax,
    Obituary_Pleuron,
    Butterfly_Pleuron,
    Mosgharl_Ribplate,
    Mosgharl_Ribguard,
    Guild_Bard_Bolero,
    Scholar_s_Blouse,
    Guild_Bard_Vest,
    Scholar_s_Vest,
    Black_Belt_Mail,
    Black_Belt_Vest,
    Guardian_Suit,
    Helper_Suit,
    Guardian_Vest,
    Helper_Vest,
    Shinobi_Sky_Suit,
    Shinobi_Land_Suit,
    Guild_Knight_Suit,
    Maiden_s_Suit,
    Guild_Knight_Vest,
    Maiden_s_Vest,
    Yukumo_Sky_Dogi,
    Yukumo_Land_Dogi,
    High_Metal_Mail,
    High_Metal_Vest,
    Ranger_s_Girdle,
    Archer_s_Girdle,
    Chakra_Necklace,
    Sailor_Suit,
    Sailor_Vest,
    Hawksuit,
    Lecturer_s_Suit,
    Hawkjacket,
    Lecturer_s_Jacket,
    Blue_Star_Suit,
    Blue_Star_Jacket,
    Mail_of_Anat,
    Vest_of_Anat,
    Fan_Club_Jacket,
    Fan_Club_Tracksuit,
    Uniqlo_Bomber,
    Uniqlo_Hoodie,
    Star_Rook_Mail,
    Star_Rook_Vest,
    dummy_chest706,
    dummy_chest718,
    dummy_chest707,
    dummy_chest719,
    Hunter_s_Camo_Suit,
    Hunter_s_Camo_Jacket,
    dummy_chest709,
    dummy_chest721,
    dummy_chest_0,
    dummy_chest_1,
    Rider_Jacket,
    Rider_Leather,
    dummy_chest712,
    dummy_chest724,
    dummy_chest_2,
    dummy_chest_3,
    Hero_s_Clothes,
    Hero_s_Tunic,
    dummy_chest729,
    dummy_chest730,
    dummy_chest731,
    dummy_chest732,
    EX_Rebellion_Mail,
    EX_Riot_Vest,
    EX_Artian_Mail,
    EX_Artian_Vest,
    EX_Gore_Mail,
    EX_Gore_Vest,
    EX_Ingot_Mail,
    EX_Ingot_Vest,
    EX_Kirin_Jacket_U,
    EX_Kirin_Cape_U,
    Storge_Mail_0,
    Storge_Vest_0,
    Storge_Mail_S,
    Storge_Vest_S,
    Storge_Mail_1,
    Storge_Vest_1,
    Hunter_s_Mail_2,
    Hunter_s_Vest_2,
    Alloy_Mail_2,
    Alloy_Vest_2,
    Ludroth_Mail_2,
    Ludroth_Vest_2,
    Rathian_Mail_2,
    Rathian_Vest_2,
    Rath_Heart_Mail_2,
    Rath_Heart_Vest_2,
    Rathalos_Mail_2,
    Rathalos_Vest_2,
    Rath_Soul_Mail_2,
    Rath_Soul_Vest_2,
    Silver_Solmail_2,
    Silver_Solvest_2,
    Esurient_Mail_2,
    Esurient_Vest_2,
    Gloaming_Plate_2,
    Adamance_Plate_2,
    Dayspring_Plate_2,
    Epoch_Plate_2,
    Tigrex_Mail_2,
    Tigrex_Vest_2,
    Tigrex_Mail_U_2,
    Tigrex_Vest_U_2,
    Akantor_Aegis_2,
    Akantor_Plate_2,
    Zinogre_Mail_U_2,
    Zinogre_Vest_U_2,
    Gore_Mail_2,
    Gore_Vest_2,
    Gypceros_Mail_2,
    Gypceros_Vest_2,
    Gypceros_Mail_U_2,
    Gypceros_Vest_U_2,
    Khezu_Mail_2,
    Khezu_Vest_2,
    Khezu_Mail_U_2,
    Khezu_Vest_U_2,
    Kirin_Jacket_2,
    Kirin_Cape_2,
    Kirin_Jacket_U_2,
    Kirin_Cape_U_2,
    Kushala_Cista_2,
    Kushala_Vise_2,
    Ceanataur_Mail_2,
    Ceanataur_Vest_2,
    Auroros_Torso_2,
    Borealis_Chest_2,
    Genesis_Torso_2,
    Glyph_Chest_2,
    Arc_Mail_2,
    Arc_Vest_2,
    Rebellion_Mail_2,
    Riot_Vest_2,
    Dragonhide_X_1,
    Dragonskin_X_1,
    Hermitaur_Mail_2,
    Hermitaur_Vest_2,
    Lagiacrus_Mail_2,
    Lagiacrus_Vest_2,
    Escadora_Soul_2,
    Escadora_Seele_2,
    Artian_Mail_S_2,
    Artian_Vest_S_2,
    Ingot_Mail_2,
    Ingot_Vest_2,
    Storge_Mail_2,
    Storge_Vest_2,
    Velociprey_Mail_X,
    Velociprey_Vest_X,
    Ioprey_Mail_X,
    Ioprey_Vest_X,
    Kecha_Mail_X,
    Kecha_Vest_X,
    Kecha_Mail_Z,
    Kecha_Vest_Z,
    Tetsucabra_Mail_X,
    Tetsucabra_Vest_X,
    Tetsucabra_Mail_Z,
    Tetsucabra_Vest_Z,
    Nerscylla_Mail_X,
    Nerscylla_Vest_X,
    Nerscylla_Mail_Z,
    Nerscylla_Vest_Z,
    Zamtrios_Mail_X,
    Zamtrios_Vest_X,
    Zamtrios_Mail_Z,
    Zamtrios_Vest_Z,
    Najarala_Mail_X,
    Najarala_Vest_X,
    Najarala_Mail_Z,
    Najarala_Vest_Z,
    Seltas_Mail_X,
    Seltas_Vest_X,
    Seltas_Mail_Z,
    Seltas_Vest_Z,
    Gore_Mail_X,
    Gore_Vest_X,
    Gore_Armor,
    Gore_Pizane,
    Arc_Mail_X,
    Storge_Mail_X,
    Arc_Vest_X,
    Storge_Vest_X,
    Arc_Armor,
    Storge_Armor,
    Arc_Pizane,
    Storge_Pizane,
    Gogma_Mail,
    Gogma_Vest,
    Gypceros_Mail_X,
    Gypceros_Vest_X,
    Gypceros_Armor,
    Gypceros_Pizane,
    Gypceros_Mail_Z,
    Gypceros_Vest_Z,
    Gypceros_Armor_U,
    Gypceros_Pizane_U,
    Lagombi_Mail_X,
    Lagombi_Vest_X,
    Conga_Mail_X,
    Conga_Vest_X,
    Conga_Mail_Z,
    Conga_Vest_Z,
    Khezu_Mail_X,
    Khezu_Vest_X,
    Khezu_Armor,
    Khezu_Pizane,
    Khezu_Mail_Z,
    Khezu_Vest_Z,
    Khezu_Armor_U,
    Khezu_Pizane_U,
    Rathian_Mail_X,
    Rathian_Vest_X,
    Rathian_Armor,
    Rathian_Pizane,
    Rath_Heart_Mail_Z,
    Rath_Heart_Vest_Z,
    Rath_Heart_Armor,
    Rath_Heart_Pizane,
    Golden_Lunemail_Z,
    Golden_Lunevest_Z,
    Rathalos_Mail_X,
    Rathalos_Vest_X,
    Rathalos_Armor,
    Rathalos_Pizane,
    Rath_Soul_Mail_Z,
    Rath_Soul_Vest_Z,
    Rath_Soul_Armor,
    Rath_Soul_Pizane,
    Silver_Solmail_Z,
    Silver_Solvest_Z,
    Silver_Solarmor,
    Silver_Solpizane,
    Zinogre_Mail_X,
    Zinogre_Vest_X,
    Zinogre_Mail_Z,
    Zinogre_Vest_Z,
    Zinogre_Armor_U,
    Zinogre_Pizane_U,
    Tigrex_Mail_X,
    Tigrex_Vest_X,
    Tigrex_Armor,
    Tigrex_Pizane,
    Tigrex_Mail_Z,
    Tigrex_Vest_Z,
    Tigrex_Armor_U,
    Tigrex_Pizane_U,
    Excello_Mail_Z,
    Excello_Vest_Z,
    Gravios_Mail_X,
    Gravios_Vest_X,
    Gravios_Mail_Z,
    Gravios_Vest_Z,
    Brachydios_Mail_X,
    Brachydios_Vest_X,
    Brachydium_Mail,
    Brachydium_Vest,
    Grand_Gloaming_Plate,
    Grand_Adamance_Plate,
    Grand_Dayspring_Plate,
    Grand_Epoch_Plate,
    Gloaming_Redplate,
    Adamance_Redplate,
    Dayspring_Redplate,
    Epoch_Redplate,
    Vangis_Mail_X,
    Vangis_Vest_X,
    Esurient_Mail_Z,
    Esurient_Vest_Z,
    Esurient_Armor,
    Esurient_Pizane,
    Kaiser_Mail_X,
    Kaiser_Vest_X,
    Akantor_Aegis_X,
    Akantor_Plate_X,
    Akantor_Armor,
    Akantor_Pizane,
    EX_Escadora_Soul,
    EX_Escadora_Seele,
    Ukanlos_Aegis_X,
    Ukanlos_Plate_X,
    Kushala_Cista_X,
    Kushala_Vise_X,
    Kushala_Armor,
    Kushala_Pizane,
    Kujula_Cista,
    Kujula_Vise,
    Grand_God_s_Peer_Robe,
    Grand_Hermit_Robe,
    Grand_Divine_Ire_Robe,
    Grand_Crusher_Robe,
    Rebellion_Mail_X,
    Riot_Vest_X,
    Rebellion_Armor,
    Riot_Pizane,
    Rebellion_Mail_Z,
    Riot_Vest_Z,
    Cephalos_Mail_X,
    Cephalos_Vest_X,
    Hermitaur_Mail_X,
    Hermitaur_Vest_X,
    Hermitaur_Armor,
    Hermitaur_Pizane,
    Hermitaur_Mail_Z,
    Hermitaur_Vest_Z,
    Mono_Mail_S,
    Mono_Vest_S,
    Mono_Mail_X,
    Mono_Vest_X,
    Mono_Mail,
    Mono_Vest,
    Mono_Armor,
    Mono_Pizane,
    Monodevil_Mail_0,
    Monodevil_Vest_0,
    Monodevil_Mail_1,
    Monodevil_Vest_1,
    Monodevil_Armor,
    Monodevil_Pizane,
    Diablos_Mail_X,
    Diablos_Vest_X,
    Diablos_Mail_1,
    Diablos_Vest_1,
    Diablos_Armor,
    Diablos_Pizane,
    Diablos_Mail_Z,
    Diablos_Vest_Z,
    Dragonhide_X_2,
    Dragonskin_X_2,
    Dragonarmor_X,
    Dragonpizane_X,
    Fatalis_Crimsonhide_Z,
    Fatalis_Crimsonskin_Z,
    Fatalis_Crimsonarmor_Z,
    Fatalis_Crimsonpizane_Z,
    Wrothhide,
    Wrothskin,
    White_Fatalis_Hide,
    White_Fatalis_Skin,
    Grand_Mizuha_Guards,
    Grand_Cham_Camise,
    Regios_Mail_S,
    Regios_Vest_S,
    Regios_Mail_X,
    Regios_Vest_X,
    Chaos_Mail,
    Nephilim_Mail,
    Chaos_Vest,
    Nephilim_Vest,
    Basarios_Mail_X,
    Basarios_Vest_X,
    Basarios_Mail_Z,
    Basarios_Vest_Z,
    Kut_Ku_Mail_X,
    Kut_Ku_Vest_X,
    Kut_Ku_Mail_Z,
    Kut_Ku_Vest_Z,
    Garuga_Mail_X,
    Garuga_Vest_X,
    Kirin_Jacket_X,
    Kirin_Cape_X,
    Kirin_Armor,
    Kirin_Pizane,
    Kirin_Jacket_Z,
    Kirin_Cape_Z,
    Kirin_Armor_U,
    Kirin_Pizane_U,
    Bnahabra_Suit_X,
    Bnahabra_Vest_X,
    Slagtoth_Cloak_X,
    Slagtoth_Wrap_X,
    Rhenoplos_Mail_X,
    Rhenoplos_Vest_X,
    Hunter_s_Armor,
    Hunter_s_Pizane,
    Alloy_Armor,
    Alloy_Pizane,
    Artian_Mail_X,
    Artian_Vest_X,
    Arc_Armor_S,
    Arc_Pizane_S,
    Ingot_Armor,
    Ingot_Pizane,
    Guardian_Suit_X,
    Helper_Vest_X,
    Guardian_Vest_X,
    Healer_Vest_X,
    Guardian_Suit_Z,
    Helper_Vest_Z,
    Guardian_Vest_Z,
    Healer_Vest_Z,
    G__Knight_Suit_X,
    Maiden_s_Suit_X,
    G__Knight_Vest_X,
    Exclusive_Vest_X,
    Ace_Mail,
    Sororal_Mail,
    Ace_Vest,
    Sororal_Vest,
    Ceanataur_Armor,
    Ceanataur_Pizane,
    Lagiacrus_Armor,
    Lagiacrus_Pizane,
    Escadora_Armor,
    Escadora_Pizane,
    Auroros_Kermes_Plate,
    Borealis_Woad_Plate,
    Genesis_Kermes_Plate,
    Glyph_Woad_Plate,
    Ludroth_Armor,
    Ludroth_Pizane,
    Hornet_Mail_0,
    Hornet_Vest_0,
    Hornet_Armor,
    Hornet_Pizane,
    Wroggi_Mail_0,
    Wroggi_Vest_0,
    Wroggi_Armor,
    Wroggi_Pizane,
    Gigginox_Mail_0,
    Gigginox_Vest_0,
    Gigginox_Armor,
    Gigginox_Pizane,
    Tempest_Robe_0,
    Welkin_Robe_0,
    Tempest_Vesture,
    Welkin_Vesture,
    Death_Stench_Muscle_0,
    Death_Stench_Heart_0,
    Death_Stench_Armor,
    Death_Stench_Pizane,
    Damascus_Mail_0,
    Damascus_Vest_0,
    Damascus_Armor,
    Damascus_Pizane,
    Lagiacrus_Mail_X,
    Lagiacrus_Vest_X,
    Nargacuga_Mail_X,
    Nargacuga_Vest_X,
    Empress_Mail_X,
    Empress_Vest_X,
    Helios_Mail_X,
    Selene_Mail_X,
    Helios_Vest_X,
    Selene_Vest_X,
    Agnaktor_Mail_X,
    Agnaktor_Vest_X,
    Qurupeco_Mail_X,
    Qurupeco_Vest_X,
    Gobul_Mail_X,
    Gobul_Vest_X,
    Barioth_Mail_X,
    Barioth_Vest_X,
    Barroth_Mail_X,
    Barroth_Vest_X,
    Nibelsnarf_Mail_X,
    Nibelsnarf_Vest_X,
    Duramboros_Mail_X,
    Duramboros_Vest_X,
    Lava_Mail_X,
    Lava_Vest_X,
    Grand_Yamato_Doate,
    Grand_Hyuga_Muneate,
    Grand_Mutsu_Doate,
    Grand_Amagi_Muneate,
    Grand_Yaksha_Raiment,
    Grand_Carnage_Raiment,
    Miralis_Breastplate,
    Miralis_Chestguard,
    Plesioth_Mail_Z,
    Plesioth_Vest_Z,
    Kita_Star_Jacket,
    Umi_Ocean_Jacket,
    Patissier_s_Suit,
    Patissier_s_Vest,
    High_Metal_Mail_S,
    High_Metal_Vest_S,
    Aelucanth_Thorax_X,
    Rhopessa_Thorax_X,
    Aelucanth_Pleuron_X,
    Rhopessa_Pleuron_X,
    Obituary_Thorax_X,
    Butterfly_Thorax_X,
    Obituary_Pleuron_X,
    Butterfly_Pleuron_X,
    EX_Auroros_Torso,
    EX_Borealis_Chest,
    EX_Genesis_Torso,
    EX_Glyph_Chest,
    Tempest_Robe_1,
    Welkin_Robe_1,
    GX_Escadora_Armor,
    GX_Escadora_Pizane,
    GX_Dragonarmor_X,
    GX_Dragonpizane_X,
    Star_Knight_Mail,
    Star_Knight_Vest,
    Mail_of_Rage,
    Vest_of_Rage,
    Varia_Suit_Armor_0,
    Zero_Suit_Body_0,
    Varia_Suit_Barrier_0,
    Zero_Suit_Wear_0,
    Varia_Suit_Armor_1,
    Zero_Suit_Body_1,
    Varia_Suit_Barrier_1,
    Zero_Suit_Wear_1,
    Fan_Club_Goldsuit,
    Fan_Club_Silversuit,
    Hawksuit_X,
    Lecturer_s_Suit_X,
    Hawkjacket_X,
    Lecturer_s_Jacket_X,
    GX_Hunter_s_Armor,
    GX_Hunter_s_Pizane,
    GX_Esurient_Armor,
    GX_Esurient_Pizane,
    GX_Tempest_Vesture,
    GX_Welkin_Vesture,
    GX_Fatalis_Crimsonarmor,
    GX_Fatalis_Crimsonpizane,
    Hunter_s_Mail_3,
    Hunter_s_Vest_3,
    Hunter_s_Mail_4,
    Hunter_s_Vest_4,
    Ludroth_Mail_3,
    Ludroth_Vest_3,
    Ludroth_Mail_4,
    Ludroth_Vest_4,
    Alloy_Mail_3,
    Alloy_Vest_3,
    Alloy_Mail_4,
    Alloy_Vest_4,
    Gypceros_Mail_3,
    Gypceros_Vest_3,
    Gypceros_Mail_4,
    Gypceros_Vest_4,
    Khezu_Mail_3,
    Khezu_Vest_3,
    Khezu_Mail_4,
    Khezu_Vest_4,
    Ingot_Mail_3,
    Ingot_Vest_3,
    Ingot_Mail_4,
    Ingot_Vest_4,
    Rathian_Mail_3,
    Rathian_Vest_3,
    Lagiacrus_Mail_3,
    Lagiacrus_Vest_3,
    Rathalos_Mail_3,
    Rathalos_Vest_3,
    Gypceros_Mail_U_3,
    Gypceros_Vest_U_3,
    Khezu_Mail_U_3,
    Khezu_Vest_U_3,
    Tigrex_Mail_3,
    Tigrex_Vest_3,
    Kirin_Jacket_3,
    Kirin_Cape_3,
    Kirin_Jacket_4,
    Kirin_Cape_4,
    Artian_Mail_S_3,
    Artian_Vest_S_3,
    Ceanataur_Mail_3,
    Ceanataur_Vest_3,
    Ceanataur_Mail_4,
    Ceanataur_Vest_4,
    Gloaming_Plate_3,
    Dayspring_Plate_3,
    Adamance_Plate_3,
    Epoch_Plate_3,
    Zinogre_Mail_U_3,
    Zinogre_Vest_U_3,
    Tigrex_Mail_U_3,
    Tigrex_Vest_U_3,
    Gore_Mail_3,
    Gore_Vest_3,
    Auroros_Torso_3,
    Genesis_Torso_3,
    Borealis_Chest_3,
    Glyph_Chest_3,
    Kirin_Jacket_U_3,
    Kirin_Cape_U_3,
    Kirin_Jacket_U_4,
    Kirin_Cape_U_4,
    Esurient_Mail_3,
    Esurient_Vest_3,
    Monoblos_Mail,
    Monoblos_Vest,
    Hornet_Mail_1,
    Hornet_Vest_1,
    Wroggi_Mail_1,
    Wroggi_Vest_1,
    Monodevil_Mail_2,
    Monodevil_Vest_2,
    Diablos_Mail_2,
    Diablos_Vest_2,
    Gigginox_Mail_1,
    Gigginox_Vest_1,
    Death_Stench_Muscle_1,
    Death_Stench_Heart_1,
    Damascus_Mail_1,
    Damascus_Vest_1,
    dummy_chest_4,
    dummy_chest_5
};
}
