#pragma once

namespace MH4U {
constexpr const char* Head_s[] = {
    "(None)",
    "Derring Headgear",
    "Derring Helm S",
    "Derring Cap S",
    "Leather Headgear",
    "Leather Helm S",
    "Leather Cap S",
    "Chainmail Headgear",
    "Chainmail Helm S",
    "Chainmail Cap S",
    "Hunter's Helm",
    "Hunter's Cap",
    "Hunter's Helm S",
    "Hunter's Cap S",
    "Hunter's Helm",
    "Hunter's Cap",
    "Bone Helm",
    "Bone Cap",
    "Bone Helm S",
    "Bone Cap S",
    "Alloy Helm",
    "Alloy Cap",
    "Alloy Helm S",
    "Alloy Cap S",
    "Alloy Helm",
    "Alloy Cap",
    "Jaggi Helm",
    "Jaggi Cap",
    "Jaggi Helm S",
    "Jaggi Cap S",
    "Ludroth Helm",
    "Ludroth Cap",
    "Ludroth Helm",
    "Ludroth Cap",
    "Rhenoplos Helm",
    "Rhenoplos Cap",
    "Rhenoplos Helm S",
    "Rhenoplos Cap S",
    "Bnahabra Hat",
    "Bnahabra Headpiece",
    "Bnahabra Hat S",
    "Bnahabra Headpiece S",
    "Barroth Helm",
    "Barroth Cap",
    "Rathian Helm",
    "Rathian Cap",
    "Rathian Helm S",
    "Rathian Cap S",
    "Rath Heart Helm",
    "Rath Heart Cap",
    "Golden Lunehelm",
    "Golden Lunecap",
    "Rathian Helm",
    "Rathian Cap",
    "Rath Heart Helm",
    "Rath Heart Cap",
    "EX Rathian Helm",
    "EX Rathian Cap",
    "Rathalos Helm",
    "Rathalos Cap",
    "Rathalos Helm S",
    "Rathalos Cap S",
    "Rath Soul Helm",
    "Rath Soul Cap",
    "Silver Solhelm",
    "Silver Solcap",
    "Rathalos Helm",
    "Rathalos Cap",
    "Rath Soul Helm",
    "Rath Soul Cap",
    "Silver Solhelm",
    "Silver Solcap",
    "EX Rathalos Helm",
    "EX Rathalos Cap",
    "Diablos Helm",
    "Diablos Cap",
    "Uragaan Helm",
    "Uragaan Cap",
    "Vangis Helm",
    "Vangis Cap",
    "Esurient Helm",
    "Esurient Cap",
    "Esurient Helm",
    "Esurient Cap",
    "Gloaming Helm",
    "Adamance Helm",
    "Dayspring Kasa",
    "Epoch Helm",
    "Gloaming Archhelm",
    "Adamance Archhelm",
    "Dayspring Archkasa",
    "Epoch Archhelm",
    "Gloaming Helm",
    "Adamance Helm",
    "Dayspring Kasa",
    "Epoch Helm",
    "Plesioth Helm",
    "Plesioth Cap",
    "Nibelsnarf Helm",
    "Nibelsnarf Cap",
    "Duramboros Helm",
    "Duramboros Cap",
    "Arzuros Helm",
    "Arzuros Cap",
    "Lagombi Helm",
    "Lagombi Cap",
    "Lagombi Helm S",
    "Lagombi Cap S",
    "Slagtoth Hood",
    "Slagtoth Cowl",
    "Slagtoth Hood S",
    "Slagtoth Cowl S",
    "Nargacuga Helm",
    "Nargacuga Cap",
    "Tigrex Helm",
    "Tigrex Cap",
    "Tigrex Helm S",
    "Tigrex Cap S",
    "Tigrex Helm U",
    "Tigrex Cap U",
    "Excello Helm",
    "Excello Cap",
    "EX Tigrex Helm",
    "EX Tigrex Cap",
    "Tigrex Helm",
    "Tigrex Cap",
    "Tigrex Helm U",
    "Tigrex Cap U",
    "Brachydios Helm",
    "Brachydios Cap",
    "Brachydios Helm S",
    "Brachydios Cap S",
    "Akantor Mask",
    "Akantor Fangs",
    "Akantor Mask",
    "Akantor Fangs",
    "Zinogre Helm",
    "Zinogre Cap",
    "Zinogre Helm S",
    "Zinogre Cap S",
    "Zinogre Helm U",
    "Zinogre Cap U",
    "Zinogre Helm U",
    "Zinogre Cap U",
    "EX Kaiser Crown",
    "EX Kaiser Mask",
    "Kecha Helm",
    "Kecha Cap",
    "Kecha Helm S",
    "Kecha Cap S",
    "Gore Helm",
    "Gore Cap",
    "Gore Helm S",
    "Gore Cap S",
    "Gore Helm",
    "Gore Cap",
    "Tetsucabra Helm",
    "Tetsucabra Cap",
    "Tetsucabra Helm S",
    "Tetsucabra Cap S",
    "Nerscylla Helm",
    "Nerscylla Cap",
    "Nerscylla Helm S",
    "Nerscylla Cap S",
    "Najarala Helm",
    "Najarala Cap",
    "Najarala Helm S",
    "Najarala Cap S",
    "Garuga Helm",
    "Garuga Cap",
    "Garuga Helm S",
    "Garuga Cap S",
    "Basarios Helm",
    "Basarios Cap",
    "Basarios Helm S",
    "Basarios Cap S",
    "Basarios Helm U",
    "Basarios Cap U",
    "Battle Helm",
    "Battle Cap",
    "Velociprey Helm",
    "Velociprey Cap",
    "Velociprey Helm S",
    "Velociprey Cap S",
    "Genprey Helm",
    "Genprey Cap",
    "Genprey Helm S",
    "Genprey Cap S",
    "Ioprey Helm",
    "Ioprey Cap",
    "Ioprey Helm S",
    "Ioprey Cap S",
    "Kut-Ku Helm",
    "Kut-Ku Cap",
    "Kut-Ku Helm S",
    "Kut-Ku Cap S",
    "Kut-Ku Helm U",
    "Kut-Ku Cap U",
    "Gypceros Helm",
    "Gypceros Cap",
    "Gypceros Helm S",
    "Gypceros Cap S",
    "Gypceros Helm U",
    "Gypceros Cap U",
    "Gypceros Helm",
    "Gypceros Cap",
    "Gypceros Helm U",
    "Gypceros Cap U",
    "Conga Helm",
    "Conga Cap",
    "Conga Helm S",
    "Conga Cap S",
    "Conga Helm U",
    "Conga Cap U",
    "Gravios Helm",
    "Gravios Cap",
    "Gravios Helm S",
    "Gravios Cap S",
    "Gravios Helm U",
    "Gravios Cap U",
    "Khezu Helm",
    "Khezu Cap",
    "Khezu Helm S",
    "Khezu Cap S",
    "Khezu Helm U",
    "Khezu Cap U",
    "Khezu Helm",
    "Khezu Cap",
    "Khezu Helm U",
    "Khezu Cap U",
    "Kirin Horn",
    "Kirin Crest",
    "Kirin Horn S",
    "Kirin Crest S",
    "Kirin Horn U",
    "Kirin Crest U",
    "Kirin Horn",
    "Kirin Crest",
    "Kirin Horn U",
    "Kirin Crest U",
    "Kushala Glare",
    "Kushala Snarl",
    "EX Kushala Glare",
    "EX Kushala Snarl",
    "Kushala Glare",
    "Kushala Snarl",
    "Empress Crown",
    "Empress Mask",
    "Ceanataur Helm",
    "Ceanataur Cap",
    "Ceanataur Helm",
    "Ceanataur Cap",
    "Auroros Helm",
    "Borealis Crown",
    "Genesis Headpiece",
    "Glyph Crown",
    "Auroros Helm",
    "Borealis Crown",
    "Genesis Headpiece",
    "Glyph Crown",
    "Lava Helm",
    "Lava Cap",
    "Remobra Headgear",
    "Remobra Mask",
    "Remobra Headgear S",
    "Remobra Mask S",
    "Zamtrios Helm",
    "Zamtrios Cap",
    "Zamtrios Helm S",
    "Zamtrios Cap S",
    "Seltas Helm",
    "Seltas Cap",
    "Seltas Helm S",
    "Seltas Cap S",
    "Arc Helm",
    "Arc Cap",
    "Arc Helm S",
    "Arc Cap S",
    "Arc Helm",
    "Arc Cap",
    "Kaiser Crown",
    "Kaiser Mask",
    "Golden Headdress",
    "Puppeteer Mask",
    "Divine Ire Headdress",
    "Crusher Mask",
    "Rebellion Helm",
    "Riot Cap",
    "Rebellion Helm",
    "Riot Cap",
    "Dragonhead X",
    "Dragonface X",
    "Dragonhead",
    "Dragonface",
    "Fatalis Crimsonhead",
    "Fatalis Crimsonface",
    "Ioprey Head",
    "Ioprey Face",
    "Cephalos Helm",
    "Cephalos Cap",
    "Mizuha Cap",
    "Cham Hat",
    "Hermitaur Helm",
    "Hermitaur Cap",
    "Hermitaur Helm",
    "Hermitaur Cap",
    "Vespoid Helm",
    "Vespoid Cap",
    "Qurupeco Helm",
    "Qurupeco Cap",
    "Agnaktor Helm",
    "Agnaktor Cap",
    "Barioth Helm",
    "Barioth Cap",
    "Volvidon Helm",
    "Volvidon Cap",
    "Lagiacrus Helm",
    "Lagiacrus Cap",
    "Lagiacrus Helm",
    "Lagiacrus Cap",
    "Helios Helm",
    "Helios Cap",
    "Selene Helm",
    "Selene Cap",
    "Gobul Helm",
    "Gobul Cap",
    "Yamato Kabuto",
    "Hyuga Hachigane",
    "Mutsu Eboshi",
    "Amagi Hachigane",
    "Escadora Wisdom",
    "Escadora Sagesse",
    "Escadora Wisdom",
    "Escadora Sagesse",
    "Blango Helm",
    "Blango Cap",
    "Lobster Helm",
    "Lobster Cap",
    "Ukanlos Mask",
    "Ukanlos Fangs",
    "Indra Helm",
    "Steadfast Helm",
    "Yaksha Mask",
    "Carnage Helm",
    "Artian Helm S",
    "Artian Cap S",
    "Dober Helm",
    "Dober Cap",
    "Ingot Helm",
    "Ingot Cap",
    "Ingot Helm",
    "Ingot Cap",
    "Aelucanth Vertex",
    "Rhopessa Vertex",
    "Aelucanth Clypeus",
    "Rhopessa Clypeus",
    "Obituary Vertex",
    "Butterfly Vertex",
    "Obituary Clypeus",
    "Butterfly Clypeus",
    "Mosgharl Vizor",
    "Mosgharl Brim",
    "Guild Bard Lobos",
    "Scholar's Beret",
    "Guild Bard Hat",
    "Scholar's Cap",
    "Skull Visage",
    "Skull Mask",
    "Shadow Shades",
    "Jaggi Mask",
    "Gargwa Mask",
    "Black Belt Helm",
    "Black Belt Cap",
    "Guardian Helm",
    "Helper Hood",
    "Guardian Mask",
    "Helper Cap",
    "Shinobi Sky Mask",
    "Shinobi Land Mask",
    "Guild Knight Feather",
    "Maiden's Hat",
    "Guild Knight Mask",
    "Maiden's Cap",
    "Yukumo Sky Kasa",
    "Yukumo Land Kasa",
    "High Metal Helm",
    "High Metal Cap",
    "Ranger's Headgear",
    "Archer's Turban",
    "Dragonlord's Gaze",
    "Chakra Earring",
    "Sailor Hat",
    "Sailor Cap",
    "Hawkhat",
    "Lecturer's Hood",
    "Hawkcap",
    "Lecturer's Cap",
    "Friendship Feather",
    "Victory Feather",
    "Champion Feather",
    "Felyne Hairband",
    "Cunning Specs",
    "Blue Star Lobos",
    "Blue Star Hat",
    "dummy701",
    "Helm of Anat",
    "Cap of Anat",
    "Uniqlo Hood",
    "Uniqlo Cap",
    "Star Rook Helm",
    "Star Rook Cap",
    "dummy706",
    "dummy718",
    "dummy707",
    "dummy719",
    "Artian Helm S",
    "Artian Cap S",
    "Overlord Feather",
    "DUMMY",
    "Hero's Hat",
    "DUMMY",
    "Hero's Cap",
    "dummy729",
    "dummy730",
    "EX Rebellion Helm",
    "EX Riot Cap",
    "EX Gore Helm",
    "EX Gore Cap",
    "EX Ingot Helm",
    "EX Ingot Cap",
    "EX Kirin Horn U",
    "EX Kirin Crest U",
    "EX Artian Helm",
    "EX Artian Cap",
    "Storge Helm",
    "Storge Cap",
    "Storge Helm S",
    "Storge Cap S",
    "Storge Helm",
    "Storge Cap",
    "Hunter's Helm",
    "Hunter's Cap",
    "Alloy Helm",
    "Alloy Cap",
    "Ludroth Helm",
    "Ludroth Cap",
    "Rathian Helm",
    "Rathian Cap",
    "Rath Heart Helm",
    "Rath Heart Cap",
    "Rathalos Helm",
    "Rathalos Cap",
    "Rath Soul Helm",
    "Rath Soul Cap",
    "Silver Solhelm",
    "Silver Solcap",
    "Esurient Helm",
    "Esurient Cap",
    "Gloaming Helm",
    "Adamance Helm",
    "Dayspring Kasa",
    "Epoch Helm",
    "Tigrex Helm",
    "Tigrex Cap",
    "Tigrex Helm U",
    "Tigrex Cap U",
    "Akantor Mask",
    "Akantor Fangs",
    "Zinogre Helm U",
    "Zinogre Cap U",
    "Gore Helm",
    "Gore Cap",
    "Gypceros Helm",
    "Gypceros Cap",
    "Gypceros Helm U",
    "Gypceros Cap U",
    "Khezu Helm",
    "Khezu Cap",
    "Khezu Helm U",
    "Khezu Cap U",
    "Kirin Horn",
    "Kirin Crest",
    "Kirin Horn U",
    "Kirin Crest U",
    "Kushala Glare",
    "Kushala Snarl",
    "Ceanataur Helm",
    "Ceanataur Cap",
    "Auroros Helm",
    "Borealis Crown",
    "Genesis Headpiece",
    "Glyph Crown",
    "Arc Helm",
    "Arc Cap",
    "Rebellion Helm",
    "Riot Cap",
    "Dragonhead X",
    "Dragonface X",
    "Hermitaur Helm",
    "Hermitaur Cap",
    "Lagiacrus Helm",
    "Lagiacrus Cap",
    "Escadora Wisdom",
    "Escadora Sagesse",
    "Ingot Helm",
    "Ingot Cap",
    "Artian Helm S",
    "Artian Cap S",
    "Storge Helm",
    "Storge Cap",
    "Velociprey Helm X",
    "Velociprey Cap X",
    "Ioprey Helm X",
    "Ioprey Cap X",
    "Kecha Helm X",
    "Kecha Cap X",
    "Kecha Helm Z",
    "Kecha Cap Z",
    "Tetsucabra Helm X",
    "Tetsucabra Cap X",
    "Tetsucabra Helm Z",
    "Tetsucabra Cap Z",
    "Nerscylla Helm X",
    "Nerscylla Cap X",
    "Nerscylla Helm Z",
    "Nerscylla Cap Z",
    "Zamtrios Helm X",
    "Zamtrios Cap X",
    "Zamtrios Helm Z",
    "Zamtrios Cap Z",
    "Najarala Helm X",
    "Najarala Cap X",
    "Najarala Helm Z",
    "Najarala Cap Z",
    "Seltas Helm X",
    "Seltas Cap X",
    "Seltas Helm Z",
    "Seltas Cap Z",
    "Gore Helm X",
    "Gore Cap X",
    "Gore Casque",
    "Gore Coif",
    "Arc Helm X",
    "Storge Helm X",
    "Arc Cap X",
    "Storge Cap X",
    "Arc Casque",
    "Storge Casque",
    "Arc Coif",
    "Storge Coif",
    "Gogma Helm",
    "Gogma Cap",
    "Gypceros Helm X",
    "Gypceros Cap X",
    "Gypceros Casque",
    "Gypceros Coif",
    "Gypceros Helm Z",
    "Gypceros Cap Z",
    "Gypceros Casque U",
    "Gypceros Coif U",
    "Lagombi Helm X",
    "Lagombi Cap X",
    "Conga Helm X",
    "Conga Cap X",
    "Conga Helm Z",
    "Conga Cap Z",
    "Khezu Helm X",
    "Khezu Cap X",
    "Khezu Casque",
    "Khezu Coif",
    "Khezu Helm Z",
    "Khezu Cap Z",
    "Khezu Casque U",
    "Khezu Coif U",
    "Rathian Helm X",
    "Rathian Cap X",
    "Rathian Casque",
    "Rathian Coif",
    "Rath Heart Helm Z",
    "Rath Heart Cap Z",
    "Rath Heart Casque",
    "Rath Heart Coif",
    "Golden Lunehelm Z",
    "Golden Lunecap Z",
    "Rathalos Helm X",
    "Rathalos Cap X",
    "Rathalos Casque",
    "Rathalos Coif",
    "Rath Soul Helm Z",
    "Rath Soul Cap Z",
    "Rath Soul Casque",
    "Rath Soul Coif",
    "Silver Solhelm Z",
    "Silver Solcap Z",
    "Silver Solcasque",
    "Silver Solcoif",
    "Zinogre Helm X",
    "Zinogre Cap X",
    "Zinogre Helm Z",
    "Zinogre Cap Z",
    "Zinogre Casque U",
    "Zinogre Coif U",
    "Tigrex Helm X",
    "Tigrex Cap X",
    "Tigrex Casque",
    "Tigrex Coif",
    "Tigrex Helm Z",
    "Tigrex Cap Z",
    "Tigrex Casque U",
    "Tigrex Coif U",
    "Excello Helm Z",
    "Excello Cap Z",
    "Gravios Helm X",
    "Gravios Cap X",
    "Gravios Helm Z",
    "Gravios Cap Z",
    "Brachydios Helm X",
    "Brachydios Cap X",
    "Brachydium Helm",
    "Brachydium Cap",
    "Grand Gloaming Helm",
    "Grand Adamance Helm",
    "Grand Dayspring Helm",
    "Grand Epoch Helm",
    "Gloaming Redhelm",
    "Adamance Redhelm",
    "Dayspring Redhelm",
    "Epoch Redhelm",
    "Vangis Helm X",
    "Vangis Cap X",
    "Esurient Helm Z",
    "Esurient Cap Z",
    "Esurient Casque",
    "Esurient Coif",
    "Kaiser Crown X",
    "Kaiser Mask X",
    "Akantor Mask X",
    "Akantor Fangs X",
    "Akantor Casque",
    "Akantor Coif",
    "EX Escadora Wisdom",
    "EX Escadora Sagesse",
    "Ukanlos Mask X",
    "Ukanlos Fangs X",
    "Kushala Glare X",
    "Kushala Snarl X",
    "Kushala Casque",
    "Kushala Coif",
    "Kujula Glare",
    "Kujula Snarl",
    "Grand God's Peer Mask",
    "Grand Hermit Mask",
    "Grand Divine Ire Mask",
    "Grand Crusher Mask",
    "Rebellion Helm X",
    "Riot Cap X",
    "Rebellion Casque",
    "Riot Coif",
    "Rebellion Helm Z",
    "Riot Cap Z",
    "Cephalos Helm X",
    "Cephalos Cap X",
    "Hermitaur Helm X",
    "Hermitaur Cap X",
    "Hermitaur Casque",
    "Hermitaur Coif",
    "Hermitaur Helm Z",
    "Hermitaur Cap Z",
    "Mono Helm S",
    "Mono Cap S",
    "Mono Helm X",
    "Mono Cap X",
    "Mono Helm",
    "Mono Cap",
    "Mono Casque",
    "Mono Coif",
    "Monodevil Helm",
    "Monodevil Cap",
    "Monodevil Helm",
    "Monodevil Cap",
    "Monodevil Casque",
    "Monodevil Coif",
    "Diablos Helm X",
    "Diablos Cap X",
    "Diablos Helm",
    "Diablos Cap",
    "Diablos Casque",
    "Diablos Coif",
    "Diablos Helm Z",
    "Diablos Cap Z",
    "Dragonhead X",
    "Dragonface X",
    "Dragoncasque X",
    "Dragoncoif X",
    "Fatalis Crimsonhead Z",
    "Fatalis Crimsonface Z",
    "Fatalis Crimsonhelm Z",
    "Fatalis Crimsoncoif Z",
    "Wrothhead",
    "Wrothface",
    "White Fatalis Head",
    "White Fatalis Face",
    "Grand Mizuha Mask",
    "Grand Cham Hat",
    "Regios Helm S",
    "Regios Cap S",
    "Regios Helm X",
    "Regios Cap X",
    "Chaos Helm",
    "Nephilim Helm",
    "Chaos Cap",
    "Nephilim Cap",
    "Basarios Helm X",
    "Basarios Cap X",
    "Basarios Helm Z",
    "Basarios Cap Z",
    "Kut-Ku Helm X",
    "Kut-Ku Cap X",
    "Kut-Ku Helm Z",
    "Kut-Ku Cap Z",
    "Garuga Helm X",
    "Garuga Cap X",
    "Kirin Horn X",
    "Kirin Crest X",
    "Kirin Casque",
    "Kirin Coif",
    "Kirin Horn Z",
    "Kirin Crest Z",
    "Kirin Casque U",
    "Kirin Coif U",
    "Bnahabra Hat X",
    "Bnahabra Headpiece X",
    "Slagtoth Hood X",
    "Slagtoth Cowl X",
    "Rhenoplos Helm X",
    "Rhenoplos Cap X",
    "Hunter's Casque",
    "Hunter's Coif",
    "Alloy Casque",
    "Alloy Coif",
    "Artian Helm X",
    "Artian Cap X",
    "Arc Casque S",
    "Arc Coif S",
    "Ingot Casque",
    "Ingot Coif",
    "Guardian Helm X",
    "Helper Hood X",
    "Guardian Mask X",
    "Healer Glasses X",
    "Guardian Helm Z",
    "Helper Hood Z",
    "Guardian Mask Z",
    "Healer Beret Z",
    "G. Knight Feather X",
    "Maiden's Hat X",
    "G. Knight Mask X",
    "Exclusive Glasses X",
    "Ace Headgear",
    "Sororal Headgear",
    "Ace Mask",
    "Sororal Mask",
    "Ceanataur Casque",
    "Ceanataur Coif",
    "Lagiacrus Casque",
    "Lagiacrus Coif",
    "Escadora Casque",
    "Escadora Coif",
    "Auroros Kermes Helm",
    "Borealis Bellflower",
    "Genesis Kermes Helm",
    "Glyph Bellflower",
    "Ludroth Casque",
    "Ludroth Coif",
    "Hornet Helm",
    "Hornet Cap",
    "Hornet Casque",
    "Hornet Coif",
    "Wroggi Hat",
    "Wroggi Cap",
    "Wroggi Casque",
    "Wroggi Coif",
    "Gigginox Helm",
    "Gigginox Cap",
    "Gigginox Casque",
    "Gigginox Coif",
    "Tempest Crown",
    "Welkin Crown",
    "Tempest Diadem",
    "Welkin Diadem",
    "Death Stench Brain",
    "Death Stench Soul",
    "Death Stench Casque",
    "Death Stench Coif",
    "Damascus Helm",
    "Damascus Cap",
    "Damascus Casque",
    "Damascus Coif",
    "Lagiacrus Helm X",
    "Lagiacrus Cap X",
    "Nargacuga Helm X",
    "Nargacuga Cap X",
    "Empress Crown X",
    "Empress Mask X",
    "Helios Helm X",
    "Selene Helm X",
    "Helios Cap X",
    "Selene Cap X",
    "Agnaktor Helm X",
    "Agnaktor Cap X",
    "Qurupeco Helm X",
    "Qurupeco Cap X",
    "Gobul Helm X",
    "Gobul Cap X",
    "Barioth Helm X",
    "Barioth Cap X",
    "Barroth Helm X",
    "Barroth Cap X",
    "Nibelsnarf Helm X",
    "Nibelsnarf Cap X",
    "Duramboros Helm X",
    "Duramboros Cap X",
    "Lava Helm X",
    "Lava Cap X",
    "Grand Yamato Kabuto",
    "Grand H. Hachigane",
    "Grand Mutsu Jingasa",
    "Grand Amagi Jingasa",
    "Grand Yaksha Mask",
    "Grand Carnage Helm",
    "Miralis Diadem",
    "Miralis Crown",
    "Plesioth Helm Z",
    "Plesioth Cap Z",
    "Kita Star Headdress",
    "Umi Ocean Headdress",
    "Patissier's Toque",
    "Patissier's Cap",
    "High Metal Helm S",
    "High Metal Cap S",
    "Aelucanth Vertex X",
    "Rhopessa Vertex X",
    "Aelucanth Clypeus X",
    "Rhopessa Clypeus X",
    "Obituary Vertex X",
    "Butterfly Vertex X",
    "Obituary Clypeus X",
    "Butterfly Clypeus X",
    "EX Auroros Helm",
    "EX Borealis Crown",
    "EX Genesis Headpiece",
    "EX Glyph Crown",
    "Tempest Crown",
    "Welkin Crown",
    "GX Escadora Casque",
    "GX Escadora Coif",
    "GX Dragoncasque X",
    "GX Dragoncoif X",
    "Star Knight Helm",
    "Star Knight Cap",
    "Helm of Rage",
    "Cap of Rage",
    "Varia Suit Visor",
    "Zero Suit Wig",
    "Varia Suit Scope",
    "Zero Suit Hairpiece",
    "Varia Suit Visor",
    "Zero Suit Ponytail",
    "Varia Suit Scope",
    "Zero Suit Hairpiece",
    "DUMMY",
    "DUMMY",
    "Hawkhat X",
    "Lecturer's Hood X",
    "Hawkcap X",
    "Lecturer's Cap X",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "Hawkeye Earring",
    "Amplifeathers",
    "Craftsman's Specs",
    "Felyne Hairband X",
    "Sword Saint Earring",
    "Barrage Earring",
    "Chaoshroom",
    "Velociprey Mask",
    "Giaprey Mask",
    "Genprey Mask",
    "Mosswine Mask",
    "Bulldrome Mask",
    "Garuga Mask",
    "False Felyne",
    "Acorn Helm",
    "Palico Bro",
    "GX Hunter's Casque",
    "GX Hunter's Coif",
    "GX Esurient Casque",
    "GX Esurient Coif",
    "GX Tempest Diadem",
    "GX Welkin Diadem",
    "GX Fatalis Crimsonhelm",
    "GX Fatalis Crimsoncoif",
    "Hunter's Helm",
    "Hunter's Cap",
    "Hunter's Helm",
    "Hunter's Cap",
    "Ludroth Helm",
    "Ludroth Cap",
    "Ludroth Helm",
    "Ludroth Cap",
    "Alloy Helm",
    "Alloy Cap",
    "Alloy Helm",
    "Alloy Cap",
    "Gypceros Helm",
    "Gypceros Cap",
    "Gypceros Helm",
    "Gypceros Cap",
    "Khezu Helm",
    "Khezu Cap",
    "Khezu Helm",
    "Khezu Cap",
    "Ingot Helm",
    "Ingot Cap",
    "Ingot Helm",
    "Ingot Cap",
    "Rathian Helm",
    "Rathian Cap",
    "Lagiacrus Helm",
    "Lagiacrus Cap",
    "Rathalos Helm",
    "Rathalos Cap",
    "Gypceros Helm U",
    "Gypceros Cap U",
    "Khezu Helm U",
    "Khezu Cap U",
    "Tigrex Helm",
    "Tigrex Cap",
    "Kirin Horn",
    "Kirin Crest",
    "Kirin Horn",
    "Kirin Crest",
    "Artian Helm S",
    "Artian Cap S",
    "Ceanataur Helm",
    "Ceanataur Cap",
    "Ceanataur Helm",
    "Ceanataur Cap",
    "Gloaming Helm",
    "Dayspring Kasa",
    "Adamance Helm",
    "Epoch Helm",
    "Zinogre Helm U",
    "Zinogre Cap U",
    "Tigrex Helm U",
    "Tigrex Cap U",
    "Gore Helm",
    "Gore Cap",
    "Auroros Helm",
    "Genesis Headpiece",
    "Borealis Crown",
    "Glyph Crown",
    "Kirin Horn U",
    "Kirin Crest U",
    "Kirin Horn U",
    "Kirin Crest U",
    "Esurient Helm",
    "Esurient Cap",
    "Monoblos Helm",
    "Monoblos Cap",
    "Hornet Helm",
    "Hornet Cap",
    "Wroggi Hat",
    "Wroggi Cap",
    "Monodevil Helm",
    "Monodevil Cap",
    "Diablos Helm",
    "Diablos Cap",
    "Gigginox Helm",
    "Gigginox Cap",
    "Death Stench Brain",
    "Death Stench Soul",
    "Damascus Helm",
    "Damascus Cap",
    "DUMMY",
    "DUMMY"
};

enum Head_e {
    NoHead,
    Derring_Headgear,
    Derring_Helm_S,
    Derring_Cap_S,
    Leather_Headgear,
    Leather_Helm_S,
    Leather_Cap_S,
    Chainmail_Headgear,
    Chainmail_Helm_S,
    Chainmail_Cap_S,
    Hunter_s_Helm_0,
    Hunter_s_Cap_0,
    Hunter_s_Helm_S,
    Hunter_s_Cap_S,
    Hunter_s_Helm_1,
    Hunter_s_Cap_1,
    Bone_Helm,
    Bone_Cap,
    Bone_Helm_S,
    Bone_Cap_S,
    Alloy_Helm_0,
    Alloy_Cap_0,
    Alloy_Helm_S,
    Alloy_Cap_S,
    Alloy_Helm_1,
    Alloy_Cap_1,
    Jaggi_Helm,
    Jaggi_Cap,
    Jaggi_Helm_S,
    Jaggi_Cap_S,
    Ludroth_Helm_0,
    Ludroth_Cap_0,
    Ludroth_Helm_1,
    Ludroth_Cap_1,
    Rhenoplos_Helm,
    Rhenoplos_Cap,
    Rhenoplos_Helm_S,
    Rhenoplos_Cap_S,
    Bnahabra_Hat,
    Bnahabra_Headpiece,
    Bnahabra_Hat_S,
    Bnahabra_Headpiece_S,
    Barroth_Helm,
    Barroth_Cap,
    Rathian_Helm_0,
    Rathian_Cap_0,
    Rathian_Helm_S,
    Rathian_Cap_S,
    Rath_Heart_Helm_0,
    Rath_Heart_Cap_0,
    Golden_Lunehelm,
    Golden_Lunecap,
    Rathian_Helm_1,
    Rathian_Cap_1,
    Rath_Heart_Helm_1,
    Rath_Heart_Cap_1,
    EX_Rathian_Helm,
    EX_Rathian_Cap,
    Rathalos_Helm_0,
    Rathalos_Cap_0,
    Rathalos_Helm_S,
    Rathalos_Cap_S,
    Rath_Soul_Helm_0,
    Rath_Soul_Cap_0,
    Silver_Solhelm_0,
    Silver_Solcap_0,
    Rathalos_Helm_1,
    Rathalos_Cap_1,
    Rath_Soul_Helm_1,
    Rath_Soul_Cap_1,
    Silver_Solhelm_1,
    Silver_Solcap_1,
    EX_Rathalos_Helm,
    EX_Rathalos_Cap,
    Diablos_Helm_0,
    Diablos_Cap_0,
    Uragaan_Helm,
    Uragaan_Cap,
    Vangis_Helm,
    Vangis_Cap,
    Esurient_Helm_0,
    Esurient_Cap_0,
    Esurient_Helm_1,
    Esurient_Cap_1,
    Gloaming_Helm_0,
    Adamance_Helm_0,
    Dayspring_Kasa_0,
    Epoch_Helm_0,
    Gloaming_Archhelm,
    Adamance_Archhelm,
    Dayspring_Archkasa,
    Epoch_Archhelm,
    Gloaming_Helm_1,
    Adamance_Helm_1,
    Dayspring_Kasa_1,
    Epoch_Helm_1,
    Plesioth_Helm,
    Plesioth_Cap,
    Nibelsnarf_Helm,
    Nibelsnarf_Cap,
    Duramboros_Helm,
    Duramboros_Cap,
    Arzuros_Helm,
    Arzuros_Cap,
    Lagombi_Helm,
    Lagombi_Cap,
    Lagombi_Helm_S,
    Lagombi_Cap_S,
    Slagtoth_Hood,
    Slagtoth_Cowl,
    Slagtoth_Hood_S,
    Slagtoth_Cowl_S,
    Nargacuga_Helm,
    Nargacuga_Cap,
    Tigrex_Helm_0,
    Tigrex_Cap_0,
    Tigrex_Helm_S,
    Tigrex_Cap_S,
    Tigrex_Helm_U_0,
    Tigrex_Cap_U_0,
    Excello_Helm,
    Excello_Cap,
    EX_Tigrex_Helm,
    EX_Tigrex_Cap,
    Tigrex_Helm_1,
    Tigrex_Cap_1,
    Tigrex_Helm_U_1,
    Tigrex_Cap_U_1,
    Brachydios_Helm,
    Brachydios_Cap,
    Brachydios_Helm_S,
    Brachydios_Cap_S,
    Akantor_Mask_0,
    Akantor_Fangs_0,
    Akantor_Mask_1,
    Akantor_Fangs_1,
    Zinogre_Helm,
    Zinogre_Cap,
    Zinogre_Helm_S,
    Zinogre_Cap_S,
    Zinogre_Helm_U_0,
    Zinogre_Cap_U_0,
    Zinogre_Helm_U_1,
    Zinogre_Cap_U_1,
    EX_Kaiser_Crown,
    EX_Kaiser_Mask,
    Kecha_Helm,
    Kecha_Cap,
    Kecha_Helm_S,
    Kecha_Cap_S,
    Gore_Helm_0,
    Gore_Cap_0,
    Gore_Helm_S,
    Gore_Cap_S,
    Gore_Helm_1,
    Gore_Cap_1,
    Tetsucabra_Helm,
    Tetsucabra_Cap,
    Tetsucabra_Helm_S,
    Tetsucabra_Cap_S,
    Nerscylla_Helm,
    Nerscylla_Cap,
    Nerscylla_Helm_S,
    Nerscylla_Cap_S,
    Najarala_Helm,
    Najarala_Cap,
    Najarala_Helm_S,
    Najarala_Cap_S,
    Garuga_Helm,
    Garuga_Cap,
    Garuga_Helm_S,
    Garuga_Cap_S,
    Basarios_Helm,
    Basarios_Cap,
    Basarios_Helm_S,
    Basarios_Cap_S,
    Basarios_Helm_U,
    Basarios_Cap_U,
    Battle_Helm,
    Battle_Cap,
    Velociprey_Helm,
    Velociprey_Cap,
    Velociprey_Helm_S,
    Velociprey_Cap_S,
    Genprey_Helm,
    Genprey_Cap,
    Genprey_Helm_S,
    Genprey_Cap_S,
    Ioprey_Helm,
    Ioprey_Cap,
    Ioprey_Helm_S,
    Ioprey_Cap_S,
    Kut_Ku_Helm,
    Kut_Ku_Cap,
    Kut_Ku_Helm_S,
    Kut_Ku_Cap_S,
    Kut_Ku_Helm_U,
    Kut_Ku_Cap_U,
    Gypceros_Helm_0,
    Gypceros_Cap_0,
    Gypceros_Helm_S,
    Gypceros_Cap_S,
    Gypceros_Helm_U_0,
    Gypceros_Cap_U_0,
    Gypceros_Helm_1,
    Gypceros_Cap_1,
    Gypceros_Helm_U_1,
    Gypceros_Cap_U_1,
    Conga_Helm,
    Conga_Cap,
    Conga_Helm_S,
    Conga_Cap_S,
    Conga_Helm_U,
    Conga_Cap_U,
    Gravios_Helm,
    Gravios_Cap,
    Gravios_Helm_S,
    Gravios_Cap_S,
    Gravios_Helm_U,
    Gravios_Cap_U,
    Khezu_Helm_0,
    Khezu_Cap_0,
    Khezu_Helm_S,
    Khezu_Cap_S,
    Khezu_Helm_U_0,
    Khezu_Cap_U_0,
    Khezu_Helm_1,
    Khezu_Cap_1,
    Khezu_Helm_U_1,
    Khezu_Cap_U_1,
    Kirin_Horn_0,
    Kirin_Crest_0,
    Kirin_Horn_S,
    Kirin_Crest_S,
    Kirin_Horn_U_0,
    Kirin_Crest_U_0,
    Kirin_Horn_1,
    Kirin_Crest_1,
    Kirin_Horn_U_1,
    Kirin_Crest_U_1,
    Kushala_Glare_0,
    Kushala_Snarl_0,
    EX_Kushala_Glare,
    EX_Kushala_Snarl,
    Kushala_Glare_1,
    Kushala_Snarl_1,
    Empress_Crown,
    Empress_Mask,
    Ceanataur_Helm_0,
    Ceanataur_Cap_0,
    Ceanataur_Helm_1,
    Ceanataur_Cap_1,
    Auroros_Helm_0,
    Borealis_Crown_0,
    Genesis_Headpiece_0,
    Glyph_Crown_0,
    Auroros_Helm_1,
    Borealis_Crown_1,
    Genesis_Headpiece_1,
    Glyph_Crown_1,
    Lava_Helm,
    Lava_Cap,
    Remobra_Headgear,
    Remobra_Mask,
    Remobra_Headgear_S,
    Remobra_Mask_S,
    Zamtrios_Helm,
    Zamtrios_Cap,
    Zamtrios_Helm_S,
    Zamtrios_Cap_S,
    Seltas_Helm,
    Seltas_Cap,
    Seltas_Helm_S,
    Seltas_Cap_S,
    Arc_Helm_0,
    Arc_Cap_0,
    Arc_Helm_S,
    Arc_Cap_S,
    Arc_Helm_1,
    Arc_Cap_1,
    Kaiser_Crown,
    Kaiser_Mask,
    Golden_Headdress,
    Puppeteer_Mask,
    Divine_Ire_Headdress,
    Crusher_Mask,
    Rebellion_Helm_0,
    Riot_Cap_0,
    Rebellion_Helm_1,
    Riot_Cap_1,
    Dragonhead_X_0,
    Dragonface_X_0,
    Dragonhead,
    Dragonface,
    Fatalis_Crimsonhead,
    Fatalis_Crimsonface,
    Ioprey_Head,
    Ioprey_Face,
    Cephalos_Helm,
    Cephalos_Cap,
    Mizuha_Cap,
    Cham_Hat,
    Hermitaur_Helm_0,
    Hermitaur_Cap_0,
    Hermitaur_Helm_1,
    Hermitaur_Cap_1,
    Vespoid_Helm,
    Vespoid_Cap,
    Qurupeco_Helm,
    Qurupeco_Cap,
    Agnaktor_Helm,
    Agnaktor_Cap,
    Barioth_Helm,
    Barioth_Cap,
    Volvidon_Helm,
    Volvidon_Cap,
    Lagiacrus_Helm_0,
    Lagiacrus_Cap_0,
    Lagiacrus_Helm_1,
    Lagiacrus_Cap_1,
    Helios_Helm,
    Helios_Cap,
    Selene_Helm,
    Selene_Cap,
    Gobul_Helm,
    Gobul_Cap,
    Yamato_Kabuto,
    Hyuga_Hachigane,
    Mutsu_Eboshi,
    Amagi_Hachigane,
    Escadora_Wisdom_0,
    Escadora_Sagesse_0,
    Escadora_Wisdom_1,
    Escadora_Sagesse_1,
    Blango_Helm,
    Blango_Cap,
    Lobster_Helm,
    Lobster_Cap,
    Ukanlos_Mask,
    Ukanlos_Fangs,
    Indra_Helm,
    Steadfast_Helm,
    Yaksha_Mask,
    Carnage_Helm,
    Artian_Helm_S_0,
    Artian_Cap_S_0,
    Dober_Helm,
    Dober_Cap,
    Ingot_Helm_0,
    Ingot_Cap_0,
    Ingot_Helm_1,
    Ingot_Cap_1,
    Aelucanth_Vertex,
    Rhopessa_Vertex,
    Aelucanth_Clypeus,
    Rhopessa_Clypeus,
    Obituary_Vertex,
    Butterfly_Vertex,
    Obituary_Clypeus,
    Butterfly_Clypeus,
    Mosgharl_Vizor,
    Mosgharl_Brim,
    Guild_Bard_Lobos,
    Scholar_s_Beret,
    Guild_Bard_Hat,
    Scholar_s_Cap,
    Skull_Visage,
    Skull_Mask,
    Shadow_Shades,
    Jaggi_Mask,
    Gargwa_Mask,
    Black_Belt_Helm,
    Black_Belt_Cap,
    Guardian_Helm,
    Helper_Hood,
    Guardian_Mask,
    Helper_Cap,
    Shinobi_Sky_Mask,
    Shinobi_Land_Mask,
    Guild_Knight_Feather,
    Maiden_s_Hat,
    Guild_Knight_Mask,
    Maiden_s_Cap,
    Yukumo_Sky_Kasa,
    Yukumo_Land_Kasa,
    High_Metal_Helm,
    High_Metal_Cap,
    Ranger_s_Headgear,
    Archer_s_Turban,
    Dragonlord_s_Gaze,
    Chakra_Earring,
    Sailor_Hat,
    Sailor_Cap,
    Hawkhat,
    Lecturer_s_Hood,
    Hawkcap,
    Lecturer_s_Cap,
    Friendship_Feather,
    Victory_Feather,
    Champion_Feather,
    Felyne_Hairband,
    Cunning_Specs,
    Blue_Star_Lobos,
    Blue_Star_Hat,
    dummy_head701,
    Helm_of_Anat,
    Cap_of_Anat,
    Uniqlo_Hood,
    Uniqlo_Cap,
    Star_Rook_Helm,
    Star_Rook_Cap,
    dummy_head706,
    dummy_head718,
    dummy_head707,
    dummy_head719,
    Artian_Helm_S_1,
    Artian_Cap_S_1,
    Overlord_Feather,
    dummy_head_0,
    Hero_s_Hat,
    dummy_head_1,
    Hero_s_Cap,
    dummy_head729,
    dummy_head730,
    EX_Rebellion_Helm,
    EX_Riot_Cap,
    EX_Gore_Helm,
    EX_Gore_Cap,
    EX_Ingot_Helm,
    EX_Ingot_Cap,
    EX_Kirin_Horn_U,
    EX_Kirin_Crest_U,
    EX_Artian_Helm,
    EX_Artian_Cap,
    Storge_Helm_0,
    Storge_Cap_0,
    Storge_Helm_S,
    Storge_Cap_S,
    Storge_Helm_1,
    Storge_Cap_1,
    Hunter_s_Helm_2,
    Hunter_s_Cap_2,
    Alloy_Helm_2,
    Alloy_Cap_2,
    Ludroth_Helm_2,
    Ludroth_Cap_2,
    Rathian_Helm_2,
    Rathian_Cap_2,
    Rath_Heart_Helm_2,
    Rath_Heart_Cap_2,
    Rathalos_Helm_2,
    Rathalos_Cap_2,
    Rath_Soul_Helm_2,
    Rath_Soul_Cap_2,
    Silver_Solhelm_2,
    Silver_Solcap_2,
    Esurient_Helm_2,
    Esurient_Cap_2,
    Gloaming_Helm_2,
    Adamance_Helm_2,
    Dayspring_Kasa_2,
    Epoch_Helm_2,
    Tigrex_Helm_2,
    Tigrex_Cap_2,
    Tigrex_Helm_U_2,
    Tigrex_Cap_U_2,
    Akantor_Mask_2,
    Akantor_Fangs_2,
    Zinogre_Helm_U_2,
    Zinogre_Cap_U_2,
    Gore_Helm_2,
    Gore_Cap_2,
    Gypceros_Helm_2,
    Gypceros_Cap_2,
    Gypceros_Helm_U_2,
    Gypceros_Cap_U_2,
    Khezu_Helm_2,
    Khezu_Cap_2,
    Khezu_Helm_U_2,
    Khezu_Cap_U_2,
    Kirin_Horn_2,
    Kirin_Crest_2,
    Kirin_Horn_U_2,
    Kirin_Crest_U_2,
    Kushala_Glare_2,
    Kushala_Snarl_2,
    Ceanataur_Helm_2,
    Ceanataur_Cap_2,
    Auroros_Helm_2,
    Borealis_Crown_2,
    Genesis_Headpiece_2,
    Glyph_Crown_2,
    Arc_Helm_2,
    Arc_Cap_2,
    Rebellion_Helm_2,
    Riot_Cap_2,
    Dragonhead_X_1,
    Dragonface_X_1,
    Hermitaur_Helm_2,
    Hermitaur_Cap_2,
    Lagiacrus_Helm_2,
    Lagiacrus_Cap_2,
    Escadora_Wisdom_2,
    Escadora_Sagesse_2,
    Ingot_Helm_2,
    Ingot_Cap_2,
    Artian_Helm_S_2,
    Artian_Cap_S_2,
    Storge_Helm_2,
    Storge_Cap_2,
    Velociprey_Helm_X,
    Velociprey_Cap_X,
    Ioprey_Helm_X,
    Ioprey_Cap_X,
    Kecha_Helm_X,
    Kecha_Cap_X,
    Kecha_Helm_Z,
    Kecha_Cap_Z,
    Tetsucabra_Helm_X,
    Tetsucabra_Cap_X,
    Tetsucabra_Helm_Z,
    Tetsucabra_Cap_Z,
    Nerscylla_Helm_X,
    Nerscylla_Cap_X,
    Nerscylla_Helm_Z,
    Nerscylla_Cap_Z,
    Zamtrios_Helm_X,
    Zamtrios_Cap_X,
    Zamtrios_Helm_Z,
    Zamtrios_Cap_Z,
    Najarala_Helm_X,
    Najarala_Cap_X,
    Najarala_Helm_Z,
    Najarala_Cap_Z,
    Seltas_Helm_X,
    Seltas_Cap_X,
    Seltas_Helm_Z,
    Seltas_Cap_Z,
    Gore_Helm_X,
    Gore_Cap_X,
    Gore_Casque,
    Gore_Coif,
    Arc_Helm_X,
    Storge_Helm_X,
    Arc_Cap_X,
    Storge_Cap_X,
    Arc_Casque,
    Storge_Casque,
    Arc_Coif,
    Storge_Coif,
    Gogma_Helm,
    Gogma_Cap,
    Gypceros_Helm_X,
    Gypceros_Cap_X,
    Gypceros_Casque,
    Gypceros_Coif,
    Gypceros_Helm_Z,
    Gypceros_Cap_Z,
    Gypceros_Casque_U,
    Gypceros_Coif_U,
    Lagombi_Helm_X,
    Lagombi_Cap_X,
    Conga_Helm_X,
    Conga_Cap_X,
    Conga_Helm_Z,
    Conga_Cap_Z,
    Khezu_Helm_X,
    Khezu_Cap_X,
    Khezu_Casque,
    Khezu_Coif,
    Khezu_Helm_Z,
    Khezu_Cap_Z,
    Khezu_Casque_U,
    Khezu_Coif_U,
    Rathian_Helm_X,
    Rathian_Cap_X,
    Rathian_Casque,
    Rathian_Coif,
    Rath_Heart_Helm_Z,
    Rath_Heart_Cap_Z,
    Rath_Heart_Casque,
    Rath_Heart_Coif,
    Golden_Lunehelm_Z,
    Golden_Lunecap_Z,
    Rathalos_Helm_X,
    Rathalos_Cap_X,
    Rathalos_Casque,
    Rathalos_Coif,
    Rath_Soul_Helm_Z,
    Rath_Soul_Cap_Z,
    Rath_Soul_Casque,
    Rath_Soul_Coif,
    Silver_Solhelm_Z,
    Silver_Solcap_Z,
    Silver_Solcasque,
    Silver_Solcoif,
    Zinogre_Helm_X,
    Zinogre_Cap_X,
    Zinogre_Helm_Z,
    Zinogre_Cap_Z,
    Zinogre_Casque_U,
    Zinogre_Coif_U,
    Tigrex_Helm_X,
    Tigrex_Cap_X,
    Tigrex_Casque,
    Tigrex_Coif,
    Tigrex_Helm_Z,
    Tigrex_Cap_Z,
    Tigrex_Casque_U,
    Tigrex_Coif_U,
    Excello_Helm_Z,
    Excello_Cap_Z,
    Gravios_Helm_X,
    Gravios_Cap_X,
    Gravios_Helm_Z,
    Gravios_Cap_Z,
    Brachydios_Helm_X,
    Brachydios_Cap_X,
    Brachydium_Helm,
    Brachydium_Cap,
    Grand_Gloaming_Helm,
    Grand_Adamance_Helm,
    Grand_Dayspring_Helm,
    Grand_Epoch_Helm,
    Gloaming_Redhelm,
    Adamance_Redhelm,
    Dayspring_Redhelm,
    Epoch_Redhelm,
    Vangis_Helm_X,
    Vangis_Cap_X,
    Esurient_Helm_Z,
    Esurient_Cap_Z,
    Esurient_Casque,
    Esurient_Coif,
    Kaiser_Crown_X,
    Kaiser_Mask_X,
    Akantor_Mask_X,
    Akantor_Fangs_X,
    Akantor_Casque,
    Akantor_Coif,
    EX_Escadora_Wisdom,
    EX_Escadora_Sagesse,
    Ukanlos_Mask_X,
    Ukanlos_Fangs_X,
    Kushala_Glare_X,
    Kushala_Snarl_X,
    Kushala_Casque,
    Kushala_Coif,
    Kujula_Glare,
    Kujula_Snarl,
    Grand_God_s_Peer_Mask,
    Grand_Hermit_Mask,
    Grand_Divine_Ire_Mask,
    Grand_Crusher_Mask,
    Rebellion_Helm_X,
    Riot_Cap_X,
    Rebellion_Casque,
    Riot_Coif,
    Rebellion_Helm_Z,
    Riot_Cap_Z,
    Cephalos_Helm_X,
    Cephalos_Cap_X,
    Hermitaur_Helm_X,
    Hermitaur_Cap_X,
    Hermitaur_Casque,
    Hermitaur_Coif,
    Hermitaur_Helm_Z,
    Hermitaur_Cap_Z,
    Mono_Helm_S,
    Mono_Cap_S,
    Mono_Helm_X,
    Mono_Cap_X,
    Mono_Helm,
    Mono_Cap,
    Mono_Casque,
    Mono_Coif,
    Monodevil_Helm_0,
    Monodevil_Cap_0,
    Monodevil_Helm_1,
    Monodevil_Cap_1,
    Monodevil_Casque,
    Monodevil_Coif,
    Diablos_Helm_X,
    Diablos_Cap_X,
    Diablos_Helm_1,
    Diablos_Cap_1,
    Diablos_Casque,
    Diablos_Coif,
    Diablos_Helm_Z,
    Diablos_Cap_Z,
    Dragonhead_X_2,
    Dragonface_X_2,
    Dragoncasque_X,
    Dragoncoif_X,
    Fatalis_Crimsonhead_Z,
    Fatalis_Crimsonface_Z,
    Fatalis_Crimsonhelm_Z,
    Fatalis_Crimsoncoif_Z,
    Wrothhead,
    Wrothface,
    White_Fatalis_Head,
    White_Fatalis_Face,
    Grand_Mizuha_Mask,
    Grand_Cham_Hat,
    Regios_Helm_S,
    Regios_Cap_S,
    Regios_Helm_X,
    Regios_Cap_X,
    Chaos_Helm,
    Nephilim_Helm,
    Chaos_Cap,
    Nephilim_Cap,
    Basarios_Helm_X,
    Basarios_Cap_X,
    Basarios_Helm_Z,
    Basarios_Cap_Z,
    Kut_Ku_Helm_X,
    Kut_Ku_Cap_X,
    Kut_Ku_Helm_Z,
    Kut_Ku_Cap_Z,
    Garuga_Helm_X,
    Garuga_Cap_X,
    Kirin_Horn_X,
    Kirin_Crest_X,
    Kirin_Casque,
    Kirin_Coif,
    Kirin_Horn_Z,
    Kirin_Crest_Z,
    Kirin_Casque_U,
    Kirin_Coif_U,
    Bnahabra_Hat_X,
    Bnahabra_Headpiece_X,
    Slagtoth_Hood_X,
    Slagtoth_Cowl_X,
    Rhenoplos_Helm_X,
    Rhenoplos_Cap_X,
    Hunter_s_Casque,
    Hunter_s_Coif,
    Alloy_Casque,
    Alloy_Coif,
    Artian_Helm_X,
    Artian_Cap_X,
    Arc_Casque_S,
    Arc_Coif_S,
    Ingot_Casque,
    Ingot_Coif,
    Guardian_Helm_X,
    Helper_Hood_X,
    Guardian_Mask_X,
    Healer_Glasses_X,
    Guardian_Helm_Z,
    Helper_Hood_Z,
    Guardian_Mask_Z,
    Healer_Beret_Z,
    G__Knight_Feather_X,
    Maiden_s_Hat_X,
    G__Knight_Mask_X,
    Exclusive_Glasses_X,
    Ace_Headgear,
    Sororal_Headgear,
    Ace_Mask,
    Sororal_Mask,
    Ceanataur_Casque,
    Ceanataur_Coif,
    Lagiacrus_Casque,
    Lagiacrus_Coif,
    Escadora_Casque,
    Escadora_Coif,
    Auroros_Kermes_Helm,
    Borealis_Bellflower,
    Genesis_Kermes_Helm,
    Glyph_Bellflower,
    Ludroth_Casque,
    Ludroth_Coif,
    Hornet_Helm_0,
    Hornet_Cap_0,
    Hornet_Casque,
    Hornet_Coif,
    Wroggi_Hat_0,
    Wroggi_Cap_0,
    Wroggi_Casque,
    Wroggi_Coif,
    Gigginox_Helm_0,
    Gigginox_Cap_0,
    Gigginox_Casque,
    Gigginox_Coif,
    Tempest_Crown_0,
    Welkin_Crown_0,
    Tempest_Diadem,
    Welkin_Diadem,
    Death_Stench_Brain_0,
    Death_Stench_Soul_0,
    Death_Stench_Casque,
    Death_Stench_Coif,
    Damascus_Helm_0,
    Damascus_Cap_0,
    Damascus_Casque,
    Damascus_Coif,
    Lagiacrus_Helm_X,
    Lagiacrus_Cap_X,
    Nargacuga_Helm_X,
    Nargacuga_Cap_X,
    Empress_Crown_X,
    Empress_Mask_X,
    Helios_Helm_X,
    Selene_Helm_X,
    Helios_Cap_X,
    Selene_Cap_X,
    Agnaktor_Helm_X,
    Agnaktor_Cap_X,
    Qurupeco_Helm_X,
    Qurupeco_Cap_X,
    Gobul_Helm_X,
    Gobul_Cap_X,
    Barioth_Helm_X,
    Barioth_Cap_X,
    Barroth_Helm_X,
    Barroth_Cap_X,
    Nibelsnarf_Helm_X,
    Nibelsnarf_Cap_X,
    Duramboros_Helm_X,
    Duramboros_Cap_X,
    Lava_Helm_X,
    Lava_Cap_X,
    Grand_Yamato_Kabuto,
    Grand_H__Hachigane,
    Grand_Mutsu_Jingasa,
    Grand_Amagi_Jingasa,
    Grand_Yaksha_Mask,
    Grand_Carnage_Helm,
    Miralis_Diadem,
    Miralis_Crown,
    Plesioth_Helm_Z,
    Plesioth_Cap_Z,
    Kita_Star_Headdress,
    Umi_Ocean_Headdress,
    Patissier_s_Toque,
    Patissier_s_Cap,
    High_Metal_Helm_S,
    High_Metal_Cap_S,
    Aelucanth_Vertex_X,
    Rhopessa_Vertex_X,
    Aelucanth_Clypeus_X,
    Rhopessa_Clypeus_X,
    Obituary_Vertex_X,
    Butterfly_Vertex_X,
    Obituary_Clypeus_X,
    Butterfly_Clypeus_X,
    EX_Auroros_Helm,
    EX_Borealis_Crown,
    EX_Genesis_Headpiece,
    EX_Glyph_Crown,
    Tempest_Crown_1,
    Welkin_Crown_1,
    GX_Escadora_Casque,
    GX_Escadora_Coif,
    GX_Dragoncasque_X,
    GX_Dragoncoif_X,
    Star_Knight_Helm,
    Star_Knight_Cap,
    Helm_of_Rage,
    Cap_of_Rage,
    Varia_Suit_Visor_0,
    Zero_Suit_Wig,
    Varia_Suit_Scope_0,
    Zero_Suit_Hairpiece_0,
    Varia_Suit_Visor_1,
    Zero_Suit_Ponytail,
    Varia_Suit_Scope_1,
    Zero_Suit_Hairpiece_1,
    dummy_head_2,
    dummy_head_3,
    Hawkhat_X,
    Lecturer_s_Hood_X,
    Hawkcap_X,
    Lecturer_s_Cap_X,
    dummy_head_4,
    dummy_head_5,
    dummy_head_6,
    Hawkeye_Earring,
    Amplifeathers,
    Craftsman_s_Specs,
    Felyne_Hairband_X,
    Sword_Saint_Earring,
    Barrage_Earring,
    Chaoshroom,
    Velociprey_Mask,
    Giaprey_Mask,
    Genprey_Mask,
    Mosswine_Mask,
    Bulldrome_Mask,
    Garuga_Mask,
    False_Felyne,
    Acorn_Helm,
    Palico_Bro,
    GX_Hunter_s_Casque,
    GX_Hunter_s_Coif,
    GX_Esurient_Casque,
    GX_Esurient_Coif,
    GX_Tempest_Diadem,
    GX_Welkin_Diadem,
    GX_Fatalis_Crimsonhelm,
    GX_Fatalis_Crimsoncoif,
    Hunter_s_Helm_3,
    Hunter_s_Cap_3,
    Hunter_s_Helm_4,
    Hunter_s_Cap_4,
    Ludroth_Helm_3,
    Ludroth_Cap_3,
    Ludroth_Helm_4,
    Ludroth_Cap_4,
    Alloy_Helm_3,
    Alloy_Cap_3,
    Alloy_Helm_4,
    Alloy_Cap_4,
    Gypceros_Helm_3,
    Gypceros_Cap_3,
    Gypceros_Helm_4,
    Gypceros_Cap_4,
    Khezu_Helm_3,
    Khezu_Cap_3,
    Khezu_Helm_4,
    Khezu_Cap_4,
    Ingot_Helm_3,
    Ingot_Cap_3,
    Ingot_Helm_4,
    Ingot_Cap_4,
    Rathian_Helm_3,
    Rathian_Cap_3,
    Lagiacrus_Helm_3,
    Lagiacrus_Cap_3,
    Rathalos_Helm_3,
    Rathalos_Cap_3,
    Gypceros_Helm_U_3,
    Gypceros_Cap_U_3,
    Khezu_Helm_U_3,
    Khezu_Cap_U_3,
    Tigrex_Helm_3,
    Tigrex_Cap_3,
    Kirin_Horn_3,
    Kirin_Crest_3,
    Kirin_Horn_4,
    Kirin_Crest_4,
    Artian_Helm_S_3,
    Artian_Cap_S_3,
    Ceanataur_Helm_3,
    Ceanataur_Cap_3,
    Ceanataur_Helm_4,
    Ceanataur_Cap_4,
    Gloaming_Helm_3,
    Dayspring_Kasa_3,
    Adamance_Helm_3,
    Epoch_Helm_3,
    Zinogre_Helm_U_3,
    Zinogre_Cap_U_3,
    Tigrex_Helm_U_3,
    Tigrex_Cap_U_3,
    Gore_Helm_3,
    Gore_Cap_3,
    Auroros_Helm_3,
    Genesis_Headpiece_3,
    Borealis_Crown_3,
    Glyph_Crown_3,
    Kirin_Horn_U_3,
    Kirin_Crest_U_3,
    Kirin_Horn_U_4,
    Kirin_Crest_U_4,
    Esurient_Helm_3,
    Esurient_Cap_3,
    Monoblos_Helm,
    Monoblos_Cap,
    Hornet_Helm_1,
    Hornet_Cap_1,
    Wroggi_Hat_1,
    Wroggi_Cap_1,
    Monodevil_Helm_2,
    Monodevil_Cap_2,
    Diablos_Helm_2,
    Diablos_Cap_2,
    Gigginox_Helm_1,
    Gigginox_Cap_1,
    Death_Stench_Brain_1,
    Death_Stench_Soul_1,
    Damascus_Helm_1,
    Damascus_Cap_1,
    dummy_head_7,
    dummy_head_8
};
}
