#pragma once

namespace MH4U {
constexpr const char* Legs_s[] = {
    "(None)",
    "Derring Trousers",
    "Derring Greaves S",
    "Derring Leggings S",
    "Leather Trousers",
    "Leather Greaves S",
    "Leather Leggings S",
    "Chainmail Trousers",
    "Chainmail Greaves S",
    "Chainmail Leggings S",
    "Hunter's Greaves",
    "Hunter's Leggings",
    "Hunter's Greaves S",
    "Hunter's Leggings S",
    "Hunter's Greaves",
    "Hunter's Leggings",
    "Bone Greaves",
    "Bone Leggings",
    "Bone Greaves S",
    "Bone Leggings S",
    "Alloy Greaves",
    "Alloy Leggings",
    "Alloy Greaves S",
    "Alloy Leggings S",
    "Alloy Greaves",
    "Alloy Leggings",
    "Jaggi Greaves",
    "Jaggi Leggings",
    "Jaggi Greaves S",
    "Jaggi Leggings S",
    "Loc Lac Boots",
    "Ludroth Greaves",
    "Ludroth Leggings",
    "Ludroth Greaves",
    "Ludroth Leggings",
    "Rhenoplos Greaves",
    "Rhenoplos Leggings",
    "Rhenoplos Greaves S",
    "Rhenoplos Leggings S",
    "Bnahabra Boots",
    "Bnahabra Pants",
    "Bnahabra Boots S",
    "Bnahabra Pants S",
    "Barroth Greaves",
    "Barroth Leggings",
    "Rathian Greaves",
    "Rathian Leggings",
    "Rathian Greaves S",
    "Rathian Leggings S",
    "Rath Heart Greaves",
    "Rath Heart Leggings",
    "Golden Lunegreaves",
    "Golden Luneleggings",
    "Rathian Greaves",
    "Rathian Leggings",
    "Rath Heart Greaves",
    "Rath Heart Leggings",
    "EX Rathian Greaves",
    "EX Rathian Leggings",
    "Rathalos Greaves",
    "Rathalos Leggings",
    "Rathalos Greaves S",
    "Rathalos Leggings S",
    "Rath Soul Greaves",
    "Rath Soul Leggings",
    "Silver Solgreaves",
    "Silver Solleggings",
    "Rathalos Greaves",
    "Rathalos Leggings",
    "Rath Soul Greaves",
    "Rath Soul Leggings",
    "Silver Solgreaves",
    "Silver Solleggings",
    "EX Rathalos Greaves",
    "EX Rathalos Leggings",
    "Diablos Greaves",
    "Diablos Leggings",
    "Uragaan Greaves",
    "Uragaan Leggings",
    "Vangis Greaves",
    "Vangis Leggings",
    "Esurient Greaves",
    "Esurient Leggings",
    "Esurient Greaves",
    "Esurient Leggings",
    "Gloaming Greaves",
    "Adamance Pleats",
    "Dayspring Pleats",
    "Epoch Pleats",
    "Gloaming Archgreaves",
    "Adamance Archpleats",
    "Dayspring Archpleats",
    "Epoch Archpleats",
    "Gloaming Greaves",
    "Adamance Pleats",
    "Dayspring Pleats",
    "Epoch Pleats",
    "Plesioth Greaves",
    "Plesioth Leggings",
    "Nibelsnarf Greaves",
    "Nibelsnarf Leggings",
    "Duramboros Greaves",
    "Duramboros Leggings",
    "Arzuros Greaves",
    "Arzuros Leggings",
    "Lagombi Greaves",
    "Lagombi Leggings",
    "Lagombi Greaves S",
    "Lagombi Leggings S",
    "Nargacuga Greaves",
    "Nargacuga Leggings",
    "Tigrex Greaves",
    "Tigrex Leggings",
    "Tigrex Greaves S",
    "Tigrex Leggings S",
    "Tigrex Greaves U",
    "Tigrex Leggings U",
    "Excello Greaves",
    "Excello Leggings",
    "EX Tigrex Greaves",
    "EX Tigrex Leggings",
    "Tigrex Greaves",
    "Tigrex Leggings",
    "Tigrex Greaves U",
    "Tigrex Leggings U",
    "Brachydios Greaves",
    "Brachydios Leggings",
    "Brachydios Greaves S",
    "Brachy Leggings S",
    "Akantor Hessian",
    "Akantor Boots",
    "Akantor Hessian",
    "Akantor Boots",
    "Zinogre Greaves",
    "Zinogre Leggings",
    "Zinogre Greaves S",
    "Zinogre Leggings S",
    "Zinogre Greaves U",
    "Zinogre Leggings U",
    "Zinogre Greaves U",
    "Zinogre Leggings U",
    "EX Kaiser Greaves",
    "EX Kaiser Leggings",
    "Kecha Greaves",
    "Kecha Leggings",
    "Kecha Greaves S",
    "Kecha Leggings S",
    "Gore Greaves",
    "Gore Leggings",
    "Gore Greaves S",
    "Gore Leggings S",
    "Gore Greaves",
    "Gore Leggings",
    "Tetsucabra Greaves",
    "Tetsucabra Leggings",
    "Tetsucabra Greaves S",
    "Tetsucabra Leggings S",
    "Nerscylla Greaves",
    "Nerscylla Leggings",
    "Nerscylla Greaves S",
    "Nerscylla Leggings S",
    "Najarala Greaves",
    "Najarala Leggings",
    "Najarala Greaves S",
    "Najarala Leggings S",
    "Garuga Greaves",
    "Garuga Leggings",
    "Garuga Greaves S",
    "Garuga Leggings S",
    "Basarios Greaves",
    "Basarios Leggings",
    "Basarios Greaves S",
    "Basarios Leggings S",
    "Basarios Greaves U",
    "Basarios Leggings U",
    "Battle Greaves",
    "Battle Leggings",
    "Velociprey Greaves",
    "Velociprey Leggings",
    "Velociprey Greaves S",
    "Velociprey Leggings S",
    "Genprey Greaves",
    "Genprey Leggings",
    "Genprey Greaves S",
    "Genprey Leggings S",
    "Ioprey Greaves",
    "Ioprey Leggings",
    "Ioprey Greaves S",
    "Ioprey Leggings S",
    "Kut-Ku Greaves",
    "Kut-Ku Leggings",
    "Kut-Ku Greaves S",
    "Kut-Ku Leggings S",
    "Kut-Ku Greaves U",
    "Kut-Ku Leggings U",
    "Gypceros Greaves",
    "Gypceros Leggings",
    "Gypceros Greaves S",
    "Gypceros Leggings S",
    "Gypceros Greaves U",
    "Gypceros Leggings U",
    "Gypceros Greaves",
    "Gypceros Leggings",
    "Gypceros Greaves U",
    "Gypceros Leggings U",
    "Conga Greaves",
    "Conga Leggings",
    "Conga Greaves S",
    "Conga Leggings S",
    "Conga Greaves U",
    "Conga Leggings U",
    "Gravios Greaves",
    "Gravios Leggings",
    "Gravios Greaves S",
    "Gravios Leggings S",
    "Gravios Greaves U",
    "Gravios Leggings U",
    "Khezu Greaves",
    "Khezu Leggings",
    "Khezu Greaves S",
    "Khezu Leggings S",
    "Khezu Greaves U",
    "Khezu Leggings U",
    "Khezu Greaves",
    "Khezu Leggings",
    "Khezu Greaves U",
    "Khezu Leggings U",
    "Kirin Leg Guards",
    "Kirin Boots",
    "Kirin Leg Guards S",
    "Kirin Boots S",
    "Kirin Leg Guards U",
    "Kirin Boots U",
    "Kirin Leg Guards",
    "Kirin Boots",
    "Kirin Leg Guards U",
    "Kirin Boots U",
    "Kushala Crus",
    "Kushala Shank",
    "EX Kushala Crus",
    "EX Kushala Shank",
    "Kushala Crus",
    "Kushala Shank",
    "Empress Greaves",
    "Empress Leggings",
    "Ceanataur Greaves",
    "Ceanataur Leggings",
    "Ceanataur Greaves",
    "Ceanataur Leggings",
    "Auroros Pants",
    "Borealis Hakama",
    "Genesis Pants",
    "Glyph Hakama",
    "Auroros Pants",
    "Borealis Hakama",
    "Genesis Pants",
    "Glyph Hakama",
    "Lava Greaves",
    "Lava Leggings",
    "Remobra Feet",
    "Remobra Tights",
    "Remobra Feet S",
    "Remobra Tights S",
    "Zamtrios Greaves",
    "Zamtrios Leggings",
    "Zamtrios Greaves S",
    "Zamtrios Leggings S",
    "Seltas Greaves",
    "Seltas Leggings",
    "Seltas Greaves S",
    "Seltas Leggings S",
    "Arc Greaves",
    "Arc Leggings",
    "Arc Greaves S",
    "Arc Leggings S",
    "Arc Greaves",
    "Arc Leggings",
    "Kaiser Greaves",
    "Kaiser Leggings",
    "Golden Hakama",
    "Puppeteer Tabi",
    "Divine Ire Hakama",
    "Mind Crusher Tabi",
    "Rebellion Greaves",
    "Riot Leggings",
    "Rebellion Greaves",
    "Riot Leggings",
    "Dragonfeet X",
    "Dragonlegs X",
    "Dragonfeet",
    "Dragonlegs",
    "Fatalis Crimsonfeet",
    "Fatalis Crimsonlegs",
    "Ioprey Feet",
    "Ioprey Tights",
    "Cephalos Greaves",
    "Cephalos Leggings",
    "Mizuha Leg Wrap",
    "Cham Trousers",
    "Hermitaur Greaves",
    "Hermitaur Leggings",
    "Hermitaur Greaves",
    "Hermitaur Leggings",
    "Vespoid Greaves",
    "Vespoid Leggings",
    "Qurupeco Greaves",
    "Qurupeco Leggings",
    "Agnaktor Greaves",
    "Agnaktor Leggings",
    "Barioth Greaves",
    "Barioth Leggings",
    "Volvidon Greaves",
    "Volvidon Leggings",
    "Lagiacrus Greaves",
    "Lagiacrus Leggings",
    "Lagiacrus Greaves",
    "Lagiacrus Leggings",
    "Helios Greaves",
    "Helios Leggings",
    "Selene Greaves",
    "Selene Leggings",
    "Gobul Greaves",
    "Gobul Leggings",
    "Yamato Gusoku",
    "Hyuga Hakama",
    "Mutsu Gusoku",
    "Amagi Hakama",
    "Escadora Sheath",
    "Escadora Scala",
    "Escadora Sheath",
    "Escadora Scala",
    "Blango Greaves",
    "Blango Leggings",
    "Lobster Greaves",
    "Lobster Leggings",
    "Ukanlos Hessian",
    "Ukanlos Boots",
    "Indra Leggings",
    "Steadfast Boots",
    "Yaksha Boots",
    "Carnage Boots",
    "Chrome Metal Boots",
    "Chrome Metal Feet",
    "Artian Greaves",
    "Artian Leggings",
    "Artian Greaves S",
    "Artian Leggings S",
    "Artian Greaves S",
    "Artian Leggings S",
    "Dober Greaves",
    "Dober Leggings",
    "Ingot Greaves",
    "Ingot Leggings",
    "Ingot Greaves",
    "Ingot Leggings",
    "Aelucanth Crura",
    "Rhopessa Crura",
    "Aelucanth Tarsi",
    "Rhopessa Tarsi",
    "Obituary Crura",
    "Butterfly Crura",
    "Obituary Tarsi",
    "Butterfly Tarsi",
    "Mosgharl Roots",
    "Mosgharl Radicles",
    "Guild Bard Boots",
    "Scholar's Socks",
    "Guild Bard Gaiters",
    "Scholar's Sandals",
    "Black Belt Greaves",
    "Black Belt Leggings",
    "Guardian Boots",
    "Helper Socks",
    "Guardian Pants",
    "Helper Tights",
    "Shinobi Sky Boots",
    "Shinobi Land Boots",
    "Guild Knight Boots",
    "Maiden's Socks",
    "Guild Knight Tights",
    "Maiden's Tights",
    "Yukumo Sky Hakama",
    "Yukumo Land Hakama",
    "High Metal Greaves",
    "High Metal Leggings",
    "Ranger's Espadrilles",
    "Archer's Espadrilles",
    "Black Leather Chaps",
    "Black Leather Pants",
    "Chakra Anklet",
    "Sailor Socks",
    "Sailor Sandals",
    "Hawkboots",
    "Lecturer's Boots",
    "Hawkfeet",
    "Lecturer's Footwear",
    "Blue Star Boots",
    "Blue Star Footwear",
    "Greaves of Anat",
    "Leggings of Anat",
    "Uniqlo Slacks",
    "Uniqlo Tights",
    "Star Rook Greaves",
    "Star Rook Leggings",
    "dummy706",
    "dummy718",
    "dummy707",
    "dummy719",
    "dummy709",
    "dummy721",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "DUMMY",
    "Hero's Boots",
    "Hero's Leggings",
    "dummy729",
    "dummy730",
    "dummy731",
    "dummy732",
    "EX Rebellion Greaves",
    "EX Riot Leggings",
    "EX Artian Greaves",
    "EX Artian Leggings",
    "EX Gore Greaves",
    "EX Gore Leggings",
    "EX Ingot Greaves",
    "EX Ingot Leggings",
    "EX Kirin Leg Guards U",
    "EX Kirin Boots U",
    "Storge Greaves",
    "Storge Leggings",
    "Storge Greaves S",
    "Storge Leggings S",
    "Storge Greaves",
    "Storge Leggings",
    "Hunter's Greaves",
    "Hunter's Leggings",
    "Alloy Greaves",
    "Alloy Leggings",
    "Ludroth Greaves",
    "Ludroth Leggings",
    "Rathian Greaves",
    "Rathian Leggings",
    "Rath Heart Greaves",
    "Rath Heart Leggings",
    "Rathalos Greaves",
    "Rathalos Leggings",
    "Rath Soul Greaves",
    "Rath Soul Leggings",
    "Silver Solgreaves",
    "Silver Solleggings",
    "Esurient Greaves",
    "Esurient Leggings",
    "Gloaming Greaves",
    "Adamance Pleats",
    "Dayspring Pleats",
    "Epoch Pleats",
    "Tigrex Greaves",
    "Tigrex Leggings",
    "Tigrex Greaves U",
    "Tigrex Leggings U",
    "Akantor Hessian",
    "Akantor Boots",
    "Zinogre Greaves U",
    "Zinogre Leggings U",
    "Gore Greaves",
    "Gore Leggings",
    "Gypceros Greaves",
    "Gypceros Leggings",
    "Gypceros Greaves U",
    "Gypceros Leggings U",
    "Khezu Greaves",
    "Khezu Leggings",
    "Khezu Greaves U",
    "Khezu Leggings U",
    "Kirin Leg Guards",
    "Kirin Boots",
    "Kirin Leg Guards U",
    "Kirin Boots U",
    "Kushala Crus",
    "Kushala Shank",
    "Ceanataur Greaves",
    "Ceanataur Leggings",
    "Auroros Pants",
    "Borealis Hakama",
    "Genesis Pants",
    "Glyph Hakama",
    "Arc Greaves",
    "Arc Leggings",
    "Rebellion Greaves",
    "Riot Leggings",
    "Dragonfeet X",
    "Dragonlegs X",
    "Hermitaur Greaves",
    "Hermitaur Leggings",
    "Lagiacrus Greaves",
    "Lagiacrus Leggings",
    "Escadora Sheath",
    "Escadora Scala",
    "Artian Greaves S",
    "Artian Leggings S",
    "Ingot Greaves",
    "Ingot Leggings",
    "Storge Greaves",
    "Storge Leggings",
    "Velociprey Greaves X",
    "Velociprey Leggings X",
    "Ioprey Greaves X",
    "Ioprey Leggings X",
    "Kecha Greaves X",
    "Kecha Leggings X",
    "Kecha Greaves Z",
    "Kecha Leggings Z",
    "Tetsucabra Greaves X",
    "Tetsucabra Leggings X",
    "Tetsucabra Greaves Z",
    "Tetsucabra Leggings Z",
    "Nerscylla Greaves X",
    "Nerscylla Leggings X",
    "Nerscylla Greaves Z",
    "Nerscylla Leggings Z",
    "Zamtrios Greaves X",
    "Zamtrios Leggings X",
    "Zamtrios Greaves Z",
    "Zamtrios Leggings Z",
    "Najarala Greaves X",
    "Najarala Leggings X",
    "Najarala Greaves Z",
    "Najarala Leggings Z",
    "Seltas Greaves X",
    "Seltas Leggings X",
    "Seltas Greaves Z",
    "Seltas Leggings Z",
    "Gore Greaves X",
    "Gore Leggings X",
    "Gore Cuisses",
    "Gore Jambs",
    "Arc Greaves X",
    "Storge Greaves X",
    "Arc Leggings X",
    "Storge Leggings X",
    "Arc Cuisses",
    "Storge Cuisses",
    "Arc Jambs",
    "Storge Jambs",
    "Gogma Greaves",
    "Gogma Leggings",
    "Gypceros Greaves X",
    "Gypceros Leggings X",
    "Gypceros Cuisses",
    "Gypceros Jambs",
    "Gypceros Greaves Z",
    "Gypceros Leggings Z",
    "Gypceros Cuisses U",
    "Gypceros Jambs U",
    "Lagombi Greaves X",
    "Lagombi Leggings X",
    "Conga Greaves X",
    "Conga Leggings X",
    "Conga Greaves Z",
    "Conga Leggings Z",
    "Khezu Greaves X",
    "Khezu Leggings X",
    "Khezu Cuisses",
    "Khezu Jambs",
    "Khezu Greaves Z",
    "Khezu Leggings Z",
    "Khezu Cuisses U",
    "Khezu Jambs U",
    "Rathian Greaves X",
    "Rathian Leggings X",
    "Rathian Cuisses",
    "Rathian Jambs",
    "Rath Heart Greaves Z",
    "Rath Heart Leggings Z",
    "Rath Heart Cuisses",
    "Rath Heart Jambs",
    "Golden Lunegreaves Z",
    "Golden Luneleggings Z",
    "Rathalos Greaves X",
    "Rathalos Leggings X",
    "Rathalos Cuisses",
    "Rathalos Jambs",
    "Rath Soul Greaves Z",
    "Rath Soul Leggings Z",
    "Rath Soul Cuisses",
    "Rath Soul Jambs",
    "Silver Solgreaves Z",
    "Silver Solleggings Z",
    "Silver Solcuisses",
    "Silver Soljambs",
    "Zinogre Greaves X",
    "Zinogre Leggings X",
    "Zinogre Greaves Z",
    "Zinogre Leggings Z",
    "Zinogre Cuisses U",
    "Zinogre Jambs U",
    "Tigrex Greaves X",
    "Tigrex Leggings X",
    "Tigrex Cuisses",
    "Tigrex Jambs",
    "Tigrex Greaves Z",
    "Tigrex Leggings Z",
    "Tigrex Cuisses U",
    "Tigrex Jambs U",
    "Excello Greaves Z",
    "Excello Leggings Z",
    "Gravios Greaves X",
    "Gravios Leggings X",
    "Gravios Greaves Z",
    "Gravios Leggings Z",
    "Brachydios Greaves X",
    "Brachydios Leggings X",
    "Brachydium Greaves",
    "Brachydium Leggings",
    "Grand Gloaming Greaves",
    "Grand Adamance Pleats",
    "Grand Dayspring Pleats",
    "Grand Epoch Greaves",
    "Gloaming Whitewalkers",
    "Adamance Whitewalkers",
    "Dayspring Whitewalkers",
    "Epoch Whitepleats",
    "Vangis Greaves X",
    "Vangis Leggings X",
    "Esurient Greaves Z",
    "Esurient Leggings Z",
    "Esurient Cuisses",
    "Esurient Jambs",
    "Kaiser Greaves X",
    "Kaiser Leggings X",
    "Akantor Hessian X",
    "Akantor Boots X",
    "Akantor Cuisses",
    "Akantor Jambs",
    "EX Escadora Sheath",
    "EX Escadora Scala",
    "Ukanlos Hessian X",
    "Ukanlos Boots X",
    "Kushala Crus X",
    "Kushala Shank X",
    "Kushala Cuisses",
    "Kushala Jambs",
    "Kujula Crus",
    "Kujula Shank",
    "Grand God's Peer Feet",
    "Grand Hermit Feet",
    "Grand Divine Ire Feet",
    "Grand Crusher Feet",
    "Rebellion Greaves X",
    "Riot Leggings X",
    "Rebellion Cuisses",
    "Riot Jambs",
    "Rebellion Greaves Z",
    "Riot Leggings Z",
    "Cephalos Greaves X",
    "Cephalos Leggings X",
    "Hermitaur Greaves X",
    "Hermitaur Leggings X",
    "Hermitaur Cuisses",
    "Hermitaur Jambs",
    "Hermitaur Greaves Z",
    "Hermitaur Leggings Z",
    "Mono Greaves S",
    "Mono Leggings S",
    "Mono Greaves X",
    "Mono Leggings X",
    "Mono Greaves",
    "Mono Leggings",
    "Mono Cuisses",
    "Mono Jambs",
    "Monodevil Greaves",
    "Monodevil Leggings",
    "Monodevil Greaves",
    "Monodevil Leggings",
    "Monodevil Cuisses",
    "Monodevil Jambs",
    "Diablos Greaves X",
    "Diablos Leggings X",
    "Diablos Greaves",
    "Diablos Leggings",
    "Diablos Cuisses",
    "Diablos Jambs",
    "Diablos Greaves Z",
    "Diablos Leggings Z",
    "Dragonfeet X",
    "Dragonlegs X",
    "Dragoncuisses X",
    "Dragonjambs X",
    "Fatalis Crimsonfeet Z",
    "Fatalis Crimsonlegs Z",
    "Fatalis Crimsonboots Z",
    "Fatalis Crimsonjambs Z",
    "Wrothfeet",
    "Wrothlegs",
    "White Fatalis Feet",
    "White Fatalis Legs",
    "Grand Mizuha Leg Wrap",
    "Grand Cham Trousers",
    "Regios Greaves S",
    "Regios Leggings S",
    "Regios Greaves X",
    "Regios Leggings X",
    "Chaos Greaves",
    "Nephilim Greaves",
    "Chaos Leggings",
    "Nephilim Leggings",
    "Basarios Greaves X",
    "Basarios Leggings X",
    "Basarios Greaves Z",
    "Basarios Leggings Z",
    "Kut-Ku Greaves X",
    "Kut-Ku Leggings X",
    "Kut-Ku Greaves Z",
    "Kut-Ku Leggings Z",
    "Garuga Greaves X",
    "Garuga Leggings X",
    "Kirin Leg Guards X",
    "Kirin Boots X",
    "Kirin Cuisses",
    "Kirin Jambs",
    "Kirin Leg Guards Z",
    "Kirin Boots Z",
    "Kirin Cuisses U",
    "Kirin Jambs U",
    "Bnahabra Boots X",
    "Bnahabra Pants X",
    "DUMMY",
    "DUMMY",
    "Rhenoplos Greaves X",
    "Rhenoplos Leggings X",
    "Hunter's Cuisses",
    "Hunter's Jambs",
    "Alloy Cuisses",
    "Alloy Jambs",
    "Artian Greaves X",
    "Artian Leggings X",
    "Arc Cuisses S",
    "Arc Jambs S",
    "Ingot Cuisses",
    "Ingot Jambs",
    "Guardian Boots X",
    "Helper Socks X",
    "Guardian Pants X",
    "Healer Socks X",
    "Guardian Boots Z",
    "Helper Socks Z",
    "Guardian Pants Z",
    "Healer Socks Z",
    "G. Knight Boots X",
    "Maiden's Socks X",
    "G. Knight Tights X",
    "Exclusive Tights X",
    "Ace Greaves",
    "Sororal Greaves",
    "Ace Leggings",
    "Sororal Leggings",
    "Ceanataur Cuisses",
    "Ceanataur Jambs",
    "Lagiacrus Cuisses",
    "Lagiacrus Jambs",
    "Escadora Cuisses",
    "Escadora Jambs",
    "Auroros Kermes Shins",
    "Borealis Woad Pants",
    "Genesis Kermes Shins",
    "Glyph Woad Pants",
    "Ludroth Cuisses",
    "Ludroth Jambs",
    "Hornet Greaves",
    "Hornet Leggings",
    "Hornet Cuisses",
    "Hornet Jambs",
    "Wroggi Greaves",
    "Wroggi Leggings",
    "Wroggi Cuisses",
    "Wroggi Jambs",
    "Gigginox Greaves",
    "Gigginox Leggings",
    "Gigginox Cuisses",
    "Gigginox Jambs",
    "Tempest Hakama",
    "Welkin Hakama",
    "Tempest Wingpleats",
    "Welkin Wingpleats",
    "Death Stench Heel",
    "Death Stench March",
    "Death Stench Cuisses",
    "Death Stench Jambs",
    "Damascus Greaves",
    "Damascus Leggings",
    "Damascus Cuisses",
    "Damascus Jambs",
    "Lagiacrus Greaves X",
    "Lagiacrus Leggings X",
    "Nargacuga Greaves X",
    "Nargacuga Leggings X",
    "Empress Greaves X",
    "Empress Leggings X",
    "Helios Greaves X",
    "Selene Greaves X",
    "Helios Leggings X",
    "Selene Leggings X",
    "Agnaktor Greaves X",
    "Agnaktor Leggings X",
    "Qurupeco Greaves X",
    "Qurupeco Leggings X",
    "Gobul Greaves X",
    "Gobul Leggings X",
    "Barioth Greaves X",
    "Barioth Leggings X",
    "Barroth Greaves X",
    "Barroth Leggings X",
    "Nibelsnarf Greaves X",
    "Nibelsnarf Leggings X",
    "Duramboros Greaves X",
    "Duramboros Leggings X",
    "Lava Greaves X",
    "Lava Leggings X",
    "Grand Yamato Gusoku",
    "Grand Hyuga Hakama",
    "Grand Mutsu Gusoku",
    "Grand Amagi Hakama",
    "Grand Yaksha Boots",
    "Grand Carnage Boots",
    "Miralis Drogues",
    "Miralis Kedges",
    "Plesioth Greaves Z",
    "Plesioth Leggings Z",
    "Kita Star Hakama",
    "Umi Ocean Hakama",
    "Patissier's Boots",
    "Patissier's Footwear",
    "High Metal Greaves S",
    "High Metal Leggings S",
    "Aelucanth Crura X",
    "Rhopessa Crura X",
    "Aelucanth Tarsi X",
    "Rhopessa Tarsi X",
    "Obituary Crura X",
    "Butterfly Crura X",
    "Obituary Tarsi X",
    "Butterfly Tarsi X",
    "EX Auroros Pants",
    "EX Borealis Hakama",
    "EX Genesis Pants",
    "EX Glyph Hakama",
    "Tempest Hakama",
    "Welkin Hakama",
    "GX Escadora Cuisses",
    "GX Escadora Jambs",
    "GX Dragoncuisses X",
    "GX Dragonjambs X",
    "Star Knight Greaves",
    "Star Knight Leggings",
    "Greaves of Rage",
    "Leggings of Rage",
    "Varia Suit Leg Guards",
    "Zero Suit Boots",
    "Varia Suit Legs",
    "Zero Suit Tights",
    "Varia Suit Leg Guards",
    "Zero Suit Boots",
    "Varia Suit Legs",
    "Zero Suit Tights",
    "DUMMY",
    "DUMMY",
    "Hawkboots X",
    "Lecturer's Boots X",
    "Hawkfeet X",
    "Lecturer's Footwear X",
    "GX Hunter's Cuisses",
    "GX Hunter's Jambs",
    "GX Esurient Cuisses",
    "GX Esurient Jambs",
    "GX Tempest Wingpleats",
    "GX Welkin Wingpleats",
    "GX Fatalis Crimsonboots",
    "GX Fatalis Crimsonjambs",
    "Hunter's Greaves",
    "Hunter's Leggings",
    "Hunter's Greaves",
    "Hunter's Leggings",
    "Ludroth Greaves",
    "Ludroth Leggings",
    "Ludroth Greaves",
    "Ludroth Leggings",
    "Alloy Greaves",
    "Alloy Leggings",
    "Alloy Greaves",
    "Alloy Leggings",
    "Gypceros Greaves",
    "Gypceros Leggings",
    "Gypceros Greaves",
    "Gypceros Leggings",
    "Khezu Greaves",
    "Khezu Leggings",
    "Khezu Greaves",
    "Khezu Leggings",
    "Ingot Greaves",
    "Ingot Leggings",
    "Ingot Greaves",
    "Ingot Leggings",
    "Rathian Greaves",
    "Rathian Leggings",
    "Lagiacrus Greaves",
    "Lagiacrus Leggings",
    "Rathalos Greaves",
    "Rathalos Leggings",
    "Gypceros Greaves U",
    "Gypceros Leggings U",
    "Khezu Greaves U",
    "Khezu Leggings U",
    "Tigrex Greaves",
    "Tigrex Leggings",
    "Kirin Leg Guards",
    "Kirin Boots",
    "Kirin Leg Guards",
    "Kirin Boots",
    "Artian Greaves S",
    "Artian Leggings S",
    "Ceanataur Greaves",
    "Ceanataur Leggings",
    "Ceanataur Greaves",
    "Ceanataur Leggings",
    "Gloaming Greaves",
    "Dayspring Pleats",
    "Adamance Pleats",
    "Epoch Pleats",
    "Zinogre Greaves U",
    "Zinogre Leggings U",
    "Tigrex Greaves U",
    "Tigrex Leggings U",
    "Gore Greaves",
    "Gore Leggings",
    "Auroros Pants",
    "Genesis Pants",
    "Borealis Hakama",
    "Glyph Hakama",
    "Kirin Leg Guards U",
    "Kirin Boots U",
    "Kirin Leg Guards U",
    "Kirin Boots U",
    "Esurient Greaves",
    "Esurient Leggings",
    "Monoblos Greaves",
    "Monoblos Leggings",
    "Hornet Greaves",
    "Hornet Leggings",
    "Wroggi Greaves",
    "Wroggi Leggings",
    "Monodevil Greaves",
    "Monodevil Leggings",
    "Diablos Greaves",
    "Diablos Leggings",
    "Gigginox Greaves",
    "Gigginox Leggings",
    "Death Stench Heel",
    "Death Stench March",
    "Damascus Greaves",
    "Damascus Leggings",
    "DUMMY",
    "DUMMY"
};

enum Legs_e {
    NoLegs,
    Derring_Trousers,
    Derring_Greaves_S,
    Derring_Leggings_S,
    Leather_Trousers,
    Leather_Greaves_S,
    Leather_Leggings_S,
    Chainmail_Trousers,
    Chainmail_Greaves_S,
    Chainmail_Leggings_S,
    Hunter_s_Greaves_0,
    Hunter_s_Leggings_0,
    Hunter_s_Greaves_S,
    Hunter_s_Leggings_S,
    Hunter_s_Greaves_1,
    Hunter_s_Leggings_1,
    Bone_Greaves,
    Bone_Leggings,
    Bone_Greaves_S,
    Bone_Leggings_S,
    Alloy_Greaves_0,
    Alloy_Leggings_0,
    Alloy_Greaves_S,
    Alloy_Leggings_S,
    Alloy_Greaves_1,
    Alloy_Leggings_1,
    Jaggi_Greaves,
    Jaggi_Leggings,
    Jaggi_Greaves_S,
    Jaggi_Leggings_S,
    Loc_Lac_Boots,
    Ludroth_Greaves_0,
    Ludroth_Leggings_0,
    Ludroth_Greaves_1,
    Ludroth_Leggings_1,
    Rhenoplos_Greaves,
    Rhenoplos_Leggings,
    Rhenoplos_Greaves_S,
    Rhenoplos_Leggings_S,
    Bnahabra_Boots,
    Bnahabra_Pants,
    Bnahabra_Boots_S,
    Bnahabra_Pants_S,
    Barroth_Greaves,
    Barroth_Leggings,
    Rathian_Greaves_0,
    Rathian_Leggings_0,
    Rathian_Greaves_S,
    Rathian_Leggings_S,
    Rath_Heart_Greaves_0,
    Rath_Heart_Leggings_0,
    Golden_Lunegreaves,
    Golden_Luneleggings,
    Rathian_Greaves_1,
    Rathian_Leggings_1,
    Rath_Heart_Greaves_1,
    Rath_Heart_Leggings_1,
    EX_Rathian_Greaves,
    EX_Rathian_Leggings,
    Rathalos_Greaves_0,
    Rathalos_Leggings_0,
    Rathalos_Greaves_S,
    Rathalos_Leggings_S,
    Rath_Soul_Greaves_0,
    Rath_Soul_Leggings_0,
    Silver_Solgreaves_0,
    Silver_Solleggings_0,
    Rathalos_Greaves_1,
    Rathalos_Leggings_1,
    Rath_Soul_Greaves_1,
    Rath_Soul_Leggings_1,
    Silver_Solgreaves_1,
    Silver_Solleggings_1,
    EX_Rathalos_Greaves,
    EX_Rathalos_Leggings,
    Diablos_Greaves_0,
    Diablos_Leggings_0,
    Uragaan_Greaves,
    Uragaan_Leggings,
    Vangis_Greaves,
    Vangis_Leggings,
    Esurient_Greaves_0,
    Esurient_Leggings_0,
    Esurient_Greaves_1,
    Esurient_Leggings_1,
    Gloaming_Greaves_0,
    Adamance_Pleats_0,
    Dayspring_Pleats_0,
    Epoch_Pleats_0,
    Gloaming_Archgreaves,
    Adamance_Archpleats,
    Dayspring_Archpleats,
    Epoch_Archpleats,
    Gloaming_Greaves_1,
    Adamance_Pleats_1,
    Dayspring_Pleats_1,
    Epoch_Pleats_1,
    Plesioth_Greaves,
    Plesioth_Leggings,
    Nibelsnarf_Greaves,
    Nibelsnarf_Leggings,
    Duramboros_Greaves,
    Duramboros_Leggings,
    Arzuros_Greaves,
    Arzuros_Leggings,
    Lagombi_Greaves,
    Lagombi_Leggings,
    Lagombi_Greaves_S,
    Lagombi_Leggings_S,
    Nargacuga_Greaves,
    Nargacuga_Leggings,
    Tigrex_Greaves_0,
    Tigrex_Leggings_0,
    Tigrex_Greaves_S,
    Tigrex_Leggings_S,
    Tigrex_Greaves_U_0,
    Tigrex_Leggings_U_0,
    Excello_Greaves,
    Excello_Leggings,
    EX_Tigrex_Greaves,
    EX_Tigrex_Leggings,
    Tigrex_Greaves_1,
    Tigrex_Leggings_1,
    Tigrex_Greaves_U_1,
    Tigrex_Leggings_U_1,
    Brachydios_Greaves,
    Brachydios_Leggings,
    Brachydios_Greaves_S,
    Brachy_Leggings_S,
    Akantor_Hessian_0,
    Akantor_Boots_0,
    Akantor_Hessian_1,
    Akantor_Boots_1,
    Zinogre_Greaves,
    Zinogre_Leggings,
    Zinogre_Greaves_S,
    Zinogre_Leggings_S,
    Zinogre_Greaves_U_0,
    Zinogre_Leggings_U_0,
    Zinogre_Greaves_U_1,
    Zinogre_Leggings_U_1,
    EX_Kaiser_Greaves,
    EX_Kaiser_Leggings,
    Kecha_Greaves,
    Kecha_Leggings,
    Kecha_Greaves_S,
    Kecha_Leggings_S,
    Gore_Greaves_0,
    Gore_Leggings_0,
    Gore_Greaves_S,
    Gore_Leggings_S,
    Gore_Greaves_1,
    Gore_Leggings_1,
    Tetsucabra_Greaves,
    Tetsucabra_Leggings,
    Tetsucabra_Greaves_S,
    Tetsucabra_Leggings_S,
    Nerscylla_Greaves,
    Nerscylla_Leggings,
    Nerscylla_Greaves_S,
    Nerscylla_Leggings_S,
    Najarala_Greaves,
    Najarala_Leggings,
    Najarala_Greaves_S,
    Najarala_Leggings_S,
    Garuga_Greaves,
    Garuga_Leggings,
    Garuga_Greaves_S,
    Garuga_Leggings_S,
    Basarios_Greaves,
    Basarios_Leggings,
    Basarios_Greaves_S,
    Basarios_Leggings_S,
    Basarios_Greaves_U,
    Basarios_Leggings_U,
    Battle_Greaves,
    Battle_Leggings,
    Velociprey_Greaves,
    Velociprey_Leggings,
    Velociprey_Greaves_S,
    Velociprey_Leggings_S,
    Genprey_Greaves,
    Genprey_Leggings,
    Genprey_Greaves_S,
    Genprey_Leggings_S,
    Ioprey_Greaves,
    Ioprey_Leggings,
    Ioprey_Greaves_S,
    Ioprey_Leggings_S,
    Kut_Ku_Greaves,
    Kut_Ku_Leggings,
    Kut_Ku_Greaves_S,
    Kut_Ku_Leggings_S,
    Kut_Ku_Greaves_U,
    Kut_Ku_Leggings_U,
    Gypceros_Greaves_0,
    Gypceros_Leggings_0,
    Gypceros_Greaves_S,
    Gypceros_Leggings_S,
    Gypceros_Greaves_U_0,
    Gypceros_Leggings_U_0,
    Gypceros_Greaves_1,
    Gypceros_Leggings_1,
    Gypceros_Greaves_U_1,
    Gypceros_Leggings_U_1,
    Conga_Greaves,
    Conga_Leggings,
    Conga_Greaves_S,
    Conga_Leggings_S,
    Conga_Greaves_U,
    Conga_Leggings_U,
    Gravios_Greaves,
    Gravios_Leggings,
    Gravios_Greaves_S,
    Gravios_Leggings_S,
    Gravios_Greaves_U,
    Gravios_Leggings_U,
    Khezu_Greaves_0,
    Khezu_Leggings_0,
    Khezu_Greaves_S,
    Khezu_Leggings_S,
    Khezu_Greaves_U_0,
    Khezu_Leggings_U_0,
    Khezu_Greaves_1,
    Khezu_Leggings_1,
    Khezu_Greaves_U_1,
    Khezu_Leggings_U_1,
    Kirin_Leg_Guards_0,
    Kirin_Boots_0,
    Kirin_Leg_Guards_S,
    Kirin_Boots_S,
    Kirin_Leg_Guards_U_0,
    Kirin_Boots_U_0,
    Kirin_Leg_Guards_1,
    Kirin_Boots_1,
    Kirin_Leg_Guards_U_1,
    Kirin_Boots_U_1,
    Kushala_Crus_0,
    Kushala_Shank_0,
    EX_Kushala_Crus,
    EX_Kushala_Shank,
    Kushala_Crus_1,
    Kushala_Shank_1,
    Empress_Greaves,
    Empress_Leggings,
    Ceanataur_Greaves_0,
    Ceanataur_Leggings_0,
    Ceanataur_Greaves_1,
    Ceanataur_Leggings_1,
    Auroros_Pants_0,
    Borealis_Hakama_0,
    Genesis_Pants_0,
    Glyph_Hakama_0,
    Auroros_Pants_1,
    Borealis_Hakama_1,
    Genesis_Pants_1,
    Glyph_Hakama_1,
    Lava_Greaves,
    Lava_Leggings,
    Remobra_Feet,
    Remobra_Tights,
    Remobra_Feet_S,
    Remobra_Tights_S,
    Zamtrios_Greaves,
    Zamtrios_Leggings,
    Zamtrios_Greaves_S,
    Zamtrios_Leggings_S,
    Seltas_Greaves,
    Seltas_Leggings,
    Seltas_Greaves_S,
    Seltas_Leggings_S,
    Arc_Greaves_0,
    Arc_Leggings_0,
    Arc_Greaves_S,
    Arc_Leggings_S,
    Arc_Greaves_1,
    Arc_Leggings_1,
    Kaiser_Greaves,
    Kaiser_Leggings,
    Golden_Hakama,
    Puppeteer_Tabi,
    Divine_Ire_Hakama,
    Mind_Crusher_Tabi,
    Rebellion_Greaves_0,
    Riot_Leggings_0,
    Rebellion_Greaves_1,
    Riot_Leggings_1,
    Dragonfeet_X_0,
    Dragonlegs_X_0,
    Dragonfeet,
    Dragonlegs,
    Fatalis_Crimsonfeet,
    Fatalis_Crimsonlegs,
    Ioprey_Feet,
    Ioprey_Tights,
    Cephalos_Greaves,
    Cephalos_Leggings,
    Mizuha_Leg_Wrap,
    Cham_Trousers,
    Hermitaur_Greaves_0,
    Hermitaur_Leggings_0,
    Hermitaur_Greaves_1,
    Hermitaur_Leggings_1,
    Vespoid_Greaves,
    Vespoid_Leggings,
    Qurupeco_Greaves,
    Qurupeco_Leggings,
    Agnaktor_Greaves,
    Agnaktor_Leggings,
    Barioth_Greaves,
    Barioth_Leggings,
    Volvidon_Greaves,
    Volvidon_Leggings,
    Lagiacrus_Greaves_0,
    Lagiacrus_Leggings_0,
    Lagiacrus_Greaves_1,
    Lagiacrus_Leggings_1,
    Helios_Greaves,
    Helios_Leggings,
    Selene_Greaves,
    Selene_Leggings,
    Gobul_Greaves,
    Gobul_Leggings,
    Yamato_Gusoku,
    Hyuga_Hakama,
    Mutsu_Gusoku,
    Amagi_Hakama,
    Escadora_Sheath_0,
    Escadora_Scala_0,
    Escadora_Sheath_1,
    Escadora_Scala_1,
    Blango_Greaves,
    Blango_Leggings,
    Lobster_Greaves,
    Lobster_Leggings,
    Ukanlos_Hessian,
    Ukanlos_Boots,
    Indra_Leggings,
    Steadfast_Boots,
    Yaksha_Boots,
    Carnage_Boots,
    Chrome_Metal_Boots,
    Chrome_Metal_Feet,
    Artian_Greaves,
    Artian_Leggings,
    Artian_Greaves_S_0,
    Artian_Leggings_S_0,
    Artian_Greaves_S_1,
    Artian_Leggings_S_1,
    Dober_Greaves,
    Dober_Leggings,
    Ingot_Greaves_0,
    Ingot_Leggings_0,
    Ingot_Greaves_1,
    Ingot_Leggings_1,
    Aelucanth_Crura,
    Rhopessa_Crura,
    Aelucanth_Tarsi,
    Rhopessa_Tarsi,
    Obituary_Crura,
    Butterfly_Crura,
    Obituary_Tarsi,
    Butterfly_Tarsi,
    Mosgharl_Roots,
    Mosgharl_Radicles,
    Guild_Bard_Boots,
    Scholar_s_Socks,
    Guild_Bard_Gaiters,
    Scholar_s_Sandals,
    Black_Belt_Greaves,
    Black_Belt_Leggings,
    Guardian_Boots,
    Helper_Socks,
    Guardian_Pants,
    Helper_Tights,
    Shinobi_Sky_Boots,
    Shinobi_Land_Boots,
    Guild_Knight_Boots,
    Maiden_s_Socks,
    Guild_Knight_Tights,
    Maiden_s_Tights,
    Yukumo_Sky_Hakama,
    Yukumo_Land_Hakama,
    High_Metal_Greaves,
    High_Metal_Leggings,
    Ranger_s_Espadrilles,
    Archer_s_Espadrilles,
    Black_Leather_Chaps,
    Black_Leather_Pants,
    Chakra_Anklet,
    Sailor_Socks,
    Sailor_Sandals,
    Hawkboots,
    Lecturer_s_Boots,
    Hawkfeet,
    Lecturer_s_Footwear,
    Blue_Star_Boots,
    Blue_Star_Footwear,
    Greaves_of_Anat,
    Leggings_of_Anat,
    Uniqlo_Slacks,
    Uniqlo_Tights,
    Star_Rook_Greaves,
    Star_Rook_Leggings,
    dummy_legs706,
    dummy_legs718,
    dummy_legs707,
    dummy_legs719,
    dummy_legs709,
    dummy_legs721,
    dummy_legs_0,
    dummy_legs_1,
    dummy_legs_2,
    dummy_legs_3,
    Hero_s_Boots,
    Hero_s_Leggings,
    dummy_legs729,
    dummy_legs730,
    dummy_legs731,
    dummy_legs732,
    EX_Rebellion_Greaves,
    EX_Riot_Leggings,
    EX_Artian_Greaves,
    EX_Artian_Leggings,
    EX_Gore_Greaves,
    EX_Gore_Leggings,
    EX_Ingot_Greaves,
    EX_Ingot_Leggings,
    EX_Kirin_Leg_Guards_U,
    EX_Kirin_Boots_U,
    Storge_Greaves_0,
    Storge_Leggings_0,
    Storge_Greaves_S,
    Storge_Leggings_S,
    Storge_Greaves_1,
    Storge_Leggings_1,
    Hunter_s_Greaves_2,
    Hunter_s_Leggings_2,
    Alloy_Greaves_2,
    Alloy_Leggings_2,
    Ludroth_Greaves_2,
    Ludroth_Leggings_2,
    Rathian_Greaves_2,
    Rathian_Leggings_2,
    Rath_Heart_Greaves_2,
    Rath_Heart_Leggings_2,
    Rathalos_Greaves_2,
    Rathalos_Leggings_2,
    Rath_Soul_Greaves_2,
    Rath_Soul_Leggings_2,
    Silver_Solgreaves_2,
    Silver_Solleggings_2,
    Esurient_Greaves_2,
    Esurient_Leggings_2,
    Gloaming_Greaves_2,
    Adamance_Pleats_2,
    Dayspring_Pleats_2,
    Epoch_Pleats_2,
    Tigrex_Greaves_2,
    Tigrex_Leggings_2,
    Tigrex_Greaves_U_2,
    Tigrex_Leggings_U_2,
    Akantor_Hessian_2,
    Akantor_Boots_2,
    Zinogre_Greaves_U_2,
    Zinogre_Leggings_U_2,
    Gore_Greaves_2,
    Gore_Leggings_2,
    Gypceros_Greaves_2,
    Gypceros_Leggings_2,
    Gypceros_Greaves_U_2,
    Gypceros_Leggings_U_2,
    Khezu_Greaves_2,
    Khezu_Leggings_2,
    Khezu_Greaves_U_2,
    Khezu_Leggings_U_2,
    Kirin_Leg_Guards_2,
    Kirin_Boots_2,
    Kirin_Leg_Guards_U_2,
    Kirin_Boots_U_2,
    Kushala_Crus_2,
    Kushala_Shank_2,
    Ceanataur_Greaves_2,
    Ceanataur_Leggings_2,
    Auroros_Pants_2,
    Borealis_Hakama_2,
    Genesis_Pants_2,
    Glyph_Hakama_2,
    Arc_Greaves_2,
    Arc_Leggings_2,
    Rebellion_Greaves_2,
    Riot_Leggings_2,
    Dragonfeet_X_1,
    Dragonlegs_X_1,
    Hermitaur_Greaves_2,
    Hermitaur_Leggings_2,
    Lagiacrus_Greaves_2,
    Lagiacrus_Leggings_2,
    Escadora_Sheath_2,
    Escadora_Scala_2,
    Artian_Greaves_S_2,
    Artian_Leggings_S_2,
    Ingot_Greaves_2,
    Ingot_Leggings_2,
    Storge_Greaves_2,
    Storge_Leggings_2,
    Velociprey_Greaves_X,
    Velociprey_Leggings_X,
    Ioprey_Greaves_X,
    Ioprey_Leggings_X,
    Kecha_Greaves_X,
    Kecha_Leggings_X,
    Kecha_Greaves_Z,
    Kecha_Leggings_Z,
    Tetsucabra_Greaves_X,
    Tetsucabra_Leggings_X,
    Tetsucabra_Greaves_Z,
    Tetsucabra_Leggings_Z,
    Nerscylla_Greaves_X,
    Nerscylla_Leggings_X,
    Nerscylla_Greaves_Z,
    Nerscylla_Leggings_Z,
    Zamtrios_Greaves_X,
    Zamtrios_Leggings_X,
    Zamtrios_Greaves_Z,
    Zamtrios_Leggings_Z,
    Najarala_Greaves_X,
    Najarala_Leggings_X,
    Najarala_Greaves_Z,
    Najarala_Leggings_Z,
    Seltas_Greaves_X,
    Seltas_Leggings_X,
    Seltas_Greaves_Z,
    Seltas_Leggings_Z,
    Gore_Greaves_X,
    Gore_Leggings_X,
    Gore_Cuisses,
    Gore_Jambs,
    Arc_Greaves_X,
    Storge_Greaves_X,
    Arc_Leggings_X,
    Storge_Leggings_X,
    Arc_Cuisses,
    Storge_Cuisses,
    Arc_Jambs,
    Storge_Jambs,
    Gogma_Greaves,
    Gogma_Leggings,
    Gypceros_Greaves_X,
    Gypceros_Leggings_X,
    Gypceros_Cuisses,
    Gypceros_Jambs,
    Gypceros_Greaves_Z,
    Gypceros_Leggings_Z,
    Gypceros_Cuisses_U,
    Gypceros_Jambs_U,
    Lagombi_Greaves_X,
    Lagombi_Leggings_X,
    Conga_Greaves_X,
    Conga_Leggings_X,
    Conga_Greaves_Z,
    Conga_Leggings_Z,
    Khezu_Greaves_X,
    Khezu_Leggings_X,
    Khezu_Cuisses,
    Khezu_Jambs,
    Khezu_Greaves_Z,
    Khezu_Leggings_Z,
    Khezu_Cuisses_U,
    Khezu_Jambs_U,
    Rathian_Greaves_X,
    Rathian_Leggings_X,
    Rathian_Cuisses,
    Rathian_Jambs,
    Rath_Heart_Greaves_Z,
    Rath_Heart_Leggings_Z,
    Rath_Heart_Cuisses,
    Rath_Heart_Jambs,
    Golden_Lunegreaves_Z,
    Golden_Luneleggings_Z,
    Rathalos_Greaves_X,
    Rathalos_Leggings_X,
    Rathalos_Cuisses,
    Rathalos_Jambs,
    Rath_Soul_Greaves_Z,
    Rath_Soul_Leggings_Z,
    Rath_Soul_Cuisses,
    Rath_Soul_Jambs,
    Silver_Solgreaves_Z,
    Silver_Solleggings_Z,
    Silver_Solcuisses,
    Silver_Soljambs,
    Zinogre_Greaves_X,
    Zinogre_Leggings_X,
    Zinogre_Greaves_Z,
    Zinogre_Leggings_Z,
    Zinogre_Cuisses_U,
    Zinogre_Jambs_U,
    Tigrex_Greaves_X,
    Tigrex_Leggings_X,
    Tigrex_Cuisses,
    Tigrex_Jambs,
    Tigrex_Greaves_Z,
    Tigrex_Leggings_Z,
    Tigrex_Cuisses_U,
    Tigrex_Jambs_U,
    Excello_Greaves_Z,
    Excello_Leggings_Z,
    Gravios_Greaves_X,
    Gravios_Leggings_X,
    Gravios_Greaves_Z,
    Gravios_Leggings_Z,
    Brachydios_Greaves_X,
    Brachydios_Leggings_X,
    Brachydium_Greaves,
    Brachydium_Leggings,
    Grand_Gloaming_Greaves,
    Grand_Adamance_Pleats,
    Grand_Dayspring_Pleats,
    Grand_Epoch_Greaves,
    Gloaming_Whitewalkers,
    Adamance_Whitewalkers,
    Dayspring_Whitewalkers,
    Epoch_Whitepleats,
    Vangis_Greaves_X,
    Vangis_Leggings_X,
    Esurient_Greaves_Z,
    Esurient_Leggings_Z,
    Esurient_Cuisses,
    Esurient_Jambs,
    Kaiser_Greaves_X,
    Kaiser_Leggings_X,
    Akantor_Hessian_X,
    Akantor_Boots_X,
    Akantor_Cuisses,
    Akantor_Jambs,
    EX_Escadora_Sheath,
    EX_Escadora_Scala,
    Ukanlos_Hessian_X,
    Ukanlos_Boots_X,
    Kushala_Crus_X,
    Kushala_Shank_X,
    Kushala_Cuisses,
    Kushala_Jambs,
    Kujula_Crus,
    Kujula_Shank,
    Grand_God_s_Peer_Feet,
    Grand_Hermit_Feet,
    Grand_Divine_Ire_Feet,
    Grand_Crusher_Feet,
    Rebellion_Greaves_X,
    Riot_Leggings_X,
    Rebellion_Cuisses,
    Riot_Jambs,
    Rebellion_Greaves_Z,
    Riot_Leggings_Z,
    Cephalos_Greaves_X,
    Cephalos_Leggings_X,
    Hermitaur_Greaves_X,
    Hermitaur_Leggings_X,
    Hermitaur_Cuisses,
    Hermitaur_Jambs,
    Hermitaur_Greaves_Z,
    Hermitaur_Leggings_Z,
    Mono_Greaves_S,
    Mono_Leggings_S,
    Mono_Greaves_X,
    Mono_Leggings_X,
    Mono_Greaves,
    Mono_Leggings,
    Mono_Cuisses,
    Mono_Jambs,
    Monodevil_Greaves_0,
    Monodevil_Leggings_0,
    Monodevil_Greaves_1,
    Monodevil_Leggings_1,
    Monodevil_Cuisses,
    Monodevil_Jambs,
    Diablos_Greaves_X,
    Diablos_Leggings_X,
    Diablos_Greaves_1,
    Diablos_Leggings_1,
    Diablos_Cuisses,
    Diablos_Jambs,
    Diablos_Greaves_Z,
    Diablos_Leggings_Z,
    Dragonfeet_X_2,
    Dragonlegs_X_2,
    Dragoncuisses_X,
    Dragonjambs_X,
    Fatalis_Crimsonfeet_Z,
    Fatalis_Crimsonlegs_Z,
    Fatalis_Crimsonboots_Z,
    Fatalis_Crimsonjambs_Z,
    Wrothfeet,
    Wrothlegs,
    White_Fatalis_Feet,
    White_Fatalis_Legs,
    Grand_Mizuha_Leg_Wrap,
    Grand_Cham_Trousers,
    Regios_Greaves_S,
    Regios_Leggings_S,
    Regios_Greaves_X,
    Regios_Leggings_X,
    Chaos_Greaves,
    Nephilim_Greaves,
    Chaos_Leggings,
    Nephilim_Leggings,
    Basarios_Greaves_X,
    Basarios_Leggings_X,
    Basarios_Greaves_Z,
    Basarios_Leggings_Z,
    Kut_Ku_Greaves_X,
    Kut_Ku_Leggings_X,
    Kut_Ku_Greaves_Z,
    Kut_Ku_Leggings_Z,
    Garuga_Greaves_X,
    Garuga_Leggings_X,
    Kirin_Leg_Guards_X,
    Kirin_Boots_X,
    Kirin_Cuisses,
    Kirin_Jambs,
    Kirin_Leg_Guards_Z,
    Kirin_Boots_Z,
    Kirin_Cuisses_U,
    Kirin_Jambs_U,
    Bnahabra_Boots_X,
    Bnahabra_Pants_X,
    dummy_legs_4,
    dummy_legs_5,
    Rhenoplos_Greaves_X,
    Rhenoplos_Leggings_X,
    Hunter_s_Cuisses,
    Hunter_s_Jambs,
    Alloy_Cuisses,
    Alloy_Jambs,
    Artian_Greaves_X,
    Artian_Leggings_X,
    Arc_Cuisses_S,
    Arc_Jambs_S,
    Ingot_Cuisses,
    Ingot_Jambs,
    Guardian_Boots_X,
    Helper_Socks_X,
    Guardian_Pants_X,
    Healer_Socks_X,
    Guardian_Boots_Z,
    Helper_Socks_Z,
    Guardian_Pants_Z,
    Healer_Socks_Z,
    G__Knight_Boots_X,
    Maiden_s_Socks_X,
    G__Knight_Tights_X,
    Exclusive_Tights_X,
    Ace_Greaves,
    Sororal_Greaves,
    Ace_Leggings,
    Sororal_Leggings,
    Ceanataur_Cuisses,
    Ceanataur_Jambs,
    Lagiacrus_Cuisses,
    Lagiacrus_Jambs,
    Escadora_Cuisses,
    Escadora_Jambs,
    Auroros_Kermes_Shins,
    Borealis_Woad_Pants,
    Genesis_Kermes_Shins,
    Glyph_Woad_Pants,
    Ludroth_Cuisses,
    Ludroth_Jambs,
    Hornet_Greaves_0,
    Hornet_Leggings_0,
    Hornet_Cuisses,
    Hornet_Jambs,
    Wroggi_Greaves_0,
    Wroggi_Leggings_0,
    Wroggi_Cuisses,
    Wroggi_Jambs,
    Gigginox_Greaves_0,
    Gigginox_Leggings_0,
    Gigginox_Cuisses,
    Gigginox_Jambs,
    Tempest_Hakama_0,
    Welkin_Hakama_0,
    Tempest_Wingpleats,
    Welkin_Wingpleats,
    Death_Stench_Heel_0,
    Death_Stench_March_0,
    Death_Stench_Cuisses,
    Death_Stench_Jambs,
    Damascus_Greaves_0,
    Damascus_Leggings_0,
    Damascus_Cuisses,
    Damascus_Jambs,
    Lagiacrus_Greaves_X,
    Lagiacrus_Leggings_X,
    Nargacuga_Greaves_X,
    Nargacuga_Leggings_X,
    Empress_Greaves_X,
    Empress_Leggings_X,
    Helios_Greaves_X,
    Selene_Greaves_X,
    Helios_Leggings_X,
    Selene_Leggings_X,
    Agnaktor_Greaves_X,
    Agnaktor_Leggings_X,
    Qurupeco_Greaves_X,
    Qurupeco_Leggings_X,
    Gobul_Greaves_X,
    Gobul_Leggings_X,
    Barioth_Greaves_X,
    Barioth_Leggings_X,
    Barroth_Greaves_X,
    Barroth_Leggings_X,
    Nibelsnarf_Greaves_X,
    Nibelsnarf_Leggings_X,
    Duramboros_Greaves_X,
    Duramboros_Leggings_X,
    Lava_Greaves_X,
    Lava_Leggings_X,
    Grand_Yamato_Gusoku,
    Grand_Hyuga_Hakama,
    Grand_Mutsu_Gusoku,
    Grand_Amagi_Hakama,
    Grand_Yaksha_Boots,
    Grand_Carnage_Boots,
    Miralis_Drogues,
    Miralis_Kedges,
    Plesioth_Greaves_Z,
    Plesioth_Leggings_Z,
    Kita_Star_Hakama,
    Umi_Ocean_Hakama,
    Patissier_s_Boots,
    Patissier_s_Footwear,
    High_Metal_Greaves_S,
    High_Metal_Leggings_S,
    Aelucanth_Crura_X,
    Rhopessa_Crura_X,
    Aelucanth_Tarsi_X,
    Rhopessa_Tarsi_X,
    Obituary_Crura_X,
    Butterfly_Crura_X,
    Obituary_Tarsi_X,
    Butterfly_Tarsi_X,
    EX_Auroros_Pants,
    EX_Borealis_Hakama,
    EX_Genesis_Pants,
    EX_Glyph_Hakama,
    Tempest_Hakama_1,
    Welkin_Hakama_1,
    GX_Escadora_Cuisses,
    GX_Escadora_Jambs,
    GX_Dragoncuisses_X,
    GX_Dragonjambs_X,
    Star_Knight_Greaves,
    Star_Knight_Leggings,
    Greaves_of_Rage,
    Leggings_of_Rage,
    Varia_Suit_Leg_Guards_0,
    Zero_Suit_Boots_0,
    Varia_Suit_Legs_0,
    Zero_Suit_Tights_0,
    Varia_Suit_Leg_Guards_1,
    Zero_Suit_Boots_1,
    Varia_Suit_Legs_1,
    Zero_Suit_Tights_1,
    dummy_legs_6,
    dummy_legs_7,
    Hawkboots_X,
    Lecturer_s_Boots_X,
    Hawkfeet_X,
    Lecturer_s_Footwear_X,
    GX_Hunter_s_Cuisses,
    GX_Hunter_s_Jambs,
    GX_Esurient_Cuisses,
    GX_Esurient_Jambs,
    GX_Tempest_Wingpleats,
    GX_Welkin_Wingpleats,
    GX_Fatalis_Crimsonboots,
    GX_Fatalis_Crimsonjambs,
    Hunter_s_Greaves_3,
    Hunter_s_Leggings_3,
    Hunter_s_Greaves_4,
    Hunter_s_Leggings_4,
    Ludroth_Greaves_3,
    Ludroth_Leggings_3,
    Ludroth_Greaves_4,
    Ludroth_Leggings_4,
    Alloy_Greaves_3,
    Alloy_Leggings_3,
    Alloy_Greaves_4,
    Alloy_Leggings_4,
    Gypceros_Greaves_3,
    Gypceros_Leggings_3,
    Gypceros_Greaves_4,
    Gypceros_Leggings_4,
    Khezu_Greaves_3,
    Khezu_Leggings_3,
    Khezu_Greaves_4,
    Khezu_Leggings_4,
    Ingot_Greaves_3,
    Ingot_Leggings_3,
    Ingot_Greaves_4,
    Ingot_Leggings_4,
    Rathian_Greaves_3,
    Rathian_Leggings_3,
    Lagiacrus_Greaves_3,
    Lagiacrus_Leggings_3,
    Rathalos_Greaves_3,
    Rathalos_Leggings_3,
    Gypceros_Greaves_U_3,
    Gypceros_Leggings_U_3,
    Khezu_Greaves_U_3,
    Khezu_Leggings_U_3,
    Tigrex_Greaves_3,
    Tigrex_Leggings_3,
    Kirin_Leg_Guards_3,
    Kirin_Boots_3,
    Kirin_Leg_Guards_4,
    Kirin_Boots_4,
    Artian_Greaves_S_3,
    Artian_Leggings_S_3,
    Ceanataur_Greaves_3,
    Ceanataur_Leggings_3,
    Ceanataur_Greaves_4,
    Ceanataur_Leggings_4,
    Gloaming_Greaves_3,
    Dayspring_Pleats_3,
    Adamance_Pleats_3,
    Epoch_Pleats_3,
    Zinogre_Greaves_U_3,
    Zinogre_Leggings_U_3,
    Tigrex_Greaves_U_3,
    Tigrex_Leggings_U_3,
    Gore_Greaves_3,
    Gore_Leggings_3,
    Auroros_Pants_3,
    Genesis_Pants_3,
    Borealis_Hakama_3,
    Glyph_Hakama_3,
    Kirin_Leg_Guards_U_3,
    Kirin_Boots_U_3,
    Kirin_Leg_Guards_U_4,
    Kirin_Boots_U_4,
    Esurient_Greaves_3,
    Esurient_Leggings_3,
    Monoblos_Greaves,
    Monoblos_Leggings,
    Hornet_Greaves_1,
    Hornet_Leggings_1,
    Wroggi_Greaves_1,
    Wroggi_Leggings_1,
    Monodevil_Greaves_2,
    Monodevil_Leggings_2,
    Diablos_Greaves_2,
    Diablos_Leggings_2,
    Gigginox_Greaves_1,
    Gigginox_Leggings_1,
    Death_Stench_Heel_1,
    Death_Stench_March_1,
    Damascus_Greaves_1,
    Damascus_Leggings_1,
    dummy_legs_8,
    dummy_legs_9
};
}
