#pragma once

namespace MH4U {
constexpr const char* Em_s[] = {
    "No enemy",
    "Rathian",
    "Rathalos",
    "Pink Rathian",
    "Azure Rathalos",
    "Gold Rathian",
    "Silver Rathalos",
    "Yian Kut-Ku",
    "Blue Yian Kut-Ku",
    "Gypceros",
    "Purple Gypceros",
    "Tigrex",
    "Brute Tigrex",
    "Gendrome",
    "Iodrome",
    "Great Jaggi",
    "Velocidrome",
    "Congalala",
    "Emerald Congalala",
    "Rajang",
    "Kecha Wacha",
    "Tetsucabra",
    "Zamtrios",
    "Najarala",
    "Dalamadur",
    "Seltas",
    "Seltas Queen",
    "Nerscylla",
    "Gore Magala",
    "Shagaru Magala",
    "Yian Garuga",
    "Kushala Daora",
    "Teostra",
    "Akantor",
    "Kirin",
    "Oroshi Kirin",
    "Khezu",
    "Red Khezu",
    "Basarios",
    "Ruby Basarios",
    "Gravios",
    "Black Gravios",
    "Deviljho",
    "Deviljho",
    "Brachydios",
    "Rajang",
    "Dah'ren Mohran",
    "Lagombi",
    "Zinogre",
    "Stygian Zinogre",
    "Gargwa",
    "Rhenoplos",
    "Aptonoth",
    "Popo",
    "Slagtoth",
    "Slagtoth",
    "Jaggi",
    "Jaggia",
    "Velociprey",
    "Genprey",
    "Ioprey",
    "Remobra",
    "Delex",
    "Conga",
    "Kelbi",
    "Felyne",
    "Melynx",
    "Altaroth",
    "Bnahabra",
    "Bnahabra",
    "Bnahabra",
    "Bnahabra",
    "Zamite",
    "Konchu",
    "Konchu",
    "Konchu",
    "Konchu",
    "Fatalis",
    "Fatalis",
    "Fatalis",
    "Molten Tigrex",
    "rock",
    "Kushala Daora",
    "Dalamadur",
    "rock",
    "rock",
    "rock",
    "rock",
    "Seregios",
    "Gogmazios",
    "Ash Kecha Wacha",
    "Berserk Tetsucabra",
    "Tigerstripe Zamtrios",
    "Tidal Najarala",
    "Desert Seltas",
    "Desert Seltas Queen",
    "Shrouded Nerscylla",
    "Gore Magala",
    "Raging Brachydios",
    "Diablos",
    "Black Diablos",
    "Monoblos",
    "White Monoblos",
    "Chameleos",
    "DUMMY",
    "Cephadrome",
    "Cephalos",
    "Daimyo Hermitaur",
    "Plum D.Hermitaur",
    "Hermitaur",
    "Shah Dalamadur",
    "Shah Dalamadur",
    "Rajang",
    "Deviljho",
    "Zinogre",
    "Gravios",
    "Ukanlos",
    "Fatalis",
    "Apceros",
    "Diablos",
    "Tidal Najarala",
    "Tigrex",
    "Seregios"
};
}